import{requireBackend}from'./supabase';
const text=v=>String(v??'').trim().toUpperCase();
const backend=()=>{try{return requireBackend()}catch(e){throw new Error('LIVE DATA CONNECTION IS NOT READY ON THIS DEPLOYMENT. DEPLOYMENT BACKEND CONFIGURATION IS REQUIRED.')}};
export async function loadAccountantWorkspace(){const{data,error}=await backend().rpc('accountant_workspace_buttons');if(error)throw error;if(data==null)return[];if(!Array.isArray(data))throw new Error('INVALID ACCOUNTANT WORKSPACE RESPONSE');return data.filter(x=>x&&x.enabled!==false&&text(x.label)).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0));}
export async function loadAccountantStock(){const{data,error}=await backend().rpc('accountant_stock_requirement_view');if(error)throw error;if(!Array.isArray(data))throw new Error('INVALID ACCOUNTANT STOCK RESPONSE');return data;}
export async function submitAccountantStockRequirement(itemId,qty,stockQty=0){const n=Number(qty);if(!itemId||!Number.isFinite(n)||n<=0)throw new Error('VALID REQUIRED QUANTITY REQUIRED');const{data,error}=await backend().rpc('submit_purchase_requirement',{p_item:itemId,p_qty:n,p_reason_type:Number(stockQty)<=0?'out_of_stock':'more_qty_required',p_reason:'ACCOUNTANT STOCK REQUIREMENT',p_dealer:null});if(error)throw error;return data;}
export async function loadAccountantDealerRequests(){const{data,error}=await backend().rpc('accountant_dealer_requests');if(error)throw error;if(!Array.isArray(data))throw new Error('INVALID DEALER VERIFICATION RESPONSE');return data;}
export async function updateAccountantDealerRequest(v={}){const{error}=await backend().rpc('accountant_update_dealer_request',{p_dealer:v.id,p_shop_name:text(v.shop_name),p_contact_person:text(v.contact_person),p_mobile:String(v.mobile||''),p_whatsapp:String(v.whatsapp||v.mobile||''),p_address:text(v.address),p_city:text(v.city),p_district:text(v.district),p_state:text(v.state),p_pin_code:String(v.pin_code||''),p_note:text(v.accountant_verification_note)});if(error)throw error;}
export async function submitDealerToAdmin(id,note=''){const{error}=await backend().rpc('accountant_submit_dealer_to_admin',{p_dealer:id,p_note:text(note)||null});if(error)throw error;}
export async function rejectDealerAtAccountant(id,reason){if(!text(reason))throw new Error('REJECTION REASON REQUIRED');const{error}=await backend().rpc('accountant_reject_dealer_request',{p_dealer:id,p_reason:text(reason)});if(error)throw error;}
export async function adminReturnDealerToAccountant(id,reason){if(!text(reason))throw new Error('RETURN REASON REQUIRED');const{error}=await backend().rpc('admin_return_dealer_to_accountant',{p_dealer:id,p_reason:text(reason)});if(error)throw error;}
export async function adminSaveAccountantWorkspaceButton(input={}){const label=text(input.label),description=text(input.description),sort=Number(input.sort_order);if(!label||label.length>50)throw new Error('VALID BUTTON NAME REQUIRED');if(description.length>140)throw new Error('DESCRIPTION TOO LONG');if(!Number.isInteger(sort)||sort<1||sort>99)throw new Error('SORT ORDER MUST BE 1 TO 99');const{data,error}=await backend().rpc('admin_save_accountant_workspace_button',{p_id:input.id||null,p_label:label,p_description:description||null,p_sort_order:sort,p_enabled:input.enabled!==false});if(error)throw error;return data;}
