import{requireBackend}from'./supabase';
const db=()=>requireBackend();
const statuses=new Set(['','DEALER_SELECTED','CONTACTED','CONVERTED','CLOSED']);
const actions=new Set(['MARK_CONTACTED','MARK_CONVERTED','CLOSE','REOPEN']);
const transitions={MARK_CONTACTED:new Set(['DEALER_SELECTED']),MARK_CONVERTED:new Set(['DEALER_SELECTED','CONTACTED']),CLOSE:new Set(['DEALER_SELECTED','CONTACTED']),REOPEN:new Set(['CLOSED','CONVERTED'])};
const clean=(v,max=200)=>String(v||'').trim().slice(0,max);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const iso=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()};
const normalizeRow=r=>({...r,referral_id:UUID.test(clean(r?.referral_id,40))?clean(r.referral_id,40):null,enquiry_id:UUID.test(clean(r?.enquiry_id,40))?clean(r.enquiry_id,40):null,dealer_id:UUID.test(clean(r?.dealer_id,40))?clean(r.dealer_id,40):null,product_id:UUID.test(clean(r?.product_id,40))?clean(r.product_id,40):null,referral_code:clean(r?.referral_code,80).toUpperCase(),status:clean(r?.status,40).toUpperCase(),lead_source:clean(r?.lead_source,40).toUpperCase(),customer_name:clean(r?.customer_name,160).toUpperCase(),mobile_whatsapp:clean(r?.mobile_whatsapp,20).replace(/\D/g,'').slice(-10),pin_code:clean(r?.pin_code,10).replace(/\D/g,'').slice(0,6),item_code:clean(r?.item_code,120).toUpperCase(),product_name:clean(r?.product_name,240).toUpperCase(),shop_name:clean(r?.shop_name,180).toUpperCase(),owner_note:clean(r?.owner_note,1000).toUpperCase(),created_at:iso(r?.created_at),contacted_at:iso(r?.contacted_at),converted_at:iso(r?.converted_at),closed_at:iso(r?.closed_at),last_activity_at:iso(r?.last_activity_at)});
export function canUpdateAdminPublicReferral(row,action){const a=clean(action,40).toUpperCase(),s=clean(row?.status,40).toUpperCase();return actions.has(a)&&transitions[a]?.has(s)===true}
export async function loadAdminPublicReferrals({status='',search='',limit=100}={}){const s=clean(status,40).toUpperCase();if(!statuses.has(s))throw new Error('INVALID REFERRAL STATUS');const{data,error}=await db().rpc('admin_public_referral_crm',{p_status:s||null,p_search:clean(search,160).toUpperCase()||null,p_limit:Math.max(1,Math.min(Number(limit)||100,500))});if(error)throw error;return(Array.isArray(data)?data:[]).map(normalizeRow).filter(r=>r.referral_id&&statuses.has(r.status))}
export async function loadAdminPublicReferralSummary(){const{data,error}=await db().rpc('admin_public_referral_summary');if(error)throw error;const r=Array.isArray(data)?data[0]:data;const total=Math.max(0,Number(r?.total)||0),awaiting=Math.max(0,Number(r?.awaiting_followup)||0),contacted=Math.max(0,Number(r?.contacted)||0),converted=Math.max(0,Number(r?.converted)||0),closed=Math.max(0,Number(r?.closed)||0),rate=Math.max(0,Math.min(100,Number(r?.conversion_rate)||0));return{total,awaiting_followup:awaiting,contacted,converted,closed,conversion_rate:rate}}
export async function updateAdminPublicReferral(referralId,action,note='',currentStatus=null){const id=clean(referralId,40),a=clean(action,40).toUpperCase(),n=clean(note,1000).toUpperCase();if(!UUID.test(id))throw new Error('INVALID REFERRAL ID');if(!actions.has(a))throw new Error('INVALID REFERRAL ACTION');if(currentStatus&&!canUpdateAdminPublicReferral({status:currentStatus},a))throw new Error('REFERRAL STATUS CHANGED. REFRESH AND TRY AGAIN.');const{data,error}=await db().rpc('admin_update_public_referral',{p_referral_id:id,p_action:a,p_note:n||null});if(error)throw error;const r=Array.isArray(data)?data[0]||null:data||null;if(!r)throw new Error('REFERRAL UPDATE NOT CONFIRMED');const normalized=normalizeRow(r);if(!normalized.referral_id)throw new Error('INVALID REFERRAL UPDATE RESPONSE');return normalized}
