import{requireBackend}from'./supabase';
const rpc=async(name,args={})=>{const{data,error}=await requireBackend().rpc(name,args);if(error)throw error;return data};
const id=v=>String(v||'').trim(),note=(v,max=1000)=>{const x=String(v||'').trim();if(x.length>max)throw new Error(`NOTE MUST BE ${max} CHARACTERS OR LESS`);return x||null};
export const loadAdminCustomerLeads=async(status='',limit=100)=>{const s=String(status||'').trim().toLowerCase()||null;const n=Math.max(1,Math.min(Number(limit)||100,500));const data=await rpc('admin_customer_lead_center',{p_status:s,p_limit:n});return Array.isArray(data)?data:[]};
export const routeAdminCustomerLead=async(demandId,dealerId,stage='TORVO_ASSIGNED')=>{const d=id(demandId),x=id(dealerId),s=String(stage||'TORVO_ASSIGNED').trim().toUpperCase();if(!d||!x)throw new Error('DEMAND AND DEALER REQUIRED');if(!['LOCAL','EXTENDED','TORVO_ASSIGNED'].includes(s))throw new Error('INVALID ROUTING STAGE');const data=await rpc('admin_route_customer_demand_to_dealer',{p_demand_id:d,p_dealer_id:x,p_routing_stage:s});if(!data)throw new Error('CUSTOMER LEAD ROUTING FAILED');return data};
export const notifyAdminCustomerLeadDealer=async leadId=>{const x=id(leadId);if(!x)throw new Error('ASSIGNED CUSTOMER LEAD REQUIRED');const data=await rpc('admin_notify_customer_demand_dealer',{p_lead_id:x});if(!data)throw new Error('DEALER NOTIFICATION FAILED');return data};
export const markAdminCustomerDemandAvailable=async(demandId,{dealerId=null,contactNote=null,sourcingNote=null}={})=>{const x=id(demandId),dealer=id(dealerId)||null;if(!x)throw new Error('CUSTOMER REQUIREMENT REQUIRED');const data=await rpc('admin_mark_customer_demand_available',{p_demand_id:x,p_found_dealer_id:dealer,p_found_contact_note:note(contactNote),p_sourcing_note:note(sourcingNote)});if(data!==true)throw new Error('AVAILABLE STATUS UPDATE FAILED');return true};
export const convertAdminCustomerDemand=async(demandId,reason='')=>{const x=id(demandId);if(!x)throw new Error('CUSTOMER REQUIREMENT REQUIRED');const data=await rpc('admin_convert_customer_demand',{p_demand_id:x,p_reason:note(reason,500)});if(data!==true)throw new Error('CUSTOMER DEMAND CONVERSION FAILED');return true};
export const closeAdminCustomerLead=async(demandId,reason)=>{const d=id(demandId),r=String(reason||'').trim();if(!d)throw new Error('CUSTOMER REQUIREMENT REQUIRED');if(r.length<3)throw new Error('CLOSE REASON REQUIRED');if(r.length>500)throw new Error('CLOSE REASON MUST BE 500 CHARACTERS OR LESS');const data=await rpc('admin_close_customer_demand_lead',{p_demand_id:d,p_reason:r});if(data!==true)throw new Error('CUSTOMER LEAD CLOSE FAILED');return true};
