import{requireBackend}from'./supabase';
const db=()=>requireBackend();
const statuses=new Set(['','DEALER_SELECTED','CONTACTED','CONVERTED','CLOSED']);
const actions=new Set(['MARK_CONTACTED','MARK_CONVERTED','CLOSE','REOPEN']);
const clean=(v,max=200)=>String(v||'').trim().slice(0,max);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const normalizeRow=r=>({...r,status:clean(r?.status,40).toUpperCase(),lead_source:clean(r?.lead_source,40).toUpperCase(),customer_name:clean(r?.customer_name,160),mobile_whatsapp:clean(r?.mobile_whatsapp,20).replace(/\D/g,'').slice(-10),pin_code:clean(r?.pin_code,10).replace(/\D/g,'').slice(0,6),item_code:clean(r?.item_code,120),product_name:clean(r?.product_name,240),shop_name:clean(r?.shop_name,180),owner_note:clean(r?.owner_note,1000)});
export async function loadAdminPublicReferrals({status='',search='',limit=100}={}){const s=clean(status,40).toUpperCase();if(!statuses.has(s))throw new Error('INVALID REFERRAL STATUS');const{data,error}=await db().rpc('admin_public_referral_crm',{p_status:s||null,p_search:clean(search,160)||null,p_limit:Math.max(1,Math.min(Number(limit)||100,500))});if(error)throw error;return(Array.isArray(data)?data:[]).map(normalizeRow)}
export async function loadAdminPublicReferralSummary(){const{data,error}=await db().rpc('admin_public_referral_summary');if(error)throw error;const r=Array.isArray(data)?data[0]:data;return{total:Number(r?.total)||0,awaiting_followup:Number(r?.awaiting_followup)||0,contacted:Number(r?.contacted)||0,converted:Number(r?.converted)||0,closed:Number(r?.closed)||0,conversion_rate:Number(r?.conversion_rate)||0}}
export async function updateAdminPublicReferral(referralId,action,note=''){const id=clean(referralId,40),a=clean(action,40).toUpperCase();if(!UUID.test(id))throw new Error('INVALID REFERRAL ID');if(!actions.has(a))throw new Error('INVALID REFERRAL ACTION');const{data,error}=await db().rpc('admin_update_public_referral',{p_referral_id:id,p_action:a,p_note:clean(note,1000)||null});if(error)throw error;const r=Array.isArray(data)?data[0]||null:data||null;return r?normalizeRow(r):null}
