import{dealerItemRate,submitDealerPurchaseOrder}from'./dealerProcurement';
import{confirmDealerSalesOrder,requestDealerAdditionalOrder,loadDealerOrderHistory}from'./dealerOrders';
import{loadDealerWorkspace}from'./dealerWorkspace';
import{loadDealerMachineSpares}from'./dealerMachineSpares';

export{dealerItemRate,submitDealerPurchaseOrder,confirmDealerSalesOrder,requestDealerAdditionalOrder,loadDealerOrderHistory,loadDealerWorkspace,loadDealerMachineSpares};
