import{requireBackend}from'./supabase';import{assertDealerSession}from'./dealerSession';
const proof=async()=>{const s=await assertDealerSession();if(!s?.deviceId||!s?.token)throw new Error('ACTIVE DEALER DEVICE SESSION REQUIRED');return s};const rpc=async(name,args={})=>{const s=await proof();const{data,error}=await requireBackend().rpc(name,{p_device_id:s.deviceId,p_session_token:s.token,...args});if(error)throw error;await assertDealerSession();return data};const clean=(v,n)=>String(v||'').trim().slice(0,n);
export const dealerServiceBook={async summary(){const data=await rpc('dealer_service_jobs_summary',{});const rows=Array.isArray(data)?data:data?[data]:[];return rows[0]||{in_shop:0,repairing:0,ready:0,delivered:0,cancelled:0,total:0}},async complaints(){const data=await rpc('dealer_service_complaints_read',{});return Array.isArray(data)?data:[]},async search(query,limit=100){const q=clean(query,120);if(!q)throw new Error('SEARCH QUERY REQUIRED');const data=await rpc('dealer_service_jobs_search',{p_query:q,p_limit:Math.min(Math.max(Number(limit)||100,1),300)});return Array.isArray(data)?data:[]},async jobs(status=null,limit=100){const data=await rpc('dealer_service_jobs_read',{p_status:status,p_limit:Math.min(Math.max(Number(limit)||100,1),300)});return Array.isArray(data)?data:[]},async create(x){return rpc('dealer_service_job_create',{p_customer_name:clean(x.customerName,120),p_mobile:clean(x.mobile,20),p_whatsapp:clean(x.whatsapp,20),p_address:clean(x.address,300),p_machine_photo_url:clean(x.machinePhotoUrl,1000),p_machine_catalog_item_id:x.machineCatalogItemId||null,p_machine_brand:clean(x.machineBrand,100),p_machine_type:clean(x.machineType,100),p_machine_model:clean(x.machineModel,120),p_serial_no:clean(x.serialNo,120),p_complaint_code:clean(x.complaintCode,100),p_complaint_note:clean(x.complaintNote,1000)})},async addPart(jobId,itemId,qty,sellingRate){return rpc('dealer_service_job_add_part',{p_job_id:jobId,p_item_id:itemId,p_qty:Number(qty),p_selling_rate:Number(sellingRate)})},async parts(jobId){const data=await rpc('dealer_service_job_parts_read',{p_job_id:jobId});return Array.isArray(data)?data:[]},async removePart(jobId,partId){return rpc('dealer_service_job_remove_part',{p_job_id:jobId,p_part_id:partId})},async bill(jobId){const data=await rpc('dealer_service_job_bill_read',{p_job_id:jobId});const rows=Array.isArray(data)?data:data?[data]:[];if(rows.length>1)throw new Error('SERVICE BILL RESPONSE AMBIGUOUS');return rows[0]||null},async setStatus(jobId,status,repairCharge=0){return rpc('dealer_service_job_set_status',{p_job_id:jobId,p_status:status,p_repair_charge:Number(repairCharge)||0})}};

export async function uploadDealerServiceBookPhoto(file){if(!file)throw new Error('MACHINE PHOTO REQUIRED');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('USE JPG, PNG OR WEBP PHOTO');if(file.size<1||file.size>8*1024*1024)throw new Error('PHOTO MUST BE 8 MB OR SMALLER');const s=await proof(),form=new FormData();form.append('device_id',s.deviceId);form.append('session_token',s.token);form.append('file',file);const{data,error}=await requireBackend().functions.invoke('dealer-service-book-media-upload',{body:form});if(error||!data?.ok||!data?.storage_path)throw error||new Error('SERVICE BOOK PHOTO UPLOAD FAILED');await assertDealerSession();return data.storage_path}

export async function deleteDealerServiceBookOrphanPhoto(storagePath){if(!storagePath)return false;const s=await proof();const{data,error}=await requireBackend().functions.invoke('dealer-service-book-media-delete',{body:{device_id:s.deviceId,session_token:s.token,storage_path:storagePath}});if(error||!data?.ok)throw error||new Error('SERVICE BOOK PHOTO CLEANUP FAILED');await assertDealerSession();return true}

export async function readDealerServiceBookPhoto(jobId){const s=await proof();const{data,error}=await requireBackend().functions.invoke('dealer-service-book-media-read',{body:{device_id:s.deviceId,session_token:s.token,job_id:jobId}});if(error||!data?.ok||!data?.url)throw error||new Error('SERVICE BOOK PHOTO NOT AVAILABLE');await assertDealerSession();return data.url}
export function serviceBookBill(parts=[],repairCharge=0){const partsTotal=(Array.isArray(parts)?parts:[]).reduce((n,x)=>n+(Number(x?.line_total)||0),0),labour=Math.max(0,Number(repairCharge)||0);return{partsTotal,labour,total:Math.round((partsTotal+labour)*100)/100}}
export function serviceBookWhatsAppText(job,parts=[],repairCharge=0,serverBill=null){const local=serviceBookBill(parts,repairCharge),closed=['ready','delivered','cancelled'].includes(String(job?.status||'').toLowerCase())&&serverBill,bill=closed?{partsTotal:Number(serverBill.parts_total)||0,labour:Number(serverBill.repair_charge)||0,total:Number(serverBill.grand_total)||0}:local,status=String(job?.status||'').toUpperCase(),ready=status==='READY'?'Your machine is ready for collection.':status==='DELIVERED'?'Your machine delivery is recorded as completed.':'Repair status update.';const lines=(Array.isArray(parts)?parts:[]).map(x=>`${x.item_name||x.item_code||'PART'} × ${x.qty} = ₹${Number(x.line_total||0).toFixed(2)}`).join('\n');return `TORVO DEALER SERVICE BOOK\nJob #${job?.token_no||''}\nCustomer: ${job?.customer_name||''}\nMachine: ${job?.machine_brand||''} ${job?.machine_model||''}\nComplaint: ${job?.complaint_code||''}\n${ready}\n${lines?`Parts Used:\n${lines}\n`:''}Parts Total: ₹${bill.partsTotal.toFixed(2)}\nRepair/Labour: ₹${bill.labour.toFixed(2)}\nTotal: ₹${bill.total.toFixed(2)}\nThis is an operational repair-service message.`}

export function serviceBookReceiptText(job,parts=[],repairCharge=0,serverBill=null){const local=serviceBookBill(parts,repairCharge),closed=['ready','delivered','cancelled'].includes(String(job?.status||'').toLowerCase())&&serverBill,bill=closed?{partsTotal:Number(serverBill.parts_total)||0,labour:Number(serverBill.repair_charge)||0,total:Number(serverBill.grand_total)||0}:local;const lines=(Array.isArray(parts)?parts:[]).map(x=>`${x.item_name||x.item_code||'PART'} × ${x.qty} = ₹${Number(x.line_total||0).toFixed(2)}`).join('\n');return `REPAIR SERVICE SUMMARY\nJob #${job?.token_no||''}\nCustomer: ${job?.customer_name||''}\nMobile: ${job?.mobile||''}\nMachine: ${job?.machine_brand||''} ${job?.machine_model||''}\nSerial/ID: ${job?.serial_no||''}\nComplaint: ${job?.complaint_code||''}\nStatus: ${String(job?.status||'').toUpperCase()}\n${lines?`Parts Used:\n${lines}\n`:''}Parts Total: ₹${bill.partsTotal.toFixed(2)}\nRepair/Labour: ₹${bill.labour.toFixed(2)}\nTotal: ₹${bill.total.toFixed(2)}\n\nService record only — not a GST tax invoice.`}

export function serviceBookWhatsAppNumber(value){const d=String(value||'').replace(/\D/g,'');if(/^\d{10}$/.test(d))return'91'+d;if(/^91\d{10}$/.test(d))return d;return''}
