import{requireBackend}from'./supabase';import{assertDealerSession}from'./dealerSession';
const id=(v,label)=>{const s=String(v||'').trim();if(!s)throw new Error(`${label} IS REQUIRED`);if(s.length>128)throw new Error(`${label} IS INVALID`);return s};
const qty=v=>{const n=Number(v);if(!Number.isInteger(n)||n<1||n>9999)throw new Error('QUANTITY MUST BE INTEGER 1 TO 9999');return n};
const text=(v,label,max=500)=>{const s=String(v||'').trim();if(!s)throw new Error(`${label} IS REQUIRED`);if(s.length>max)throw new Error(`${label} IS TOO LONG`);return s};
const resultId=(v,label)=>{if(typeof v==='string'||typeof v==='number')return id(v,label);if(v&&typeof v==='object')return id(v.order_id||v.sales_order_id||v.id,label);throw new Error(`${label} WAS NOT CONFIRMED`)};
const rpc=async(name,args={})=>{const proof=await assertDealerSession();if(!proof?.deviceId||!proof?.token)throw new Error('ACTIVE DEALER DEVICE SESSION REQUIRED');const{data,error}=await requireBackend().rpc(name,{...args,p_device_id:proof.deviceId,p_session_token:proof.token});if(error)throw error;await assertDealerSession();return data};
export const confirmDealerSalesOrder=async(orderId,revision)=>{const order=id(orderId,'SALES ORDER'),rev=Number(revision);if(!Number.isInteger(rev)||rev<1)throw new Error('VALID SALES ORDER REVISION IS REQUIRED');const raw=await rpc('dealer_confirm_sales_order_revision',{p_sales_order:order,p_revision:rev});if(raw===false||raw==null)throw new Error('SALES ORDER CONFIRMATION WAS NOT ACCEPTED');return{order_id:order,revision_no:rev,status:'DEALER_OK'}};
export const requestDealerAdditionalOrder=async(orderId,lines,reason)=>{const parent=id(orderId,'ORIGINAL SALES ORDER');if(!Array.isArray(lines)||!lines.length)throw new Error('ADDITIONAL PURCHASE ORDER REQUIRES AT LEAST ONE ITEM');if(lines.length>500)throw new Error('ADDITIONAL PURCHASE ORDER HAS TOO MANY ITEMS');const clean=lines.map(x=>({item_id:id(x?.item_id,'ITEM'),qty:qty(x?.qty)}));if(new Set(clean.map(x=>x.item_id)).size!==clean.length)throw new Error('DUPLICATE ITEM IS NOT ALLOWED');const raw=await rpc('request_additional_purchase_order',{p_original_sales_order:parent,p_lines:clean,p_reason:text(reason,'REASON')});return{order_id:resultId(raw,'ADDITIONAL PURCHASE ORDER'),parent_order_id:parent,status:'PENDING_APPROVAL'}};
export const loadDealerOrderHistory=async()=>{const data=await rpc('get_dealer_order_history_30d');if(data==null)return[];if(!Array.isArray(data))throw new Error('INVALID DEALER ORDER HISTORY RESPONSE');const seen=new Set();return data.filter(x=>{if(!x||typeof x!=='object')return false;const key=String(x.id||x.order_id||'').trim(),type=String(x.doc_type||'').trim().toLowerCase();if(!key||!['sales_order','estimate'].includes(type))return false;const unique=`${type}:${key}`;if(seen.has(unique))return false;seen.add(unique);return true})};
