import{dealerItemRate,submitDealerPurchaseOrder}from'./dealerProcurement';
import{confirmDealerSalesOrder,loadDealerOrderHistory}from'./dealerOrders';
import{loadDealerMachineSpares}from'./dealerMachineSpares';
import{reviseDealerPurchaseOrder,requestDealerSalesOrderChange,loadApprovedAdditionalRequests,createApprovedAdditionalOrder}from'./dealerBusiness';

export const secureDealerLegacy={
 dealerMachineSpares:loadDealerMachineSpares,
 dealerItemRate,
 submitPurchaseOrder:submitDealerPurchaseOrder,
 dealerConfirmSalesOrder:confirmDealerSalesOrder,
 dealerReviseSalesOrder:reviseDealerPurchaseOrder,
 dealerRequestSalesOrderChange:requestDealerSalesOrderChange,
 dealerApprovedAddOnRequests:loadApprovedAdditionalRequests,
 dealerCreateAddOnOrder:createApprovedAdditionalOrder,
 dealerOrderHistory:loadDealerOrderHistory
};
