import{requireBackend}from'./supabase';import{assertDealerSession}from'./dealerSession';
const id=(v,label='ID')=>{const s=String(v||'').trim();if(!s||s.length>128)throw new Error(`${label} IS INVALID`);return s};const list=(v,label)=>{if(v==null)return[];if(!Array.isArray(v))throw new Error(`INVALID ${label} RESPONSE`);return v.filter(x=>x&&typeof x==='object')};
const rpc=async(name,args={})=>{const c=requireBackend(),{data,error}=await c.rpc(name,args);if(error)throw error;return data};
const dealerRpc=async(name,args={})=>{const proof=await assertDealerSession();if(!proof?.deviceId||!proof?.token)throw new Error('ACTIVE DEALER DEVICE SESSION REQUIRED');const data=await rpc(name,{p_device_id:proof.deviceId,p_session_token:proof.token,...args});await assertDealerSession();return data};
export async function loadRewardBalance(){const n=Number(await dealerRpc('dealer_reward_balance'));if(!Number.isFinite(n)||n<0)throw new Error('INVALID REWARD BALANCE RESPONSE');return n}
export async function loadRewardOptions(){return list(await dealerRpc('dealer_reward_options'),'REWARD OPTIONS')}
export async function loadRewardProgress(){const data=await dealerRpc('dealer_reward_progress');if(data==null)return null;if(Array.isArray(data))return data[0]&&typeof data[0]==='object'?data[0]:null;if(typeof data!=='object')throw new Error('INVALID REWARD PROGRESS RESPONSE');return data}
export async function loadRewardClaims(){return list(await dealerRpc('dealer_reward_claim_history'),'REWARD CLAIM HISTORY')}
export async function claimReward(rewardId){const reward=id(rewardId,'REWARD');const raw=await dealerRpc('dealer_claim_reward',{p_reward:reward});const claim=typeof raw==='object'&&raw?raw.claim_id||raw.id:raw;return{claim_id:id(claim,'REWARD CLAIM'),status:'SUBMITTED'}}
export async function loadTargetRewardAdminData(){const d=await rpc('admin_dealer_target_reward_data');return d||{scheme_year:null,target_types:[],target_slabs:[],assignments:[],reward_options:[],claims:[],dealers:[]}}
export async function issueRewardVoucher(claimId,provider,code){return rpc('admin_issue_reward_voucher',{p_claim:id(claimId,'CLAIM'),p_provider:String(provider||'').trim().toUpperCase(),p_code:String(code||'').trim()})}
export async function approveRewardClaim(claimId){return rpc('admin_approve_reward_claim',{p_claim:id(claimId,'CLAIM')})}
export async function cancelRewardClaim(claimId,reason){return rpc('admin_cancel_reward_claim',{p_claim:id(claimId,'CLAIM'),p_reason:String(reason||'').trim()})}
export async function settleDealerTarget(dealerId,schemeYear){const data=await rpc('admin_settle_dealer_target',{p_dealer:id(dealerId,'DEALER'),p_scheme_year:Number(schemeYear)});return Array.isArray(data)?data[0]||null:data||null}
export async function saveTargetType(name,startMonth=4){return rpc('admin_save_dealer_target_type',{p_name:String(name||'').trim(),p_start_month:Number(startMonth)||4})}
export async function saveTargetSlab(targetTypeId,targetValue,points){return rpc('admin_save_dealer_target_slab',{p_target_type:id(targetTypeId,'TARGET TYPE'),p_target_value:Number(targetValue),p_points:Number(points)})}
export async function assignDealerTarget(dealerId,targetTypeId,schemeYear){return rpc('admin_assign_dealer_target',{p_dealer:id(dealerId,'DEALER'),p_target_type:id(targetTypeId,'TARGET TYPE'),p_scheme_year:Number(schemeYear)})}
export async function saveRewardOption(name,pointsRequired,giftValue=0,redemptionType='gift'){return rpc('admin_save_dealer_reward_option',{p_name:String(name||'').trim(),p_points:Number(pointsRequired),p_gift_value:Number(giftValue)||0,p_redemption_type:String(redemptionType||'gift').toLowerCase()})}
