import{requireBackend}from'./supabase';
const text=(v,max,label,min=0)=>{const x=String(v??'').trim();if(x.length<min||x.length>max)throw new Error(`${label} MUST BE ${min?`${min} TO `:''}${max} CHARACTERS`);return x};const id=v=>String(v??'').trim();const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const validId=(v,label)=>{const x=id(v);if(!uuid.test(x))throw new Error(`VALID ${label} REQUIRED`);return x};const validPublicTarget=v=>{const x=String(v??'').trim().toLowerCase();if(!['website','dealer_app'].includes(x))throw new Error('INVALID PROMOTION TARGET');return x};const list=(data,label,keyOf)=>{if(data==null)return[];if(!Array.isArray(data))throw new Error(`INVALID ${label} RESPONSE`);const seen=new Set();return data.filter(x=>{if(!x||typeof x!=='object')return false;const key=id(keyOf(x));if(!key||seen.has(key))return false;seen.add(key);return true})};
export async function loadProductPromotions(target='website'){const client=requireBackend(),t=validPublicTarget(target),{data,error}=await client.rpc('public_active_product_promotions',{p_target:t});if(error)throw error;return list(data,'PRODUCT PROMOTION',x=>x.id)}
export async function loadPopularProducts(limit=12){const client=requireBackend(),n=Math.min(30,Math.max(1,Math.trunc(Number(limit)||12))),{data,error}=await client.rpc('public_popular_products',{p_limit:n});if(error)throw error;return list(data,'POPULAR PRODUCT',x=>x.id||x.product_id).slice(0,n)}
export async function saveProductPromotion(input={}){const client=requireBackend();const productId=validId(input.productId,'PRODUCT'),promotionId=id(input.id)?validId(input.id,'PROMOTION'):null,title=text(input.title,120,'PROMOTION TITLE',2),caption=text(input.caption,500,'PROMOTION CAPTION'),imageUrl=text(input.imageUrl,1000,'PROMOTION IMAGE URL')||null,reason=text(input.reason,500,'CHANGE REASON',3),target=String(input.target||'both').trim().toLowerCase(),sortOrder=Number(input.sortOrder??100),startsAt=input.startsAt||new Date().toISOString(),endsAt=input.endsAt||null;if(!['website','dealer_app','both'].includes(target))throw new Error('INVALID PROMOTION TARGET');if(!Number.isInteger(sortOrder)||sortOrder<0||sortOrder>100000)throw new Error('INVALID PROMOTION SORT ORDER');if(!Number.isFinite(Date.parse(startsAt)))throw new Error('VALID PROMOTION START TIME REQUIRED');if(endsAt&&(!Number.isFinite(Date.parse(endsAt))||Date.parse(endsAt)<=Date.parse(startsAt)))throw new Error('END TIME MUST BE AFTER START TIME');const{data,error}=await client.rpc('admin_save_product_promotion',{p_id:promotionId,p_product_id:productId,p_title:title,p_caption:caption,p_image_url:imageUrl,p_target:target,p_active:input.active!==false,p_starts_at:startsAt,p_ends_at:endsAt,p_sort_order:sortOrder,p_reason:reason});if(error)throw error;if(!data)throw new Error('PROMOTION SAVE FAILED');return data}
export async function setProductFeatured(productId,featured=true,rank=null,reason=''){const client=requireBackend();const product=validId(productId,'PRODUCT'),why=text(reason,500,'CHANGE REASON',3),n=rank==null?null:Number(rank);if(n!=null&&(!Number.isInteger(n)||n<0||n>100000))throw new Error('INVALID FEATURED RANK');const{data,error}=await client.rpc('admin_set_product_featured',{p_product_id:product,p_featured:!!featured,p_rank:n,p_reason:why});if(error)throw error;if(data!==true)throw new Error('FEATURED PRODUCT UPDATE FAILED');return true}
const sessionKey=()=>{const k='torvo_promo_session';let v='';try{v=sessionStorage.getItem(k)||'';if(!v){v=(globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^a-zA-Z0-9-]/g,'').slice(0,96);sessionStorage.setItem(k,v)}}catch{v=`${Date.now()}-${Math.random()}`}return v};
export async function recordPromotionEvent(promotionId,eventType,target='website',sourceRef=null){if(!promotionId)return false;const client=requireBackend(),promotion=validId(promotionId,'PROMOTION'),event=String(eventType||'').trim().toLowerCase(),t=validPublicTarget(target),source=sourceRef==null?null:text(sourceRef,120,'SOURCE REFERENCE');if(!['view','click','enquiry','dealer_order'].includes(event))throw new Error('INVALID PROMOTION EVENT');if(event==='dealer_order'&&t!=='dealer_app')throw new Error('DEALER ORDER REQUIRES DEALER APP');const{data,error}=await client.rpc('record_product_promotion_event',{p_promotion_id:promotion,p_event_type:event,p_target:t,p_session_key:sessionKey(),p_source_ref:source||null});if(error)throw error;return !!data}
export async function loadPromotionAnalytics(days=30){const client=requireBackend(),n=Math.min(365,Math.max(1,Math.trunc(Number(days)||30))),{data,error}=await client.rpc('admin_product_promotion_analytics',{p_days:n});if(error)throw error;return list(data,'PROMOTION ANALYTICS',x=>`${x.promotion_id||x.id}:${x.event_type||x.date||''}`)}
