import{requireBackend}from'./supabase';
import{detectLeadSource,normalizeLeadSource}from'./publicLeadSource';
const db=()=>requireBackend(),source=v=>normalizeLeadSource(v)||detectLeadSource();
export async function searchProducts(search){const{data,error}=await db().rpc('public_customer_catalog',{p_search:String(search||'').trim()||null,p_limit:20});if(error)throw error;return data||[]}
export async function loadProductShowcase(limit=60){const{data,error}=await db().rpc('public_product_showcase',{p_limit:Math.max(1,Math.min(Number(limit)||60,120))});if(error)throw error;return data||[]}
export async function findDealers(pin,repairOnly=false){const{data,error}=await db().rpc('public_find_torvo_dealers_expanded',{p_pin_code:String(pin||'').trim(),p_repair_only:repairOnly,p_limit:12});if(error)throw error;return data||[]}
export async function loadDealerProfile(dealerId){if(!dealerId)return null;const{data,error}=await db().rpc('public_dealer_profile',{p_dealer_id:dealerId});if(error)throw error;return Array.isArray(data)?data[0]||null:data||null}
export async function createProductEnquiry({name,mobile,state,district,city,pin,productIds,marketing=false,leadSource}){const cleanMobile=String(mobile||'').replace(/\D/g,'').slice(-10);const{data,error}=await db().rpc('public_create_product_enquiry',{p_customer_name:name,p_mobile_whatsapp:cleanMobile,p_state:state||null,p_district:district||null,p_city:city||null,p_pin_code:String(pin||'').trim(),p_product_ids:[...new Set((productIds||[]).filter(Boolean))],p_marketing_opt_in:!!marketing,p_lead_source:source(leadSource)});if(error)throw error;return Array.isArray(data)?data[0]:data}
export async function trackDealerReferralEvent({enquiryId,dealerId,eventType,productId=null}){if(!dealerId||!eventType)return false;const{data,error}=await db().rpc('public_track_dealer_referral_event',{p_enquiry_id:enquiryId||null,p_dealer_id:dealerId,p_event_type:String(eventType).toUpperCase(),p_product_id:productId||null});if(error)throw error;return data===true}
export async function createProductRequirement({name,mobile,state,district,city,pin,productType,brand,machineModel,requiredItem,itemOemNo,description,quantity=1,photoUrl=null,marketing=false,leadSource}){const{data,error}=await db().rpc('public_create_product_requirement',{p_customer_name:name,p_mobile_whatsapp:String(mobile||'').replace(/\D/g,'').slice(-10),p_state:state||null,p_district:district||null,p_city:city||null,p_pin_code:String(pin||'').trim(),p_product_type:String(productType||'').toUpperCase(),p_brand:brand||null,p_machine_model:machineModel||null,p_required_item:requiredItem,p_item_oem_no:itemOemNo||null,p_description:description||null,p_quantity:Math.max(1,Number(quantity)||1),p_photo_url:photoUrl||null,p_marketing_opt_in:!!marketing,p_lead_source:source(leadSource)});if(error)throw error;return data}
export async function createCustomerComplaint({name,mobile,dealerId=null,enquiryId=null,category,description,attachmentUrl=null}){const{data,error}=await db().rpc('public_create_customer_complaint',{p_customer_name:name,p_mobile_whatsapp:String(mobile||'').replace(/\D/g,'').slice(-10),p_dealer_id:dealerId||null,p_enquiry_id:enquiryId||null,p_category:String(category||'').toUpperCase(),p_description:description,p_attachment_url:attachmentUrl||null});if(error)throw error;return data}
export async function createReferral({name,mobile,pin,productId,dealerId=null,marketing=false,leadSource}){const{data,error}=await db().rpc('public_create_customer_referral',{p_full_name:name,p_mobile:mobile,p_pin_code:pin,p_product_id:productId,p_dealer_id:dealerId,p_marketing_opt_in:marketing,p_lead_source:source(leadSource)});if(error)throw error;return Array.isArray(data)?data[0]:data}
export async function createRepair({name,mobile,pin,brand,model,problem,marketing=false,leadSource}){const{data,error}=await db().rpc('public_create_repair_request',{p_full_name:name,p_mobile:mobile,p_pin_code:pin,p_brand:brand||null,p_model_number:model||null,p_problem_description:problem,p_marketing_opt_in:marketing,p_lead_source:source(leadSource)});if(error)throw error;return Array.isArray(data)?data[0]:data}
export async function registerDealer({shopName,contactPerson,mobile,pin,businessType}){const{data,error}=await db().rpc('public_register_dealer',{p_shop_name:shopName,p_contact_person:contactPerson,p_mobile:mobile,p_pin_code:pin,p_business_type:businessType||null});if(error)throw error;return Array.isArray(data)?data[0]:data}
