import{requireBackend}from'./supabase';
const db=()=>requireBackend();const fail=e=>{if(e)throw e};
export const data={
 async list(table,{select='*',order='created_at',ascending=false}={}){const{data,error}=await db().from(table).select(select).order(order,{ascending});fail(error);return data??[]},async dashboardMetrics(){const{data,error}=await db().rpc('get_dashboard_metrics');fail(error);return data??{}},async reportSummary(){const{data,error}=await db().rpc('get_report_summary');fail(error);return data??{}},async reportDetail(report,from=null,to=null){const{data,error}=await db().rpc('get_report_detail',{p_report:report,p_from:from,p_to:to});fail(error);return Array.isArray(data)?data:[]},async profitSummary(from=null,to=null){const{data,error}=await db().rpc('get_profit_summary',{p_from:from,p_to:to});fail(error);return data??{}},async dealers(){return this.list('dealers')},async catalog(type){const{data,error}=await db().from('catalog_items').select('*').eq('item_type',type).order('name');fail(error);return data??[]},async documents(type){const{data,error}=await db().from('sales_documents').select('*,dealers(shop_name,dealer_code),sales_document_lines(*)').eq('doc_type',type).order('created_at',{ascending:false});fail(error);return data??[]},async inventory(){const{data,error}=await db().from('inventory').select('*,catalog_items(item_code,name,item_type,brand,model)').order('updated_at',{ascending:false});fail(error);return data??[]},async inventoryMovements(){const{data,error}=await db().from('inventory_movements').select('*,catalog_items(item_code,name,brand,model)').order('created_at',{ascending:false}).limit(100);fail(error);return data??[]},
 async dealerItemRate(itemId,qty){const{data,error}=await db().rpc('dealer_item_rate',{p_item:itemId,p_qty:Number(qty)});fail(error);return Array.isArray(data)?data[0]??null:data??null},async submitPurchaseOrder(lines){const clean=(lines||[]).map(x=>({item_id:x.item_id,qty:Number(x.qty)})).filter(x=>x.item_id&&x.qty>0);if(!clean.length)throw new Error('Purchase Order requires at least one item');const{data,error}=await db().rpc('submit_purchase_order',{p_lines:clean});fail(error);return data},
 async deliverySettings(){const{data,error}=await db().from('delivery_settings').select('*').eq('id',true).single();fail(error);return data},async setDeliverySettings(enabled,threshold,reason){const{error}=await db().rpc('set_delivery_settings',{p_enabled:!!enabled,p_threshold:Number(threshold),p_reason:String(reason||'').trim()});fail(error)},
 async approveDealer(dealerId,dealerCode,rateGroup){const{error}=await db().rpc('approve_dealer',{p_dealer:dealerId,p_dealer_code:dealerCode,p_rate_group:rateGroup});fail(error)},async setDealerRateGroup(dealerId,rateGroup,reason='RATE GROUP UPDATED'){if(!['A','B','C'].includes(rateGroup))throw new Error('Invalid dealer rate group');const{error}=await db().rpc('set_dealer_rate_group',{p_dealer:dealerId,p_rate_group:rateGroup,p_reason:reason});fail(error)},
 async recordPayment(estimateId,status,amount,key){if(!key||!String(key).trim())throw new Error('Internal payment request key is required');const{data,error}=await db().rpc('record_payment',{p_estimate:estimateId,p_status:status,p_amount:amount,p_request_key:String(key).trim()});fail(error);return data},async accountingBalances(status=null){let q=db().from('accounting_balances').select('*,dealers(shop_name,dealer_code),sales_documents!estimate_id(final_payable,created_at)').order('created_at',{ascending:false});if(status)q=q.eq('status',status);const{data,error}=await q;fail(error);return data??[]},async createAccountingBalance(estimateId,amount,remarks=null){const{data,error}=await db().rpc('create_accounting_balance',{p_estimate:estimateId,p_amount:amount,p_remarks:remarks});fail(error);return data},async markAccountingBalanceEntered(balanceId,entryNo){if(!String(entryNo||'').trim())throw new Error('Accounting entry number required');const{error}=await db().rpc('mark_accounting_balance_entered',{p_balance:balanceId,p_entry_no:String(entryNo).trim().toUpperCase()});fail(error)},
 async dispatches(){const{data,error}=await db().from('dispatches').select('id,estimate_id,status,tracking_code,delivered_at,stock_deducted_at').order('status');fail(error);return data??[]},async storeQueue(){const{data,error}=await db().rpc('get_store_fulfilment_queue');fail(error);return data??[]},async advanceDispatch(estimateId,status,trackingCode=null){const{error}=await db().rpc('advance_dispatch',{p_estimate:estimateId,p_status:status,p_tracking_code:trackingCode});fail(error)},async deliver(estimateId){const{error}=await db().rpc('deliver_estimate',{p_estimate:estimateId});fail(error)},
 async saveCatalog(item){const{data,error}=await db().rpc('upsert_catalog_item',{p_item:item.id||null,p_type:item.item_type,p_code:item.item_code,p_name:item.name,p_oem_code:item.oem_code||null,p_brand:item.brand||null,p_category:item.category||null,p_model:item.model||null,p_image_url:item.image_url||null,p_gst_mode:item.gst_mode||null,p_active:item.active!==false});fail(error);return data},async setRate(itemId,rateGroup,minQty,rate){const{data,error}=await db().rpc('set_item_rate',{p_item:itemId,p_rate_group:rateGroup,p_min_qty:minQty,p_rate:rate});fail(error);return data},
 async purchases(){const{data,error}=await db().from('purchase_headers').select('*,suppliers(*),purchase_lines(*,catalog_items(item_code,name,brand,model))').order('invoice_date',{ascending:false});fail(error);return data??[]},async purchaseRateHistory(itemId){const{data,error}=await db().from('purchase_lines').select('qty,purchase_rate,line_amount,purchase_headers(invoice_no,invoice_date,suppliers(supplier_name,company_name))').eq('item_id',itemId).order('purchase_headers(invoice_date)',{ascending:false});fail(error);return data??[]},async suitableMappings(){const{data,error}=await db().from('suitable_mappings').select('*,catalog_items!spare_part_id(item_code,name,brand,model),suitable_selling_codes(*)').order('updated_at',{ascending:false});fail(error);return data??[]},async missingPartRequests(){const{data,error}=await db().from('missing_part_requests').select('*,dealers(shop_name,dealer_code)').order('created_at',{ascending:false});fail(error);return data??[]},
 async notifications(){return this.list('notifications')},async markNotificationRead(id){const{error}=await db().rpc('mark_notification_read',{p_notification:id});fail(error)}
};
