import{requireBackend}from'./supabase';
const digits=v=>String(v||'').replace(/\D/g,'').slice(-10);const STAFF=new Set(['owner','admin','accountant','salesman','store_keeper']);const SESSION_KEY='torvo_staff_session_id';export const DEALER_SESSION_KEY='torvo_dealer_session_token';
const codeDigits=(v,n)=>String(v||'').replace(/\D/g,'').slice(0,n);const assertDevice=v=>{const x=String(v||'').trim();if(!x||x.length>180)throw new Error('SECURE DEVICE ID REQUIRED.');return x};
export const normalizeStaffUsername=v=>String(v||'').trim().toUpperCase();
const staffUsername=v=>{const x=normalizeStaffUsername(v);if(!/^[A-Z]{2,8}@[0-9]{2,6}$/.test(x))throw new Error('ENTER A VALID STAFF USER ID.');return x};
export function normalizeDealerMobile(v){const m=digits(v);if(m.length!==10)throw new Error('ENTER A VALID 10-DIGIT MOBILE NUMBER.');return m}
export function validateLoginIdentity(mode,value){if(mode==='dealer_mobile')return normalizeDealerMobile(value);if(mode==='staff_id')return staffUsername(value);throw new Error('SELECT MOBILE OR USER ID LOGIN.')}
export async function identifyLoginRole(mobile){const client=requireBackend();const m=normalizeDealerMobile(mobile);const{data,error}=await client.rpc('public_login_route',{p_mobile:m});if(error)throw error;return data}
export async function requestStaffOtp(mobile){const client=requireBackend();const m=normalizeDealerMobile(mobile);const{data,error}=await client.functions.invoke('staff-whatsapp-otp-request',{body:{mobile:m}});if(error)throw error;return data}
function keep(result){if(result?.session_id)localStorage.setItem(SESSION_KEY,result.session_id);return result}
export async function loginStaffWithAdminPassword(username,password,deviceType='mobile_app'){const client=requireBackend(),u=staffUsername(username),p=String(password||''),d=deviceId(),t=String(deviceType||'').trim().toLowerCase();if(p.length<10||p.length>80)throw new Error('ENTER THE ADMIN-ISSUED ONE-TIME PASSWORD.');if(!['mobile_app','desktop'].includes(t))throw new Error('INVALID DEVICE TYPE.');const{data,error}=await client.functions.invoke('staff-one-time-login',{body:{username:u,password:p,device_id:d,device_type:t}});if(error)throw error;if(!data?.ok||!data?.session_id)throw new Error(data?.message||'STAFF LOGIN COULD NOT BE STARTED.');return keep(data)}
export async function verifyStaffOtp(mobile,otp,deviceId){const client=requireBackend(),m=normalizeDealerMobile(mobile),o=codeDigits(otp,6);if(o.length!==6)throw new Error('ENTER THE 6-DIGIT WHATSAPP OTP.');const{data,error}=await client.functions.invoke('staff-whatsapp-otp-verify',{body:{mobile:m,otp:o,device_id:assertDevice(deviceId)}});if(error)throw error;return keep(data)}
export async function verifyEmergencyCode(mobile,code,deviceId){const client=requireBackend(),m=normalizeDealerMobile(mobile),c=codeDigits(code,10);if(c.length<6)throw new Error('ENTER THE 6 TO 10-DIGIT ADMIN CODE.');const{data,error}=await client.functions.invoke('staff-emergency-login',{body:{mobile:m,code:c,device_id:assertDevice(deviceId)}});if(error)throw error;return keep(data)}
export async function verifyDealerPin(mobile,pin,deviceId){const client=requireBackend();const m=normalizeDealerMobile(mobile),p=codeDigits(pin,4),d=assertDevice(deviceId);if(p.length!==4)throw new Error('ENTER A VALID 4-DIGIT PIN.');clearDealerSession();const{data,error}=await client.functions.invoke('dealer-pin-login',{body:{mobile:m,pin:p,device_id:d}});if(error)throw error;if(!data?.ok||!data?.dealer_session_token)throw new Error(data?.message||'SECURE DEALER SESSION COULD NOT BE STARTED.');localStorage.setItem(DEALER_SESSION_KEY,data.dealer_session_token);return data}
export async function requestDealerPinRecovery(mobile){const client=requireBackend();const m=normalizeDealerMobile(mobile);const{data,error}=await client.functions.invoke('dealer-pin-recovery-request',{body:{mobile:m}});if(error)throw error;return data}
export function dealerSessionToken(){return localStorage.getItem(DEALER_SESSION_KEY)||''}export function clearDealerSession(){localStorage.removeItem(DEALER_SESSION_KEY)}export function clearStaffSession(){localStorage.removeItem(SESSION_KEY)}
export function isStaffRole(role){return STAFF.has(role)}
export function deviceId(){let id=localStorage.getItem('torvo_device_id');if(!id){if(!globalThis.crypto?.randomUUID)throw new Error('SECURE DEVICE ID IS NOT AVAILABLE ON THIS DEVICE.');id=crypto.randomUUID();localStorage.setItem('torvo_device_id',id)}return assertDevice(id)}
