import{requireBackend}from'./supabase';import{isNativeApp}from'./runtimePlatform';
const digits=v=>String(v||'').replace(/\D/g,'').slice(-10);const STAFF=new Set(['owner','admin','accountant','salesman','store_keeper']);const SESSION_KEY='torvo_staff_session_id';export const DEALER_SESSION_KEY='torvo_dealer_session_token';
const codeDigits=(v,n)=>String(v||'').replace(/\D/g,'').slice(0,n);const assertDevice=v=>{const x=String(v||'').trim();if(!x||x.length>180)throw new Error('SECURE DEVICE ID REQUIRED.');return x};
export const normalizeStaffUsername=v=>String(v||'').trim().toUpperCase();
export const BUSINESS_STAFF_USER_IDS=new Set(['OR@000','AD@001','AC@002','AC@003']);
export const isBusinessStaffUserId=v=>BUSINESS_STAFF_USER_IDS.has(normalizeStaffUsername(v));
const staffUsername=v=>{const x=normalizeStaffUsername(v);if(!isBusinessStaffUserId(x))throw new Error('ENTER AN AUTHORIZED USER ID.');return x};
export function normalizeDealerEmail(v){const e=String(v||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))throw new Error('ENTER A VALID REGISTERED EMAIL ID.');return e}
export function validateLoginIdentity(mode,value){if(mode==='dealer_email')return normalizeDealerEmail(value);if(mode==='staff_id')return staffUsername(value);throw new Error('SELECT EMAIL OR USER ID LOGIN.')}
function keep(result){if(result?.staff_session_id){const store=['salesman','store_keeper'].includes(result.role)?localStorage:sessionStorage;store.setItem(SESSION_KEY,result.staff_session_id)}return result}
export async function beginStaffEmailOtp(username){const client=requireBackend();const u=staffUsername(username),d=deviceId();const{data,error}=await client.functions.invoke('staff-email-otp',{body:{action:'begin',username:u,device_id:d}});if(error)throw error;if(!data?.ok||!data?.challenge_id)throw new Error('OTP COULD NOT BE SENT.');return data}
export async function verifyStaffEmailOtp(username,challengeId,otp){const client=requireBackend(),u=staffUsername(username),d=deviceId(),code=codeDigits(otp,6);if(code.length!==6)throw new Error('ENTER 6-DIGIT OTP.');const{data,error}=await client.functions.invoke('staff-email-otp',{body:{action:'verify',username:u,challenge_id:String(challengeId||''),otp:code,device_id:d}});if(error)throw error;if(!data?.staff_session_id)throw new Error('OTP VERIFICATION FAILED.');return keep(data)}
export async function beginDealerEmailOtp(email){const client=requireBackend(),e=normalizeDealerEmail(email),d=deviceId();const{data,error}=await client.functions.invoke('dealer-email-otp',{body:{action:'begin',email:e,device_id:d}});if(error)throw error;if(!data?.ok||!data?.challenge_id)throw new Error('OTP COULD NOT BE SENT.');return data}
export async function verifyDealerEmailOtp(email,challengeId,otp){const client=requireBackend(),e=normalizeDealerEmail(email),d=deviceId(),code=codeDigits(otp,6);if(code.length!==6)throw new Error('ENTER 6-DIGIT OTP.');clearDealerSession();const{data,error}=await client.functions.invoke('dealer-email-otp',{body:{action:'verify',email:e,challenge_id:String(challengeId||''),otp:code,device_id:d}});if(error)throw error;if(!data?.ok||!data?.dealer_session_token)throw new Error('OTP VERIFICATION FAILED.');localStorage.setItem(DEALER_SESSION_KEY,data.dealer_session_token);return data}
export function dealerSessionToken(){return localStorage.getItem(DEALER_SESSION_KEY)||''}export function clearDealerSession(){localStorage.removeItem(DEALER_SESSION_KEY)}export function clearStaffSession(){localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY)}
export function isStaffRole(role){return STAFF.has(role)}
export function deviceId(){const key=isNativeApp()?'torvo_native_installation_id':'torvo_web_device_id';let id=localStorage.getItem(key);if(!id){if(!globalThis.crypto?.randomUUID)throw new Error('SECURE DEVICE ID IS NOT AVAILABLE ON THIS DEVICE.');id=crypto.randomUUID();localStorage.setItem(key,id)}return assertDevice(id)}