import{requireBackend}from'./supabase';
const digits=v=>String(v||'').replace(/\D/g,'').slice(-10);const STAFF=new Set(['owner','admin','accountant','salesman','store_keeper']);const SESSION_KEY='torvo_staff_session_id';export const DEALER_SESSION_KEY='torvo_dealer_session_token';
const codeDigits=(v,n)=>String(v||'').replace(/\D/g,'').slice(0,n);const assertDevice=v=>{const x=String(v||'').trim();if(!x||x.length>180)throw new Error('SECURE DEVICE ID REQUIRED.');return x};
export const normalizeStaffUsername=v=>String(v||'').trim().toUpperCase();
const staffUsername=v=>{const x=normalizeStaffUsername(v);if(!/^[A-Z]{2,8}@[0-9]{2,6}$/.test(x))throw new Error('ENTER A VALID STAFF USER ID.');return x};
export function normalizeDealerMobile(v){const m=digits(v);if(m.length!==10)throw new Error('ENTER A VALID 10-DIGIT MOBILE NUMBER.');return m}
export function validateLoginIdentity(mode,value){if(mode==='dealer_mobile')return normalizeDealerMobile(value);if(mode==='staff_id')return staffUsername(value);throw new Error('SELECT MOBILE OR USER ID LOGIN.')}
export async function identifyLoginRole(mobile){const client=requireBackend();const m=normalizeDealerMobile(mobile);const{data,error}=await client.rpc('public_login_route',{p_mobile:m});if(error)throw error;return data}
function keep(result){if(result?.staff_session_id){const store=['salesman','store_keeper'].includes(result.role)?localStorage:sessionStorage;store.setItem(SESSION_KEY,result.staff_session_id)}return result}
export async function beginStaffEmailOtp(username,email){const client=requireBackend(),u=staffUsername(username),d=deviceId();const{data,error}=await client.functions.invoke('staff-email-otp',{body:{action:'begin',username:u,email:String(email||'').trim().toLowerCase(),device_id:d}});if(error)throw error;if(!data?.ok||!data?.challenge_id)throw new Error('OTP COULD NOT BE SENT.');return data}
export async function verifyStaffEmailOtp(username,email,challengeId,otp){const client=requireBackend(),u=staffUsername(username),d=deviceId(),code=codeDigits(otp,6);if(code.length!==6)throw new Error('ENTER 6-DIGIT OTP.');const{data,error}=await client.functions.invoke('staff-email-otp',{body:{action:'verify',username:u,email:String(email||'').trim().toLowerCase(),challenge_id:String(challengeId||''),otp:code,device_id:d}});if(error)throw error;if(!data?.staff_session_id)throw new Error('OTP VERIFICATION FAILED.');return keep(data)}
export async function verifyDealerPin(mobile,pin,deviceId){const client=requireBackend();const m=normalizeDealerMobile(mobile),p=codeDigits(pin,4),d=assertDevice(deviceId);if(p.length!==4)throw new Error('ENTER A VALID 4-DIGIT PIN.');clearDealerSession();const{data,error}=await client.functions.invoke('dealer-pin-login',{body:{mobile:m,pin:p,device_id:d}});if(error)throw error;if(!data?.ok||!data?.dealer_session_token)throw new Error(data?.message||'SECURE DEALER SESSION COULD NOT BE STARTED.');localStorage.setItem(DEALER_SESSION_KEY,data.dealer_session_token);return data}
export async function requestDealerPinRecovery(mobile){const client=requireBackend();const m=normalizeDealerMobile(mobile);const{data,error}=await client.functions.invoke('dealer-pin-recovery-request',{body:{mobile:m}});if(error)throw error;return data}
export function dealerSessionToken(){return localStorage.getItem(DEALER_SESSION_KEY)||''}export function clearDealerSession(){localStorage.removeItem(DEALER_SESSION_KEY)}export function clearStaffSession(){localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY)}
export function isStaffRole(role){return STAFF.has(role)}
export function deviceId(){let id=localStorage.getItem('torvo_device_id');if(!id){if(!globalThis.crypto?.randomUUID)throw new Error('SECURE DEVICE ID IS NOT AVAILABLE ON THIS DEVICE.');id=crypto.randomUUID();localStorage.setItem('torvo_device_id',id)}return assertDevice(id)}
