-- TORVO V2 ACCOUNTANT WORKSPACE BUTTONS
create table if not exists public.accountant_workspace_buttons(id uuid primary key default gen_random_uuid(),label text not null unique,description text,sort_order integer not null default 10,enabled boolean not null default true,updated_at timestamptz not null default now(),updated_by uuid);
alter table public.accountant_workspace_buttons enable row level security;
revoke all on public.accountant_workspace_buttons from anon,authenticated;
insert into public.accountant_workspace_buttons(label,description,sort_order) values
('SALES & ESTIMATES','VIEW BILLING AND ESTIMATE RECORDS',1),('PURCHASE','PURCHASE ENTRY AND HISTORY',2),('PAYMENTS','RECEIPTS, PAYMENTS AND PARTY BALANCES',3),('RETURNS','SALES AND PURCHASE RETURNS',4),('LEDGER','DEALER / SUPPLIER ACCOUNT VIEW',5),('REPORTS','SALES, PURCHASE, PAYMENT AND PROFIT REPORTS',6) on conflict(label) do nothing;
create or replace function public.accountant_workspace_buttons() returns table(id uuid,label text,description text,sort_order integer,enabled boolean) language sql security definer set search_path=public as $$ select b.id,b.label,b.description,b.sort_order,b.enabled from public.accountant_workspace_buttons b where b.enabled=true order by b.sort_order,b.label $$;
revoke all on function public.accountant_workspace_buttons() from public,anon;grant execute on function public.accountant_workspace_buttons() to authenticated;
create or replace function public.admin_save_accountant_workspace_button(p_id uuid,p_label text,p_description text,p_sort_order integer,p_enabled boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare v_role text;v_id uuid:=coalesce(p_id,gen_random_uuid());begin select upper(coalesce(role,'')) into v_role from public.app_users where auth_user_id=auth.uid() and active=true limit 1;if v_role not in('OWNER','ADMIN') then raise exception 'OWNER OR ADMIN REQUIRED';end if;if trim(coalesce(p_label,''))='' or length(trim(p_label))>50 then raise exception 'INVALID BUTTON NAME';end if;if p_sort_order<1 or p_sort_order>99 then raise exception 'INVALID SORT ORDER';end if;insert into public.accountant_workspace_buttons(id,label,description,sort_order,enabled,updated_at,updated_by) values(v_id,upper(trim(p_label)),nullif(upper(trim(coalesce(p_description,''))),''),p_sort_order,coalesce(p_enabled,true),now(),auth.uid()) on conflict(id) do update set label=excluded.label,description=excluded.description,sort_order=excluded.sort_order,enabled=excluded.enabled,updated_at=now(),updated_by=auth.uid();return v_id;end $$;
revoke all on function public.admin_save_accountant_workspace_button(uuid,text,text,integer,boolean) from public,anon;grant execute on function public.admin_save_accountant_workspace_button(uuid,text,text,integer,boolean) to authenticated;
