-- TORVO V2 ACCOUNTANT WORKSPACE CONFIGURATION
-- Install after CENTRAL ADMIN CONTROL / app_users. Staging first.
create table if not exists public.accountant_workspace_config(
 id bigint generated by default as identity primary key,
 label text not null,
 description text not null default '',
 sort_order integer not null check(sort_order between 1 and 1000),
 enabled boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(label)
);
alter table public.accountant_workspace_config enable row level security;
revoke all on public.accountant_workspace_config from anon,authenticated;
insert into public.accountant_workspace_config(label,description,sort_order) values
('SALES & ESTIMATES','VIEW BILLING AND ESTIMATE RECORDS',10),
('PURCHASE','PURCHASE ENTRY AND HISTORY',20),
('PAYMENTS','RECEIPTS, PAYMENTS AND PARTY BALANCES',30),
('RETURNS','SALES AND PURCHASE RETURNS',40),
('LEDGER','DEALER / SUPPLIER ACCOUNT VIEW',50),
('REPORTS','SALES, PURCHASE, PAYMENT AND PROFIT REPORTS',60)
on conflict(label) do nothing;
create or replace function public.accountant_workspace_buttons() returns table(id bigint,label text,description text,sort_order integer,enabled boolean) language sql security definer set search_path=public as $$
 select c.id,c.label,c.description,c.sort_order,c.enabled from public.accountant_workspace_config c
 where c.enabled=true and exists(select 1 from public.app_users u where u.auth_user_id=auth.uid() and upper(u.role)='ACCOUNTANT' and coalesce(u.active,true)=true)
 order by c.sort_order,c.id;
$$;
revoke all on function public.accountant_workspace_buttons() from public,anon;
grant execute on function public.accountant_workspace_buttons() to authenticated;
create or replace function public.admin_save_accountant_workspace_button(p_id bigint,p_label text,p_description text,p_sort_order integer,p_enabled boolean default true) returns bigint language plpgsql security definer set search_path=public as $$
declare v_role text;v_id bigint;
begin
 select upper(role) into v_role from public.app_users where auth_user_id=auth.uid() and coalesce(active,true)=true limit 1;
 if v_role not in('OWNER','ADMIN') then raise exception 'OWNER_OR_ADMIN_REQUIRED';end if;
 if nullif(trim(p_label),'') is null or length(trim(p_label))>60 or p_sort_order not between 1 and 1000 then raise exception 'INVALID_ACCOUNTANT_WORKSPACE_BUTTON';end if;
 if p_id is null then insert into public.accountant_workspace_config(label,description,sort_order,enabled) values(upper(trim(p_label)),upper(left(coalesce(p_description,''),160)),p_sort_order,coalesce(p_enabled,true)) returning id into v_id;
 else update public.accountant_workspace_config set label=upper(trim(p_label)),description=upper(left(coalesce(p_description,''),160)),sort_order=p_sort_order,enabled=coalesce(p_enabled,true),updated_at=now() where id=p_id returning id into v_id;end if;
 return v_id;
end$$;
revoke all on function public.admin_save_accountant_workspace_button(bigint,text,text,integer,boolean) from public,anon;
grant execute on function public.admin_save_accountant_workspace_button(bigint,text,text,integer,boolean) to authenticated;
