-- TORVO V2 secure business action RPCs. Actor identity always comes from auth.uid().
create or replace function approve_dealer(p_dealer uuid,p_dealer_code text,p_rate_group text) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;s text;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if p_rate_group not in('A','B','C') or nullif(trim(p_dealer_code),'') is null then raise exception 'Dealer code and valid rate group required';end if;select status into s from dealers where id=p_dealer for update;if not found then raise exception 'Dealer not found';end if;if s='approved' then raise exception 'Dealer already approved';end if;update dealers set dealer_code=upper(trim(p_dealer_code)),rate_group=p_rate_group,status='approved',approved_by=a.id,approved_at=now() where id=p_dealer;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'DEALER_APPROVED','dealer',p_dealer::text,jsonb_build_object('dealer_code',upper(trim(p_dealer_code)),'rate_group',p_rate_group));end;$$;
revoke all on function approve_dealer(uuid,text,text) from public,anon;grant execute on function approve_dealer(uuid,text,text) to authenticated;
create or replace function set_dealer_rate_group(p_dealer uuid,p_rate_group text,p_reason text) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;old_group text;dealer_status text;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if p_rate_group not in('A','B','C') or nullif(trim(p_reason),'') is null then raise exception 'Valid rate group and reason required';end if;select rate_group,status into old_group,dealer_status from dealers where id=p_dealer for update;if not found then raise exception 'Dealer not found';end if;if dealer_status<>'approved' then raise exception 'Only approved dealer rate group can be changed';end if;if old_group=p_rate_group then raise exception 'Dealer is already in this rate group';end if;update dealers set rate_group=p_rate_group where id=p_dealer;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'DEALER_RATE_GROUP_CHANGED','dealer',p_dealer::text,jsonb_build_object('old_rate_group',old_group,'new_rate_group',p_rate_group,'reason',trim(p_reason)));end;$$;
revoke all on function set_dealer_rate_group(uuid,text,text) from public,anon;grant execute on function set_dealer_rate_group(uuid,text,text) to authenticated;

-- Dealer-safe rate resolver. Returns only the caller's applicable rate; never purchase cost or other groups.
create or replace function dealer_item_rate(p_item uuid,p_qty numeric) returns table(item_id uuid,item_code text,item_name text,qty numeric,rate numeric,amount numeric) language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;d dealers%rowtype;r numeric;begin if p_qty is null or p_qty<=0 then raise exception 'Quantity must be greater than zero';end if;select * into a from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found then raise exception 'Dealer login required';end if;select d.* into d from dealers d where d.id=(select dealer_id from app_user_dealer_links where user_id=a.id limit 1) and d.status='approved';if not found or d.rate_group is null then raise exception 'Approved dealer rate group required';end if;select ir.selling_rate into r from item_rates ir where ir.item_id=p_item and ir.rate_group=d.rate_group and ir.min_qty<=p_qty order by ir.min_qty desc limit 1;if r is null then raise exception 'Rate not available for this quantity';end if;return query select c.id,c.item_code,c.name,p_qty,r,round(p_qty*r,2) from catalog_items c where c.id=p_item and c.active=true;if not found then raise exception 'Item not available';end if;end;$$;
revoke all on function dealer_item_rate(uuid,numeric) from public,anon;grant execute on function dealer_item_rate(uuid,numeric) to authenticated;

-- Dealer Purchase Order = TORVO Sales Order. Server resolves all rates and snapshots them.
create or replace function submit_purchase_order(p_lines jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;did uuid;rg text;oid uuid;ln jsonb;iid uuid;q numeric;r numeric;sub numeric:=0;begin if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'Order lines required';end if;select * into a from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found then raise exception 'Dealer login required';end if;select d.id,d.rate_group into did,rg from dealers d join app_user_dealer_links l on l.dealer_id=d.id where l.user_id=a.id and d.status='approved' limit 1;if did is null or rg is null then raise exception 'Approved dealer required';end if;insert into sales_documents(dealer_id,doc_type,status,subtotal,final_payable,created_by,revision_no,dealer_modification_limit,dealer_modifications_used) values(did,'sales_order','submitted',0,0,a.id,1,2,0) returning id into oid;for ln in select * from jsonb_array_elements(p_lines) loop begin iid:=(ln->>'item_id')::uuid;q:=(ln->>'qty')::numeric;exception when others then raise exception 'Invalid order line';end;if q is null or q<=0 then raise exception 'Invalid quantity';end if;perform 1 from catalog_items where id=iid and active=true;if not found then raise exception 'Item unavailable';end if;select selling_rate into r from item_rates where item_id=iid and rate_group=rg and min_qty<=q order by min_qty desc limit 1;if r is null then raise exception 'Rate unavailable for an item';end if;insert into sales_document_lines(document_id,item_id,qty,rate,amount) values(oid,iid,q,r,round(q*r,2));sub:=sub+round(q*r,2);end loop;update sales_documents set subtotal=sub,final_payable=sub,root_order_id=oid where id=oid;insert into sales_order_revisions(sales_order_id,revision_no,changed_by,actor_role,change_reason,after_data) values(oid,1,a.id,'dealer','PURCHASE ORDER SUBMITTED',jsonb_build_object('subtotal',sub,'lines',p_lines));insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'PURCHASE_ORDER_SUBMITTED','sales_order',oid::text,jsonb_build_object('dealer_id',did,'subtotal',sub));return oid;exception when others then raise;end;$$;
revoke all on function submit_purchase_order(jsonb) from public,anon;grant execute on function submit_purchase_order(jsonb) to authenticated;

-- Admin-controlled spare-part free-delivery threshold with immutable history.
create or replace function set_delivery_settings(p_enabled boolean,p_threshold numeric,p_reason text) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;s delivery_settings%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if p_threshold is null or p_threshold<0 or nullif(trim(p_reason),'') is null then raise exception 'Valid threshold and reason required';end if;select * into s from delivery_settings where id=true for update;insert into delivery_setting_history(old_enabled,old_threshold,new_enabled,new_threshold,reason,changed_by) values(s.spare_free_delivery_enabled,s.spare_free_delivery_threshold,p_enabled,p_threshold,trim(p_reason),a.id);update delivery_settings set spare_free_delivery_enabled=p_enabled,spare_free_delivery_threshold=p_threshold,updated_by=a.id,updated_at=now() where id=true;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'DELIVERY_SETTINGS_CHANGED','delivery_settings','GLOBAL',jsonb_build_object('enabled',p_enabled,'threshold',p_threshold,'reason',trim(p_reason)));end;$$;
revoke all on function set_delivery_settings(boolean,numeric,text) from public,anon;grant execute on function set_delivery_settings(boolean,numeric,text) to authenticated;

-- Internal payment note; dealer never sees this data. Total recorded amount may not exceed estimate payable.
drop function if exists record_payment(uuid,text,numeric);drop function if exists record_payment(uuid,text,numeric,text);
create or replace function record_payment(p_estimate uuid,p_status text,p_amount numeric,p_request_key text) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;pid uuid;f numeric;already numeric;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant') then raise exception 'Not authorized';end if;if p_status not in('cash','pending','received') or p_amount is null or p_amount<=0 or nullif(trim(p_request_key),'') is null then raise exception 'Valid internal payment entry required';end if;select final_payable into f from sales_documents where id=p_estimate and doc_type='estimate' for update;if not found then raise exception 'Estimate not found';end if;select coalesce(sum(amount),0) into already from payments where estimate_id=p_estimate and status in('cash','received');if p_status in('cash','received') and already+p_amount>f then raise exception 'Payment exceeds estimate payable';end if;insert into payments(estimate_id,status,amount,received_at,recorded_by) values(p_estimate,p_status,p_amount,case when p_status in('cash','received') then now() else null end,a.id) returning id into pid;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'INTERNAL_PAYMENT_NOTED','estimate',p_estimate::text,jsonb_build_object('payment_id',pid,'status',p_status,'amount',p_amount,'request_key',trim(p_request_key)));return pid;end;$$;
revoke all on function record_payment(uuid,text,numeric,text) from public,anon;grant execute on function record_payment(uuid,text,numeric,text) to authenticated;

create or replace function create_accounting_balance(p_estimate uuid,p_amount numeric,p_remarks text default null) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;bid uuid;did uuid;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant') then raise exception 'Not authorized';end if;if p_amount is null or p_amount<=0 then raise exception 'Balance amount must be greater than zero';end if;select dealer_id into did from sales_documents where id=p_estimate and doc_type='estimate';if not found then raise exception 'Estimate not found';end if;insert into accounting_balances(estimate_id,dealer_id,balance_amount,remarks) values(p_estimate,did,p_amount,nullif(trim(p_remarks),'')) returning id into bid;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'ACCOUNTING_BALANCE_CREATED','accounting_balance',bid::text,jsonb_build_object('estimate_id',p_estimate,'amount',p_amount));return bid;end;$$;
revoke all on function create_accounting_balance(uuid,numeric,text) from public,anon;grant execute on function create_accounting_balance(uuid,numeric,text) to authenticated;
create or replace function mark_accounting_balance_entered(p_balance uuid,p_entry_no text) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;b accounting_balances%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant') then raise exception 'Not authorized';end if;if nullif(trim(p_entry_no),'') is null then raise exception 'Accounting entry number required';end if;select * into b from accounting_balances where id=p_balance for update;if not found then raise exception 'Balance record not found';end if;if b.status<>'pending' then raise exception 'Balance already marked accounting entered';end if;update accounting_balances set status='accounting_entered',accounting_entry_no=upper(trim(p_entry_no)),accounting_entered_at=now(),accounting_entered_by=a.id where id=p_balance;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'ACCOUNTING_BALANCE_ENTERED','accounting_balance',p_balance::text,jsonb_build_object('balance_amount',b.balance_amount,'accounting_entry_no',upper(trim(p_entry_no))));end;$$;
revoke all on function mark_accounting_balance_entered(uuid,text) from public,anon;grant execute on function mark_accounting_balance_entered(uuid,text) to authenticated;
create or replace function advance_dispatch(p_estimate uuid,p_status text,p_tracking_code text default null) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;cur text;nxt text;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','store_keeper') then raise exception 'Not authorized';end if;if p_status='delivered' then raise exception 'Use deliver_estimate for delivery';end if;select status into cur from dispatches where estimate_id=p_estimate for update;if not found then raise exception 'Dispatch not found';end if;nxt:=case cur when 'pick_list' then 'picked' when 'picked' then 'packed' when 'packed' then 'ready_for_dispatch' else null end;if p_status<>nxt then raise exception 'Invalid dispatch transition';end if;update dispatches set status=p_status,tracking_code=coalesce(nullif(trim(p_tracking_code),''),tracking_code),updated_by=a.id where estimate_id=p_estimate;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'DISPATCH_STATUS_CHANGED','estimate',p_estimate::text,jsonb_build_object('from',cur,'to',p_status));end;$$;
revoke all on function advance_dispatch(uuid,text,text) from public,anon;grant execute on function advance_dispatch(uuid,text,text) to authenticated;
