-- TORVO V2 COMPANY FOOTER ADMIN FORWARD MIGRATION
update public.admin_managed_settings set setting_value=coalesce(setting_value,'{}'::jsonb)||jsonb_build_object('company_name',coalesce(nullif(setting_value->>'company_name',''),'TORVO TOOLS PRIVATE LIMITED'),'company_address',coalesce(setting_value->>'company_address',''),'gst_number',coalesce(setting_value->>'gst_number','')),updated_at=now() where setting_key='website_top_bar';

create or replace function public.admin_save_managed_setting(p_key text,p_value jsonb,p_active boolean default true,p_reason text default null) returns boolean language plpgsql security definer set search_path=public as $$
declare u app_users%rowtype;oldv jsonb;cn text;bn text;k text;
begin
select * into u from app_users where auth_user_id=auth.uid() and active=true;if u.id is null or u.role not in('owner','admin') then raise exception 'OWNER OR ADMIN REQUIRED';end if;if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception 'CHANGE REASON REQUIRED';end if;if p_value is null or jsonb_typeof(p_value)<>'object' then raise exception 'SETTING VALUE MUST BE A JSON OBJECT';end if;select setting_value into oldv from admin_managed_settings where setting_key=p_key for update;if not found then raise exception 'UNKNOWN MANAGED SETTING';end if;
if p_key='website_top_bar' then if jsonb_typeof(p_value->'enabled')<>'boolean' then raise exception 'TOP BAR ENABLED FLAG MUST BE BOOLEAN';end if;if coalesce(p_value->>'mobile','')<>'' and length(regexp_replace(p_value->>'mobile','\D','','g')) not in(10,12) then raise exception 'VALID TOP BAR MOBILE REQUIRED';end if;if nullif(btrim(coalesce(p_value->>'company_name','')),'') is null then raise exception 'COMPANY NAME REQUIRED';end if;if length(coalesce(p_value->>'company_name',''))>120 then raise exception 'COMPANY NAME TOO LONG';end if;if length(coalesce(p_value->>'company_address',''))>500 then raise exception 'COMPANY ADDRESS TOO LONG';end if;if coalesce(p_value->>'gst_number','')<>'' and upper(btrim(p_value->>'gst_number')) !~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$' then raise exception 'VALID GST NUMBER REQUIRED';end if;end if;
if p_key='whatsapp_channels' then cn:=regexp_replace(coalesce(p_value->>'customer_number',''),'\D','','g');bn:=regexp_replace(coalesce(p_value->>'business_number',''),'\D','','g');if length(cn) not in(10,12) or length(bn) not in(10,12) then raise exception 'VALID WHATSAPP NUMBERS REQUIRED';end if;if jsonb_typeof(p_value->'customer_active')<>'boolean' or jsonb_typeof(p_value->'business_active')<>'boolean' then raise exception 'WHATSAPP ACTIVE FLAGS MUST BE BOOLEAN';end if;end if;
if p_key='feature_switches' then foreach k in array array['dealer_registration','customer_profile','notifications','product_promotions','popular_products','customer_referral','repair_service','customer_catalog'] loop if not(p_value?k) or jsonb_typeof(p_value->k)<>'boolean' then raise exception 'FEATURE SWITCH % MUST BE BOOLEAN',upper(k);end if;end loop;end if;
update admin_managed_settings set setting_value=p_value,active=coalesce(p_active,true),updated_by=u.id,updated_at=now() where setting_key=p_key;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(u.id,'ADMIN_MANAGED_SETTING_UPDATED','SETTING',p_key,jsonb_build_object('old',oldv,'new',p_value,'reason',upper(btrim(p_reason))));return true;end$$;
revoke all on function public.admin_save_managed_setting(text,jsonb,boolean,text) from public,anon;grant execute on function public.admin_save_managed_setting(text,jsonb,boolean,text) to authenticated;
