-- TORVO V2 CUSTOMER SUPPORT + MISSING RANGE FOUNDATION
-- Run after core app_users, dealers, catalog_items and customer_product_enquiries migrations.
create extension if not exists pgcrypto;

create table if not exists public.customer_product_requirements(
 id uuid primary key default gen_random_uuid(), customer_name text not null, mobile_whatsapp text not null, state text, district text, city text, pin_code text not null,
 product_type text not null check(product_type in('MACHINE','SPARE PART','ACCESSORY')), brand text, machine_model text, required_item text not null, item_oem_no text, description text,
 quantity integer not null default 1 check(quantity>0), photo_url text, marketing_opt_in boolean not null default false, marketing_consent_at timestamptz, marketing_consent_source text, marketing_opted_out_at timestamptz,
 status text not null default 'OPEN' check(status in('OPEN','UNDER REVIEW','RESOLVED','REJECTED','PRODUCT ADDED','FULFILLED','CLOSED')), linked_product_id uuid references public.catalog_items(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.customer_product_requirements add column if not exists marketing_consent_at timestamptz;
alter table public.customer_product_requirements add column if not exists marketing_consent_source text;
alter table public.customer_product_requirements add column if not exists marketing_opted_out_at timestamptz;
create index if not exists customer_product_requirements_lookup on public.customer_product_requirements(status,product_type,brand,created_at desc);

create table if not exists public.customer_complaints(
 id uuid primary key default gen_random_uuid(), customer_name text not null, mobile_whatsapp text not null, dealer_id uuid references public.dealers(id) on delete set null, enquiry_id uuid references public.customer_product_enquiries(id) on delete set null,
 category text not null check(category in('BEHAVIOUR','WRONG INFORMATION','PRODUCT ISSUE','OVERCHARGING / COMMERCIAL ISSUE','SERVICE ISSUE','OTHER')), description text not null, attachment_url text,
 status text not null default 'OPEN' check(status in('OPEN','UNDER REVIEW','RESOLVED','REJECTED')), resolution_note text, resolved_by uuid references public.app_users(id) on delete set null, resolved_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.customer_complaints add column if not exists resolved_by uuid references public.app_users(id) on delete set null;
alter table public.customer_complaints add column if not exists resolved_at timestamptz;
create index if not exists customer_complaints_admin_lookup on public.customer_complaints(status,dealer_id,created_at desc);
create unique index if not exists customer_complaints_open_dedupe on public.customer_complaints(mobile_whatsapp,coalesce(dealer_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(enquiry_id,'00000000-0000-0000-0000-000000000000'::uuid),category) where status in('OPEN','UNDER REVIEW');

alter table public.customer_product_requirements enable row level security;alter table public.customer_complaints enable row level security;
revoke all on public.customer_product_requirements from anon,authenticated;revoke all on public.customer_complaints from anon,authenticated;

create or replace function public.public_create_product_requirement(p_customer_name text,p_mobile_whatsapp text,p_state text,p_district text,p_city text,p_pin_code text,p_product_type text,p_brand text,p_machine_model text,p_required_item text,p_item_oem_no text,p_description text,p_quantity integer default 1,p_photo_url text default null,p_marketing_opt_in boolean default false)
returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v_mobile text:=regexp_replace(coalesce(p_mobile_whatsapp,''),'\D','','g');v_pin text:=trim(coalesce(p_pin_code,''));v_type text:=upper(trim(coalesce(p_product_type,'')));begin
 if length(trim(coalesce(p_customer_name,'')))<2 then raise exception 'CUSTOMER NAME REQUIRED';end if;if length(v_mobile)<>10 then raise exception '10-DIGIT MOBILE / WHATSAPP REQUIRED';end if;if v_pin!~'^[0-9]{6}$' then raise exception '6-DIGIT PIN CODE REQUIRED';end if;
 if length(trim(coalesce(p_state,'')))<2 then raise exception 'STATE REQUIRED';end if;if length(trim(coalesce(p_district,'')))<2 then raise exception 'DISTRICT REQUIRED';end if;if length(trim(coalesce(p_city,'')))<2 then raise exception 'CITY REQUIRED';end if;
 if v_type not in('MACHINE','SPARE PART','ACCESSORY') then raise exception 'VALID PRODUCT TYPE REQUIRED';end if;if length(trim(coalesce(p_required_item,'')))<2 then raise exception 'REQUIRED PRODUCT / ITEM REQUIRED';end if;if coalesce(p_quantity,0)<1 then raise exception 'VALID QUANTITY REQUIRED';end if;
 insert into customer_product_requirements(customer_name,mobile_whatsapp,state,district,city,pin_code,product_type,brand,machine_model,required_item,item_oem_no,description,quantity,photo_url,marketing_opt_in,marketing_consent_at,marketing_consent_source,marketing_opted_out_at)
 values(upper(trim(p_customer_name)),right(v_mobile,10),upper(trim(p_state)),upper(trim(p_district)),upper(trim(p_city)),v_pin,v_type,upper(nullif(trim(p_brand),'')),upper(nullif(trim(p_machine_model),'')),upper(trim(p_required_item)),upper(nullif(trim(p_item_oem_no),'')),upper(nullif(trim(p_description),'')),p_quantity,nullif(trim(p_photo_url),''),coalesce(p_marketing_opt_in,false),case when coalesce(p_marketing_opt_in,false) then now() else null end,case when coalesce(p_marketing_opt_in,false) then 'PUBLIC WEBSITE' else null end,null) returning id into v_id;return v_id;end$$;
create or replace function public.public_set_product_requirement_marketing_opt_out(p_requirement_id uuid,p_mobile_whatsapp text) returns boolean language plpgsql security definer set search_path=public as $$declare v_mobile text:=regexp_replace(coalesce(p_mobile_whatsapp,''),'\D','','g');begin if p_requirement_id is null then raise exception 'REQUIREMENT ID REQUIRED';end if;if length(v_mobile)<>10 then raise exception '10-DIGIT MOBILE / WHATSAPP REQUIRED';end if;update customer_product_requirements set marketing_opt_in=false,marketing_opted_out_at=now(),updated_at=now() where id=p_requirement_id and mobile_whatsapp=right(v_mobile,10);if not found then raise exception 'PRODUCT REQUIREMENT NOT FOUND';end if;return true;end$$;
create or replace function public.public_create_customer_complaint(p_customer_name text,p_mobile_whatsapp text,p_dealer_id uuid,p_enquiry_id uuid,p_category text,p_description text,p_attachment_url text default null)
returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v_mobile text:=regexp_replace(coalesce(p_mobile_whatsapp,''),'\D','','g');v_cat text:=upper(trim(coalesce(p_category,'')));begin
 if length(trim(coalesce(p_customer_name,'')))<2 then raise exception 'CUSTOMER NAME REQUIRED';end if;if length(v_mobile)<>10 then raise exception '10-DIGIT MOBILE / WHATSAPP REQUIRED';end if;if v_cat not in('BEHAVIOUR','WRONG INFORMATION','PRODUCT ISSUE','OVERCHARGING / COMMERCIAL ISSUE','SERVICE ISSUE','OTHER') then raise exception 'VALID COMPLAINT CATEGORY REQUIRED';end if;if length(trim(coalesce(p_description,'')))<5 then raise exception 'COMPLAINT DETAILS REQUIRED';end if;
 if p_dealer_id is not null and not exists(select 1 from dealers d where d.id=p_dealer_id and upper(coalesce(d.status,''))='APPROVED') then raise exception 'VALID APPROVED DEALER REQUIRED';end if;if p_enquiry_id is not null and not exists(select 1 from customer_product_enquiries e where e.id=p_enquiry_id and e.mobile_whatsapp=right(v_mobile,10)) then raise exception 'CUSTOMER ENQUIRY NOT FOUND FOR MOBILE';end if;
 if exists(select 1 from customer_complaints c where c.mobile_whatsapp=right(v_mobile,10) and c.dealer_id is not distinct from p_dealer_id and c.enquiry_id is not distinct from p_enquiry_id and c.category=v_cat and c.status in('OPEN','UNDER REVIEW')) then raise exception 'SIMILAR COMPLAINT ALREADY OPEN';end if;
 begin insert into customer_complaints(customer_name,mobile_whatsapp,dealer_id,enquiry_id,category,description,attachment_url) values(upper(trim(p_customer_name)),right(v_mobile,10),p_dealer_id,p_enquiry_id,v_cat,upper(trim(p_description)),nullif(trim(p_attachment_url),'')) returning id into v_id;exception when unique_violation then raise exception 'SIMILAR COMPLAINT ALREADY OPEN';end;return v_id;end$$;

grant execute on function public.public_create_product_requirement(text,text,text,text,text,text,text,text,text,text,text,text,integer,text,boolean) to anon,authenticated;grant execute on function public.public_set_product_requirement_marketing_opt_out(uuid,text) to anon,authenticated;grant execute on function public.public_create_customer_complaint(text,text,uuid,uuid,text,text,text) to anon,authenticated;

create or replace function public.torvo_admin_customer_requirements(p_status text default null) returns setof public.customer_product_requirements language sql security definer set search_path=public as $$select r.* from customer_product_requirements r where exists(select 1 from app_users u where u.auth_user_id=auth.uid() and lower(u.role) in('owner','admin') and coalesce(u.active,true)) and (p_status is null or r.status=upper(p_status)) order by r.created_at desc$$;
create or replace function public.torvo_admin_customer_complaints(p_status text default null) returns setof public.customer_complaints language sql security definer set search_path=public as $$select c.* from customer_complaints c where exists(select 1 from app_users u where u.auth_user_id=auth.uid() and lower(u.role) in('owner','admin') and coalesce(u.active,true)) and (p_status is null or c.status=upper(p_status)) order by c.created_at desc$$;
create or replace function public.torvo_admin_update_customer_complaint(p_complaint_id uuid,p_status text,p_resolution_note text default null)
returns public.customer_complaints language plpgsql security definer set search_path=public as $$declare v_user app_users%rowtype;v_status text:=upper(trim(coalesce(p_status,'')));v_row customer_complaints%rowtype;begin
 select * into v_user from app_users u where u.auth_user_id=auth.uid() and lower(u.role) in('owner','admin') and coalesce(u.active,true) limit 1;if v_user.id is null then raise exception 'OWNER / ADMIN ACCESS REQUIRED';end if;
 if p_complaint_id is null then raise exception 'COMPLAINT ID REQUIRED';end if;if v_status not in('OPEN','UNDER REVIEW','RESOLVED','REJECTED') then raise exception 'VALID COMPLAINT STATUS REQUIRED';end if;
 if v_status in('RESOLVED','REJECTED') and length(trim(coalesce(p_resolution_note,'')))<3 then raise exception 'RESOLUTION NOTE REQUIRED';end if;
 update customer_complaints set status=v_status,resolution_note=case when v_status in('RESOLVED','REJECTED') then upper(trim(p_resolution_note)) else null end,resolved_by=case when v_status in('RESOLVED','REJECTED') then v_user.id else null end,resolved_at=case when v_status in('RESOLVED','REJECTED') then now() else null end,updated_at=now() where id=p_complaint_id returning * into v_row;
 if v_row.id is null then raise exception 'CUSTOMER COMPLAINT NOT FOUND';end if;return v_row;end$$;
grant execute on function public.torvo_admin_customer_requirements(text) to authenticated;grant execute on function public.torvo_admin_customer_complaints(text) to authenticated;grant execute on function public.torvo_admin_update_customer_complaint(uuid,text,text) to authenticated;