-- TORVO V2 CUSTOMER MARKETING CONSENT + SEGMENTATION
-- PRIVATE, VOLUNTARY CUSTOMER PROFILE DATA ONLY. NO SOCIAL SCRAPING.
alter table customer_contacts add column if not exists area text;
alter table customer_contacts add column if not exists trade_category text;
alter table customer_contacts add column if not exists facebook_url text;
alter table customer_contacts add column if not exists instagram_url text;
alter table customer_contacts add column if not exists consent_updated_at timestamptz;
create table if not exists customer_marketing_consent_events(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customer_contacts(id) on delete cascade,opted_in boolean not null,source text not null,created_at timestamptz not null default now());
alter table customer_marketing_consent_events enable row level security;revoke all on customer_marketing_consent_events from anon,authenticated;
create or replace function public_update_customer_marketing_profile(p_mobile text,p_full_name text,p_pin_code text,p_city text default null,p_area text default null,p_trade_category text default null,p_marketing_opt_in boolean default false,p_source text default 'PUBLIC WEBSITE') returns uuid language plpgsql security definer set search_path=public as $$declare m text:=right(regexp_replace(coalesce(p_mobile,''),'\D','','g'),10);c customer_contacts%rowtype;begin if length(m)<>10 then raise exception '10-DIGIT MOBILE REQUIRED';end if;if coalesce(p_pin_code,'')!~'^[0-9]{6}$' then raise exception '6-DIGIT PIN CODE REQUIRED';end if;insert into customer_contacts(full_name,mobile,whatsapp,pin_code,city,area,trade_category,marketing_opt_in,marketing_opt_in_at,marketing_opt_in_source,marketing_opt_out_at,consent_updated_at) values(upper(trim(p_full_name)),m,m,p_pin_code,upper(nullif(trim(p_city),'')),upper(nullif(trim(p_area),'')),upper(nullif(trim(p_trade_category),'')),p_marketing_opt_in,case when p_marketing_opt_in then now() end,upper(trim(p_source)),case when not p_marketing_opt_in then now() end,now()) on conflict(mobile) do update set full_name=excluded.full_name,whatsapp=excluded.whatsapp,pin_code=excluded.pin_code,city=coalesce(excluded.city,customer_contacts.city),area=coalesce(excluded.area,customer_contacts.area),trade_category=coalesce(excluded.trade_category,customer_contacts.trade_category),marketing_opt_in=excluded.marketing_opt_in,marketing_opt_in_at=case when excluded.marketing_opt_in then coalesce(customer_contacts.marketing_opt_in_at,now()) else null end,marketing_opt_in_source=excluded.marketing_opt_in_source,marketing_opt_out_at=case when excluded.marketing_opt_in then null else now() end,consent_updated_at=now(),updated_at=now() returning * into c;insert into customer_marketing_consent_events(customer_id,opted_in,source)values(c.id,p_marketing_opt_in,upper(trim(p_source)));return c.id;end$$;
create or replace function admin_customer_marketing_segments(p_trade_category text default null,p_city text default null) returns table(customer_id uuid,full_name text,mobile text,whatsapp text,pin_code text,city text,area text,trade_category text,marketing_opt_in boolean) language plpgsql security definer set search_path=public as $$declare u app_users%rowtype;begin select * into u from app_users where auth_user_id=auth.uid() and active=true;if u.id is null or u.role not in('owner','admin') then raise exception 'OWNER OR ADMIN REQUIRED';end if;return query select c.id,c.full_name,c.mobile,c.whatsapp,c.pin_code,c.city,c.area,c.trade_category,c.marketing_opt_in from customer_contacts c where c.marketing_opt_in=true and c.marketing_opt_out_at is null and(p_trade_category is null or c.trade_category=upper(trim(p_trade_category)))and(p_city is null or c.city=upper(trim(p_city)))order by c.city,c.trade_category,c.full_name;end$$;
revoke all on function public_update_customer_marketing_profile(text,text,text,text,text,text,boolean,text),admin_customer_marketing_segments(text,text) from public;grant execute on function public_update_customer_marketing_profile(text,text,text,text,text,text,boolean,text) to anon,authenticated;grant execute on function admin_customer_marketing_segments(text,text) to authenticated;
