-- TORVO V2 DEALER TARGET REWARDS
-- FINAL RULE: NO PER-INVOICE POINTS. ELIGIBLE PURCHASE VALUE REACHES ADMIN TARGET SLABS -> POINTS -> GIFT/VOUCHER.
create table if not exists dealer_target_types(id uuid primary key default gen_random_uuid(),name text not null unique,scheme_start_month int not null default 4 check(scheme_start_month between 1 and 12),active boolean not null default true,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists dealer_target_slabs(id uuid primary key default gen_random_uuid(),target_type_id uuid not null references dealer_target_types(id) on delete restrict,target_value numeric(14,2) not null check(target_value>0),points int not null check(points>0),active boolean not null default true,unique(target_type_id,target_value));
create table if not exists dealer_target_assignments(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id) on delete restrict,target_type_id uuid not null references dealer_target_types(id) on delete restrict,scheme_year int not null check(scheme_year between 2020 and 2100),active boolean not null default true,assigned_by uuid references app_users(id),unique(dealer_id,scheme_year));
create table if not exists dealer_reward_catalog(id uuid primary key default gen_random_uuid(),name text not null,points_required int not null check(points_required>0),gift_value numeric(12,2) check(gift_value>=0),redemption_type text not null check(redemption_type in('gift','voucher')),active boolean not null default true,sort_order int not null default 100,created_by uuid references app_users(id));
create table if not exists dealer_reward_points_ledger(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id),scheme_year int not null,points int not null,entry_type text not null check(entry_type in('target_earned','claim_debit','claim_reversal','admin_adjustment')),reference_id uuid,note text,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists dealer_reward_claims(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id),scheme_year int not null,reward_id uuid not null references dealer_reward_catalog(id),points_used int not null check(points_used>0),status text not null default 'requested' check(status in('requested','approved','issued','cancelled')),voucher_provider text check(voucher_provider in('AMAZON','FLIPKART') or voucher_provider is null),voucher_code text,requested_at timestamptz not null default now(),approved_by uuid references app_users(id),approved_at timestamptz,issued_at timestamptz);
alter table dealer_target_types enable row level security;alter table dealer_target_slabs enable row level security;alter table dealer_target_assignments enable row level security;alter table dealer_reward_catalog enable row level security;alter table dealer_reward_points_ledger enable row level security;alter table dealer_reward_claims enable row level security;revoke all on dealer_target_types,dealer_target_slabs,dealer_target_assignments,dealer_reward_catalog,dealer_reward_points_ledger,dealer_reward_claims from anon,authenticated;
create or replace function dealer_reward_balance() returns int language plpgsql security definer set search_path=public as $$declare d uuid;y int;b int;begin select dealer_id into d from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if d is null then raise exception 'DEALER APP LOGIN REQUIRED';end if;y:=case when extract(month from current_date)>=4 then extract(year from current_date)::int else extract(year from current_date)::int-1 end;select coalesce(sum(points),0)::int into b from dealer_reward_points_ledger where dealer_id=d and scheme_year=y;return b;end$$;
create or replace function dealer_reward_options() returns table(id uuid,name text,points_required int,gift_value numeric,redemption_type text,available boolean) language plpgsql security definer set search_path=public as $$declare b int;begin b:=dealer_reward_balance();return query select r.id,r.name,r.points_required,r.gift_value,r.redemption_type,(b>=r.points_required) from dealer_reward_catalog r where r.active=true order by r.points_required,r.sort_order;end$$;
create or replace function dealer_claim_reward(p_reward uuid) returns uuid language plpgsql security definer set search_path=public as $$declare d uuid;y int;b int;r dealer_reward_catalog%rowtype;c uuid;begin select dealer_id into d from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if d is null then raise exception 'DEALER APP LOGIN REQUIRED';end if;y:=case when extract(month from current_date)>=4 then extract(year from current_date)::int else extract(year from current_date)::int-1 end;select * into r from dealer_reward_catalog where id=p_reward and active=true;if not found then raise exception 'REWARD NOT AVAILABLE';end if;b:=dealer_reward_balance();if b<r.points_required then raise exception 'NOT ENOUGH POINTS';end if;insert into dealer_reward_claims(dealer_id,scheme_year,reward_id,points_used)values(d,y,r.id,r.points_required)returning id into c;insert into dealer_reward_points_ledger(dealer_id,scheme_year,points,entry_type,reference_id,note)values(d,y,-r.points_required,'claim_debit',c,'DEALER REWARD CLAIM');return c;end$$;
create or replace function admin_issue_reward_voucher(p_claim uuid,p_provider text,p_code text) returns boolean language plpgsql security definer set search_path=public as $$declare u app_users%rowtype;c dealer_reward_claims%rowtype;begin select * into u from app_users where auth_user_id=auth.uid() and active=true;if u.id is null or u.role not in('owner','admin')then raise exception 'OWNER OR ADMIN REQUIRED';end if;if upper(p_provider) not in('AMAZON','FLIPKART') or nullif(btrim(p_code),'') is null then raise exception 'VALID VOUCHER REQUIRED';end if;select * into c from dealer_reward_claims where id=p_claim for update;if not found or c.status not in('requested','approved')then raise exception 'CLAIM NOT READY';end if;update dealer_reward_claims set status='issued',voucher_provider=upper(p_provider),voucher_code=btrim(p_code),approved_by=coalesce(approved_by,u.id),approved_at=coalesce(approved_at,now()),issued_at=now() where id=p_claim;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(u.id,'DEALER_REWARD_VOUCHER_ISSUED','REWARD_CLAIM',p_claim::text,jsonb_build_object('provider',upper(p_provider)));return true;end$$;
revoke all on function dealer_reward_balance(),dealer_reward_options(),dealer_claim_reward(uuid),admin_issue_reward_voucher(uuid,text,text) from public,anon;grant execute on function dealer_reward_balance(),dealer_reward_options(),dealer_claim_reward(uuid),admin_issue_reward_voucher(uuid,text,text) to authenticated;
