-- TORVO V2 Dealer profile and Missing Spare Part RPCs are bound to the authenticated Dealer's active device session.
create or replace function public.dealer_my_profile(p_device_id text,p_session_token text)
returns table(id uuid,dealer_code text,shop_name text,contact_person text,mobile text,whatsapp text,status text,rate_group text)
language plpgsql security definer set search_path=public as $$declare v_dealer_id uuid;begin v_dealer_id:=public.dealer_assert_my_device_session(p_device_id,p_session_token);return query select d.id,d.dealer_code,d.shop_name,d.contact_person,d.mobile,d.whatsapp,d.status,d.rate_group from dealers d where d.id=v_dealer_id;end;$$;

create or replace function public.dealer_create_missing_part_request(p_device_id text,p_session_token text,p_machine_brand text default null,p_machine_model text default null,p_part_name text default null,p_requested_qty numeric default null,p_dealer_message text default null,p_photo_url text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_dealer_id uuid;v_id uuid;v_brand text:=nullif(upper(btrim(coalesce(p_machine_brand,''))),'');v_model text:=nullif(upper(btrim(coalesce(p_machine_model,''))),'');v_part text:=nullif(upper(btrim(coalesce(p_part_name,''))),'');v_message text:=nullif(btrim(coalesce(p_dealer_message,'')),'');v_photo text:=nullif(btrim(coalesce(p_photo_url,'')),'');
begin v_dealer_id:=public.dealer_assert_my_device_session(p_device_id,p_session_token);if v_part is null and v_message is null then raise exception 'PART NAME OR REQUIREMENT DESCRIPTION REQUIRED';end if;if length(coalesce(v_brand,''))>80 then raise exception 'MACHINE BRAND IS TOO LONG';end if;if length(coalesce(v_model,''))>120 then raise exception 'MACHINE MODEL IS TOO LONG';end if;if length(coalesce(v_part,''))>160 then raise exception 'PART NAME IS TOO LONG';end if;if length(coalesce(v_message,''))>1000 then raise exception 'REQUIREMENT DESCRIPTION IS TOO LONG';end if;if p_requested_qty is not null and (p_requested_qty<1 or p_requested_qty>9999 or trunc(p_requested_qty)<>p_requested_qty) then raise exception 'QUANTITY MUST BE A WHOLE NUMBER BETWEEN 1 AND 9999';end if;if v_photo is not null then raise exception 'SECURE PHOTO UPLOAD IS NOT CONNECTED YET';end if;insert into missing_part_requests(dealer_id,photo_url,machine_brand,machine_model,part_name,requested_qty,dealer_message,status) values(v_dealer_id,'',v_brand,v_model,v_part,p_requested_qty,v_message,'new') returning id into v_id;return v_id;end;$$;

create or replace function public.dealer_my_missing_part_requests(p_device_id text,p_session_token text)
returns table(id uuid,machine_brand text,machine_model text,part_name text,requested_qty numeric,dealer_message text,status text,reply_text text,created_at timestamptz)
language plpgsql security definer set search_path=public as $$declare v_dealer_id uuid;begin v_dealer_id:=public.dealer_assert_my_device_session(p_device_id,p_session_token);return query select r.id,r.machine_brand,r.machine_model,r.part_name,r.requested_qty,r.dealer_message,r.status,r.reply_text,r.created_at from missing_part_requests r where r.dealer_id=v_dealer_id order by r.created_at desc limit 20;end;$$;

-- Remove legacy authenticated signatures so direct calls cannot bypass device binding.
drop function if exists public.dealer_my_profile();drop function if exists public.dealer_create_missing_part_request(text,text,text,numeric,text,text);drop function if exists public.dealer_my_missing_part_requests();
revoke all on function public.dealer_my_profile(text,text) from public,anon;grant execute on function public.dealer_my_profile(text,text) to authenticated;
revoke all on function public.dealer_create_missing_part_request(text,text,text,text,text,numeric,text,text) from public,anon;grant execute on function public.dealer_create_missing_part_request(text,text,text,text,text,numeric,text,text) to authenticated;
revoke all on function public.dealer_my_missing_part_requests(text,text) from public,anon;grant execute on function public.dealer_my_missing_part_requests(text,text) to authenticated;
