-- TORVO V2 explicit dealer identity. Removes mobile-number joins from the authorization boundary.
alter table app_users add column if not exists dealer_id uuid references dealers(id);
create unique index if not exists app_users_dealer_id_unique on app_users(dealer_id) where dealer_id is not null;
-- Safe one-time migration for existing dealer users only when the mobile match is unambiguous.
update app_users u set dealer_id=d.id from dealers d where u.role='dealer' and u.dealer_id is null and u.mobile is not null and d.mobile=u.mobile and d.status='approved' and (select count(*) from dealers x where x.mobile=u.mobile and x.status='approved')=1;
create or replace function current_dealer_id() returns uuid language sql stable security definer set search_path=public as $$select dealer_id from app_users where auth_user_id=auth.uid() and active=true and role='dealer' limit 1$$;
revoke all on function current_dealer_id() from public,anon;grant execute on function current_dealer_id() to authenticated;
create or replace function link_dealer_user(p_user uuid,p_dealer uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;u app_users%rowtype;d dealers%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if nullif(trim(p_reason),'') is null then raise exception 'Reason required';end if;select * into u from app_users where id=p_user for update;if not found or u.role<>'dealer' then raise exception 'Target must be a dealer user';end if;select * into d from dealers where id=p_dealer and status='approved';if not found then raise exception 'Approved dealer required';end if;update app_users set dealer_id=p_dealer where id=p_user;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'DEALER_USER_LINKED','app_user',p_user::text,jsonb_build_object('dealer_id',p_dealer,'dealer_code',d.dealer_code,'reason',trim(p_reason)));end;$$;
revoke all on function link_dealer_user(uuid,uuid,text) from public,anon;grant execute on function link_dealer_user(uuid,uuid,text) to authenticated;
