-- TORVO V2 DEALER SERVICE / REPAIR BOOK
-- Private dealer operational utility. Install after dealer device session + catalog/rates.
create table if not exists dealer_service_jobs(
 id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id) on delete restrict,
 customer_name text not null,mobile text,whatsapp text,address text,machine_photo_url text not null,
 machine_brand text not null,machine_type text,machine_model text,serial_no text,complaint_code text not null,complaint_note text,
 status text not null default 'in_shop' check(status in('in_shop','repairing','ready','delivered','cancelled')),
 token_no bigint generated always as identity,repair_charge numeric not null default 0 check(repair_charge>=0),
 machine_in_at timestamptz not null default now(),ready_at timestamptz,delivered_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists dealer_service_job_parts(
 id uuid primary key default gen_random_uuid(),job_id uuid not null references dealer_service_jobs(id) on delete cascade,
 item_id uuid not null references catalog_items(id) on delete restrict,qty numeric not null check(qty>0 and qty=trunc(qty) and qty<=9999),
 dealer_rate_snapshot numeric not null check(dealer_rate_snapshot>=0),selling_rate numeric not null check(selling_rate>=0),created_at timestamptz not null default now(),unique(job_id,item_id)
);
alter table dealer_service_jobs enable row level security;alter table dealer_service_job_parts enable row level security;
revoke all on dealer_service_jobs,dealer_service_job_parts from public,anon,authenticated;

create or replace function dealer_service_jobs_read(p_device_id text,p_session_token text,p_status text default null,p_limit integer default 100)
returns table(id uuid,token_no bigint,customer_name text,mobile text,whatsapp text,address text,machine_photo_url text,machine_brand text,machine_type text,machine_model text,serial_no text,complaint_code text,complaint_note text,status text,repair_charge numeric,machine_in_at timestamptz,ready_at timestamptz,delivered_at timestamptz)
language plpgsql security definer set search_path=public as $$declare did uuid;s text:=lower(trim(coalesce(p_status,'')));lim integer:=least(greatest(coalesce(p_limit,100),1),300);begin
 if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);if s<>'' and s not in('in_shop','repairing','ready','delivered','cancelled')then raise exception 'INVALID SERVICE STATUS';end if;
 return query select j.id,j.token_no,j.customer_name,j.mobile,j.whatsapp,j.address,j.machine_photo_url,j.machine_brand,j.machine_type,j.machine_model,j.serial_no,j.complaint_code,j.complaint_note,j.status,j.repair_charge,j.machine_in_at,j.ready_at,j.delivered_at from dealer_service_jobs j where j.dealer_id=did and(s='' or j.status=s)order by j.machine_in_at desc limit lim;end$$;

create or replace function dealer_service_job_create(p_device_id text,p_session_token text,p_customer_name text,p_mobile text,p_whatsapp text,p_address text,p_machine_photo_url text,p_machine_brand text,p_machine_type text,p_machine_model text,p_serial_no text,p_complaint_code text,p_complaint_note text)
returns uuid language plpgsql security definer set search_path=public as $$declare did uuid;jid uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);
 if length(trim(coalesce(p_customer_name,'')))<2 then raise exception 'CUSTOMER NAME REQUIRED';end if;if nullif(trim(coalesce(p_mobile,'')),'') is not null and regexp_replace(p_mobile,'[^0-9]','','g') !~ '^(91)?[0-9]{10}$' then raise exception 'INVALID CUSTOMER MOBILE';end if;if nullif(trim(coalesce(p_whatsapp,'')),'') is not null and regexp_replace(p_whatsapp,'[^0-9]','','g') !~ '^(91)?[0-9]{10}$' then raise exception 'INVALID CUSTOMER WHATSAPP';end if;if length(trim(coalesce(p_machine_photo_url,'')))<4 then raise exception 'ORIGINAL MACHINE PHOTO REQUIRED';end if;if length(trim(coalesce(p_machine_brand,'')))<1 then raise exception 'MACHINE BRAND REQUIRED';end if;if length(trim(coalesce(p_complaint_code,'')))<2 then raise exception 'COMPLAINT REQUIRED';end if;
 insert into dealer_service_jobs(dealer_id,customer_name,mobile,whatsapp,address,machine_photo_url,machine_brand,machine_type,machine_model,serial_no,complaint_code,complaint_note)
 values(did,left(trim(p_customer_name),120),nullif(left(trim(coalesce(p_mobile,'')),20),''),nullif(left(trim(coalesce(p_whatsapp,'')),20),''),nullif(left(trim(coalesce(p_address,'')),300),''),left(trim(p_machine_photo_url),1000),left(trim(p_machine_brand),100),nullif(left(trim(coalesce(p_machine_type,'')),100),''),nullif(left(trim(coalesce(p_machine_model,'')),120),''),nullif(left(trim(coalesce(p_serial_no,'')),120),''),left(upper(trim(p_complaint_code)),100),nullif(left(trim(coalesce(p_complaint_note,'')),1000),''))returning id into jid;return jid;end$$;

create or replace function dealer_service_job_add_part(p_device_id text,p_session_token text,p_job_id uuid,p_item_id uuid,p_qty integer,p_selling_rate numeric)
returns uuid language plpgsql security definer set search_path=public as $$declare did uuid;rg text;r numeric;pid uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);perform 1 from dealer_service_jobs where id=p_job_id and dealer_id=did and status in('in_shop','repairing') for update;if not found then raise exception 'ACTIVE SERVICE JOB NOT FOUND';end if;if p_qty<1 or p_qty>9999 then raise exception 'INVALID QUANTITY';end if;perform 1 from catalog_items where id=p_item_id and active=true;if not found then raise exception 'CATALOG ITEM UNAVAILABLE';end if;select rate_group into rg from dealers where id=did and status='approved';select selling_rate into r from item_rates where item_id=p_item_id and rate_group=rg and min_qty<=p_qty order by min_qty desc limit 1;if r is null then raise exception 'DEALER RATE UNAVAILABLE';end if;if p_selling_rate is null or p_selling_rate<0 then raise exception 'SELLING RATE REQUIRED';end if;
 insert into dealer_service_job_parts(job_id,item_id,qty,dealer_rate_snapshot,selling_rate)values(p_job_id,p_item_id,p_qty,r,p_selling_rate)on conflict(job_id,item_id)do update set qty=excluded.qty,dealer_rate_snapshot=excluded.dealer_rate_snapshot,selling_rate=excluded.selling_rate returning id into pid;update dealer_service_jobs set status='repairing',updated_at=now() where id=p_job_id;return pid;end$$;

create or replace function dealer_service_job_parts_read(p_device_id text,p_session_token text,p_job_id uuid)
returns table(id uuid,item_id uuid,item_code text,item_name text,qty numeric,dealer_rate numeric,selling_rate numeric,line_total numeric)language plpgsql security definer set search_path=public as $$declare did uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);perform 1 from dealer_service_jobs where id=p_job_id and dealer_id=did;if not found then raise exception 'SERVICE JOB NOT FOUND';end if;return query select p.id,p.item_id,c.item_code,c.name,p.qty,p.dealer_rate_snapshot,p.selling_rate,round(p.qty*p.selling_rate,2)from dealer_service_job_parts p join catalog_items c on c.id=p.item_id where p.job_id=p_job_id order by p.created_at;end$$;

create or replace function dealer_service_job_set_status(p_device_id text,p_session_token text,p_job_id uuid,p_status text,p_repair_charge numeric default 0)
returns boolean language plpgsql security definer set search_path=public as $$declare did uuid;s text:=lower(trim(coalesce(p_status,'')));begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);if s not in('in_shop','repairing','ready','delivered','cancelled')then raise exception 'INVALID SERVICE STATUS';end if;if coalesce(p_repair_charge,0)<0 then raise exception 'INVALID REPAIR CHARGE';end if;update dealer_service_jobs set status=s,repair_charge=coalesce(p_repair_charge,0),ready_at=case when s='ready' then coalesce(ready_at,now())else ready_at end,delivered_at=case when s='delivered' then coalesce(delivered_at,now())else delivered_at end,updated_at=now() where id=p_job_id and dealer_id=did;if not found then raise exception 'SERVICE JOB NOT FOUND';end if;return true;end$$;
revoke all on function dealer_service_jobs_read(text,text,text,integer),dealer_service_job_create(text,text,text,text,text,text,text,text,text,text,text,text,text),dealer_service_job_add_part(text,text,uuid,uuid,integer,numeric),dealer_service_job_parts_read(text,text,uuid),dealer_service_job_set_status(text,text,uuid,text,numeric) from public,anon;
grant execute on function dealer_service_jobs_read(text,text,text,integer),dealer_service_job_create(text,text,text,text,text,text,text,text,text,text,text,text,text),dealer_service_job_add_part(text,text,uuid,uuid,integer,numeric),dealer_service_job_parts_read(text,text,uuid),dealer_service_job_set_status(text,text,uuid,text,numeric) to authenticated;
 then raise exception 'INVALID CUSTOMER MOBILE';end if;if nullif(trim(coalesce(p_whatsapp,'')),'') is not null and regexp_replace(p_whatsapp,'[^0-9]','','g') !~ '^(91)?[0-9]{10} then raise exception 'ORIGINAL MACHINE PHOTO REQUIRED';end if;if length(trim(coalesce(p_machine_brand,'')))<1 then raise exception 'MACHINE BRAND REQUIRED';end if;if length(trim(coalesce(p_complaint_code,'')))<2 then raise exception 'COMPLAINT REQUIRED';end if;
 insert into dealer_service_jobs(dealer_id,customer_name,mobile,whatsapp,address,machine_photo_url,machine_brand,machine_type,machine_model,serial_no,complaint_code,complaint_note)
 values(did,left(trim(p_customer_name),120),nullif(left(trim(coalesce(p_mobile,'')),20),''),nullif(left(trim(coalesce(p_whatsapp,'')),20),''),nullif(left(trim(coalesce(p_address,'')),300),''),left(trim(p_machine_photo_url),1000),left(trim(p_machine_brand),100),nullif(left(trim(coalesce(p_machine_type,'')),100),''),nullif(left(trim(coalesce(p_machine_model,'')),120),''),nullif(left(trim(coalesce(p_serial_no,'')),120),''),left(upper(trim(p_complaint_code)),100),nullif(left(trim(coalesce(p_complaint_note,'')),1000),''))returning id into jid;return jid;end$$;

create or replace function dealer_service_job_add_part(p_device_id text,p_session_token text,p_job_id uuid,p_item_id uuid,p_qty integer,p_selling_rate numeric)
returns uuid language plpgsql security definer set search_path=public as $$declare did uuid;rg text;r numeric;pid uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);perform 1 from dealer_service_jobs where id=p_job_id and dealer_id=did and status in('in_shop','repairing') for update;if not found then raise exception 'ACTIVE SERVICE JOB NOT FOUND';end if;if p_qty<1 or p_qty>9999 then raise exception 'INVALID QUANTITY';end if;perform 1 from catalog_items where id=p_item_id and active=true;if not found then raise exception 'CATALOG ITEM UNAVAILABLE';end if;select rate_group into rg from dealers where id=did and status='approved';select selling_rate into r from item_rates where item_id=p_item_id and rate_group=rg and min_qty<=p_qty order by min_qty desc limit 1;if r is null then raise exception 'DEALER RATE UNAVAILABLE';end if;if p_selling_rate is null or p_selling_rate<0 then raise exception 'SELLING RATE REQUIRED';end if;
 insert into dealer_service_job_parts(job_id,item_id,qty,dealer_rate_snapshot,selling_rate)values(p_job_id,p_item_id,p_qty,r,p_selling_rate)on conflict(job_id,item_id)do update set qty=excluded.qty,dealer_rate_snapshot=excluded.dealer_rate_snapshot,selling_rate=excluded.selling_rate returning id into pid;update dealer_service_jobs set status='repairing',updated_at=now() where id=p_job_id;return pid;end$$;

create or replace function dealer_service_job_parts_read(p_device_id text,p_session_token text,p_job_id uuid)
returns table(id uuid,item_id uuid,item_code text,item_name text,qty numeric,dealer_rate numeric,selling_rate numeric,line_total numeric)language plpgsql security definer set search_path=public as $$declare did uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);perform 1 from dealer_service_jobs where id=p_job_id and dealer_id=did;if not found then raise exception 'SERVICE JOB NOT FOUND';end if;return query select p.id,p.item_id,c.item_code,c.name,p.qty,p.dealer_rate_snapshot,p.selling_rate,round(p.qty*p.selling_rate,2)from dealer_service_job_parts p join catalog_items c on c.id=p.item_id where p.job_id=p_job_id order by p.created_at;end$$;

create or replace function dealer_service_job_set_status(p_device_id text,p_session_token text,p_job_id uuid,p_status text,p_repair_charge numeric default 0)
returns boolean language plpgsql security definer set search_path=public as $$declare did uuid;s text:=lower(trim(coalesce(p_status,'')));begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);if s not in('in_shop','repairing','ready','delivered','cancelled')then raise exception 'INVALID SERVICE STATUS';end if;if coalesce(p_repair_charge,0)<0 then raise exception 'INVALID REPAIR CHARGE';end if;update dealer_service_jobs set status=s,repair_charge=coalesce(p_repair_charge,0),ready_at=case when s='ready' then coalesce(ready_at,now())else ready_at end,delivered_at=case when s='delivered' then coalesce(delivered_at,now())else delivered_at end,updated_at=now() where id=p_job_id and dealer_id=did;if not found then raise exception 'SERVICE JOB NOT FOUND';end if;return true;end$$;
revoke all on function dealer_service_jobs_read(text,text,text,integer),dealer_service_job_create(text,text,text,text,text,text,text,text,text,text,text,text,text),dealer_service_job_add_part(text,text,uuid,uuid,integer,numeric),dealer_service_job_parts_read(text,text,uuid),dealer_service_job_set_status(text,text,uuid,text,numeric) from public,anon;
grant execute on function dealer_service_jobs_read(text,text,text,integer),dealer_service_job_create(text,text,text,text,text,text,text,text,text,text,text,text,text),dealer_service_job_add_part(text,text,uuid,uuid,integer,numeric),dealer_service_job_parts_read(text,text,uuid),dealer_service_job_set_status(text,text,uuid,text,numeric) to authenticated;
 then raise exception 'INVALID CUSTOMER WHATSAPP';end if;if length(trim(coalesce(p_machine_photo_url,'')))<4 then raise exception 'ORIGINAL MACHINE PHOTO REQUIRED';end if;if length(trim(coalesce(p_machine_brand,'')))<1 then raise exception 'MACHINE BRAND REQUIRED';end if;if length(trim(coalesce(p_complaint_code,'')))<2 then raise exception 'COMPLAINT REQUIRED';end if;
 insert into dealer_service_jobs(dealer_id,customer_name,mobile,whatsapp,address,machine_photo_url,machine_brand,machine_type,machine_model,serial_no,complaint_code,complaint_note)
 values(did,left(trim(p_customer_name),120),nullif(left(trim(coalesce(p_mobile,'')),20),''),nullif(left(trim(coalesce(p_whatsapp,'')),20),''),nullif(left(trim(coalesce(p_address,'')),300),''),left(trim(p_machine_photo_url),1000),left(trim(p_machine_brand),100),nullif(left(trim(coalesce(p_machine_type,'')),100),''),nullif(left(trim(coalesce(p_machine_model,'')),120),''),nullif(left(trim(coalesce(p_serial_no,'')),120),''),left(upper(trim(p_complaint_code)),100),nullif(left(trim(coalesce(p_complaint_note,'')),1000),''))returning id into jid;return jid;end$$;

create or replace function dealer_service_job_add_part(p_device_id text,p_session_token text,p_job_id uuid,p_item_id uuid,p_qty integer,p_selling_rate numeric)
returns uuid language plpgsql security definer set search_path=public as $$declare did uuid;rg text;r numeric;pid uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);perform 1 from dealer_service_jobs where id=p_job_id and dealer_id=did and status in('in_shop','repairing') for update;if not found then raise exception 'ACTIVE SERVICE JOB NOT FOUND';end if;if p_qty<1 or p_qty>9999 then raise exception 'INVALID QUANTITY';end if;perform 1 from catalog_items where id=p_item_id and active=true;if not found then raise exception 'CATALOG ITEM UNAVAILABLE';end if;select rate_group into rg from dealers where id=did and status='approved';select selling_rate into r from item_rates where item_id=p_item_id and rate_group=rg and min_qty<=p_qty order by min_qty desc limit 1;if r is null then raise exception 'DEALER RATE UNAVAILABLE';end if;if p_selling_rate is null or p_selling_rate<0 then raise exception 'SELLING RATE REQUIRED';end if;
 insert into dealer_service_job_parts(job_id,item_id,qty,dealer_rate_snapshot,selling_rate)values(p_job_id,p_item_id,p_qty,r,p_selling_rate)on conflict(job_id,item_id)do update set qty=excluded.qty,dealer_rate_snapshot=excluded.dealer_rate_snapshot,selling_rate=excluded.selling_rate returning id into pid;update dealer_service_jobs set status='repairing',updated_at=now() where id=p_job_id;return pid;end$$;

create or replace function dealer_service_job_parts_read(p_device_id text,p_session_token text,p_job_id uuid)
returns table(id uuid,item_id uuid,item_code text,item_name text,qty numeric,dealer_rate numeric,selling_rate numeric,line_total numeric)language plpgsql security definer set search_path=public as $$declare did uuid;begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);perform 1 from dealer_service_jobs where id=p_job_id and dealer_id=did;if not found then raise exception 'SERVICE JOB NOT FOUND';end if;return query select p.id,p.item_id,c.item_code,c.name,p.qty,p.dealer_rate_snapshot,p.selling_rate,round(p.qty*p.selling_rate,2)from dealer_service_job_parts p join catalog_items c on c.id=p.item_id where p.job_id=p_job_id order by p.created_at;end$$;

create or replace function dealer_service_job_set_status(p_device_id text,p_session_token text,p_job_id uuid,p_status text,p_repair_charge numeric default 0)
returns boolean language plpgsql security definer set search_path=public as $$declare did uuid;s text:=lower(trim(coalesce(p_status,'')));begin if auth.uid() is null then raise exception 'AUTHENTICATED DEALER REQUIRED';end if;did:=dealer_assert_my_device_session(p_device_id,p_session_token);if s not in('in_shop','repairing','ready','delivered','cancelled')then raise exception 'INVALID SERVICE STATUS';end if;if coalesce(p_repair_charge,0)<0 then raise exception 'INVALID REPAIR CHARGE';end if;update dealer_service_jobs set status=s,repair_charge=coalesce(p_repair_charge,0),ready_at=case when s='ready' then coalesce(ready_at,now())else ready_at end,delivered_at=case when s='delivered' then coalesce(delivered_at,now())else delivered_at end,updated_at=now() where id=p_job_id and dealer_id=did;if not found then raise exception 'SERVICE JOB NOT FOUND';end if;return true;end$$;
revoke all on function dealer_service_jobs_read(text,text,text,integer),dealer_service_job_create(text,text,text,text,text,text,text,text,text,text,text,text,text),dealer_service_job_add_part(text,text,uuid,uuid,integer,numeric),dealer_service_job_parts_read(text,text,uuid),dealer_service_job_set_status(text,text,uuid,text,numeric) from public,anon;
grant execute on function dealer_service_jobs_read(text,text,text,integer),dealer_service_job_create(text,text,text,text,text,text,text,text,text,text,text,text,text),dealer_service_job_add_part(text,text,uuid,uuid,integer,numeric),dealer_service_job_parts_read(text,text,uuid),dealer_service_job_set_status(text,text,uuid,text,numeric) to authenticated;
