-- TORVO V2 DEALER TARGET REWARDS
-- FINAL RULE: NO PER-INVOICE POINTS. ELIGIBLE PURCHASE VALUE REACHES ADMIN TARGET SLABS -> POINTS -> GIFT/VOUCHER.
create table if not exists dealer_target_types(id uuid primary key default gen_random_uuid(),name text not null unique,scheme_start_month int not null default 4 check(scheme_start_month between 1 and 12),active boolean not null default true,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists dealer_target_slabs(id uuid primary key default gen_random_uuid(),target_type_id uuid not null references dealer_target_types(id) on delete restrict,target_value numeric(14,2) not null check(target_value>0),points int not null check(points>0),active boolean not null default true,unique(target_type_id,target_value));
create table if not exists dealer_target_assignments(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id) on delete restrict,target_type_id uuid not null references dealer_target_types(id) on delete restrict,scheme_year int not null check(scheme_year between 2020 and 2100),active boolean not null default true,assigned_by uuid references app_users(id),unique(dealer_id,scheme_year));
create table if not exists dealer_reward_catalog(id uuid primary key default gen_random_uuid(),name text not null,points_required int not null check(points_required>0),gift_value numeric(12,2) check(gift_value>=0),redemption_type text not null check(redemption_type in('gift','voucher')),active boolean not null default true,sort_order int not null default 100,created_by uuid references app_users(id));
create table if not exists dealer_reward_points_ledger(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id),scheme_year int not null,points int not null,entry_type text not null check(entry_type in('target_earned','claim_debit','claim_reversal','admin_adjustment')),reference_id uuid,note text,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists dealer_reward_claims(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id),scheme_year int not null,reward_id uuid not null references dealer_reward_catalog(id),points_used int not null check(points_used>0),status text not null default 'requested' check(status in('requested','approved','issued','cancelled')),voucher_provider text check(voucher_provider in('AMAZON','FLIPKART') or voucher_provider is null),voucher_code text,requested_at timestamptz not null default now(),approved_by uuid references app_users(id),approved_at timestamptz,issued_at timestamptz);
alter table dealer_target_types enable row level security;alter table dealer_target_slabs enable row level security;alter table dealer_target_assignments enable row level security;alter table dealer_reward_catalog enable row level security;alter table dealer_reward_points_ledger enable row level security;alter table dealer_reward_claims enable row level security;revoke all on dealer_target_types,dealer_target_slabs,dealer_target_assignments,dealer_reward_catalog,dealer_reward_points_ledger,dealer_reward_claims from anon,authenticated;
create or replace function reward_scheme_year() returns int language sql stable set search_path=public as $select case when extract(month from current_date)>=4 then extract(year from current_date)::int else extract(year from current_date)::int-1 end$;
create or replace function reward_current_dealer() returns uuid language plpgsql security definer set search_path=public as $$declare d uuid;begin select dealer_id into d from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if d is null then raise exception 'DEALER APP LOGIN REQUIRED';end if;return d;end$$;
create or replace function dealer_reward_balance() returns int language sql security definer set search_path=public as $$select coalesce(sum(points),0)::int from dealer_reward_points_ledger where dealer_id=reward_current_dealer() and scheme_year=reward_scheme_year()$$;
create or replace function dealer_reward_options() returns table(id uuid,name text,points_required int,gift_value numeric,redemption_type text,available boolean) language plpgsql security definer set search_path=public as $$declare b int;begin b:=dealer_reward_balance();return query select r.id,r.name,r.points_required,r.gift_value,r.redemption_type,(b>=r.points_required) from dealer_reward_catalog r where r.active=true order by r.points_required,r.sort_order;end$$;
create or replace function dealer_reward_progress() returns table(scheme_year int,target_name text,current_points int,next_points int,points_remaining int) language sql security definer set search_path=public as $$with me as(select reward_current_dealer() d,reward_scheme_year() y),a as(select t.name from dealer_target_assignments x join dealer_target_types t on t.id=x.target_type_id,me where x.dealer_id=me.d and x.scheme_year=me.y and x.active=true),b as(select dealer_reward_balance() p),n as(select min(points_required) p from dealer_reward_catalog,b where active=true and points_required>b.p) select me.y,coalesce((select name from a),'STANDARD TARGET'),b.p,coalesce(n.p,b.p),greatest(coalesce(n.p,b.p)-b.p,0) from me,b,n$$;
create or replace function dealer_reward_claim_history() returns table(id uuid,reward_name text,points_used int,status text,voucher_provider text,requested_at timestamptz,issued_at timestamptz) language sql security definer set search_path=public as $$select c.id,r.name,c.points_used,c.status,c.voucher_provider,c.requested_at,c.issued_at from dealer_reward_claims c join dealer_reward_catalog r on r.id=c.reward_id where c.dealer_id=reward_current_dealer() order by c.requested_at desc limit 50$$;
create or replace function dealer_claim_reward(p_reward uuid) returns uuid language plpgsql security definer set search_path=public as $$declare d uuid:=reward_current_dealer();y int:=reward_scheme_year();b int;r dealer_reward_catalog%rowtype;c uuid;begin select * into r from dealer_reward_catalog where id=p_reward and active=true;if not found then raise exception 'REWARD NOT AVAILABLE';end if;b:=dealer_reward_balance();if b<r.points_required then raise exception 'NOT ENOUGH POINTS';end if;insert into dealer_reward_claims(dealer_id,scheme_year,reward_id,points_used)values(d,y,r.id,r.points_required)returning id into c;insert into dealer_reward_points_ledger(dealer_id,scheme_year,points,entry_type,reference_id,note)values(d,y,-r.points_required,'claim_debit',c,'DEALER REWARD CLAIM');return c;end$$;
create or replace function reward_admin_user() returns uuid language plpgsql security definer set search_path=public as $$declare a uuid;begin select id into a from app_users where auth_user_id=auth.uid() and active=true and role in('owner','admin');if a is null then raise exception 'OWNER OR ADMIN REQUIRED';end if;return a;end$$;
create or replace function admin_save_dealer_target_type(p_name text,p_start_month int default 4) returns uuid language plpgsql security definer set search_path=public as $$declare a uuid:=reward_admin_user();x uuid;begin if nullif(btrim(p_name),'') is null or p_start_month not between 1 and 12 then raise exception 'VALID TARGET TYPE REQUIRED';end if;insert into dealer_target_types(name,scheme_start_month,created_by)values(upper(btrim(p_name)),p_start_month,a)on conflict(name)do update set scheme_start_month=excluded.scheme_start_month,active=true returning id into x;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a,'DEALER_TARGET_TYPE_SAVED','DEALER_TARGET_TYPE',x::text,jsonb_build_object('start_month',p_start_month));return x;end$$;
create or replace function admin_save_dealer_target_slab(p_target_type uuid,p_target_value numeric,p_points int) returns uuid language plpgsql security definer set search_path=public as $$declare a uuid:=reward_admin_user();x uuid;begin if p_target_value<=0 or p_points<=0 then raise exception 'POSITIVE TARGET AND POINTS REQUIRED';end if;insert into dealer_target_slabs(target_type_id,target_value,points)values(p_target_type,p_target_value,p_points)on conflict(target_type_id,target_value)do update set points=excluded.points,active=true returning id into x;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a,'DEALER_TARGET_SLAB_SAVED','DEALER_TARGET_SLAB',x::text,jsonb_build_object('target_value',p_target_value,'points',p_points));return x;end$$;
create or replace function admin_assign_dealer_target(p_dealer uuid,p_target_type uuid,p_scheme_year int) returns uuid language plpgsql security definer set search_path=public as $$declare a uuid:=reward_admin_user();x uuid;begin if p_scheme_year not between 2020 and 2100 or not exists(select 1 from dealers where id=p_dealer and status='approved')then raise exception 'VALID APPROVED DEALER AND YEAR REQUIRED';end if;insert into dealer_target_assignments(dealer_id,target_type_id,scheme_year,assigned_by)values(p_dealer,p_target_type,p_scheme_year,a)on conflict(dealer_id,scheme_year)do update set target_type_id=excluded.target_type_id,active=true,assigned_by=a returning id into x;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a,'DEALER_TARGET_ASSIGNED','DEALER_TARGET_ASSIGNMENT',x::text,jsonb_build_object('dealer_id',p_dealer,'scheme_year',p_scheme_year));return x;end$$;
create or replace function admin_save_dealer_reward_option(p_name text,p_points int,p_gift_value numeric,p_redemption_type text) returns uuid language plpgsql security definer set search_path=public as $$declare a uuid:=reward_admin_user();x uuid;begin if nullif(btrim(p_name),'') is null or p_points<=0 or p_gift_value<0 or lower(p_redemption_type) not in('gift','voucher')then raise exception 'VALID REWARD REQUIRED';end if;insert into dealer_reward_catalog(name,points_required,gift_value,redemption_type,created_by)values(upper(btrim(p_name)),p_points,p_gift_value,lower(p_redemption_type),a)returning id into x;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a,'DEALER_REWARD_OPTION_CREATED','DEALER_REWARD',x::text,jsonb_build_object('points',p_points,'type',lower(p_redemption_type)));return x;end$$;
create or replace function admin_issue_reward_voucher(p_claim uuid,p_provider text,p_code text) returns boolean language plpgsql security definer set search_path=public as $$declare u uuid:=reward_admin_user();c dealer_reward_claims%rowtype;begin if upper(p_provider) not in('AMAZON','FLIPKART') or nullif(btrim(p_code),'') is null then raise exception 'VALID VOUCHER REQUIRED';end if;select * into c from dealer_reward_claims where id=p_claim for update;if not found or c.status not in('requested','approved')then raise exception 'CLAIM NOT READY';end if;update dealer_reward_claims set status='issued',voucher_provider=upper(p_provider),voucher_code=btrim(p_code),approved_by=coalesce(approved_by,u),approved_at=coalesce(approved_at,now()),issued_at=now() where id=p_claim;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(u,'DEALER_REWARD_VOUCHER_ISSUED','REWARD_CLAIM',p_claim::text,jsonb_build_object('provider',upper(p_provider)));return true;end$$;
revoke all on function reward_scheme_year(),reward_current_dealer(),dealer_reward_balance(),dealer_reward_options(),dealer_reward_progress(),dealer_reward_claim_history(),dealer_claim_reward(uuid),reward_admin_user(),admin_save_dealer_target_type(text,int),admin_save_dealer_target_slab(uuid,numeric,int),admin_assign_dealer_target(uuid,uuid,int),admin_save_dealer_reward_option(text,int,numeric,text),admin_issue_reward_voucher(uuid,text,text) from public,anon;
grant execute on function dealer_reward_balance(),dealer_reward_options(),dealer_reward_progress(),dealer_reward_claim_history(),dealer_claim_reward(uuid),admin_save_dealer_target_type(text,int),admin_save_dealer_target_slab(uuid,numeric,int),admin_assign_dealer_target(uuid,uuid,int),admin_save_dealer_reward_option(text,int,numeric,text),admin_issue_reward_voucher(uuid,text,text) to authenticated;
