-- TORVO V2 extended operational modules
create table if not exists dealer_request_history(id bigint generated always as identity primary key,dealer_id uuid not null references dealers(id),action text not null,reason text,actor_id uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists stock_reorder_requests(id uuid primary key default gen_random_uuid(),item_id uuid not null references catalog_items(id),required_qty numeric not null check(required_qty>0),status text not null default 'submitted' check(status in('submitted','ordered','received','cancelled')),submitted_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists schemes(id uuid primary key default gen_random_uuid(),name text not null,start_date date not null,end_date date not null,status text not null default 'draft' check(status in('draft','active','closed')),rules jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists scheme_slabs(id uuid primary key default gen_random_uuid(),scheme_id uuid not null references schemes(id) on delete cascade,min_value numeric not null,max_value numeric,gift_name text,points numeric not null default 0);
create table if not exists dealer_scheme_progress(id uuid primary key default gen_random_uuid(),scheme_id uuid not null references schemes(id),dealer_id uuid not null references dealers(id),progress_value numeric not null default 0,achieved_slab_id uuid references scheme_slabs(id),unique(scheme_id,dealer_id));
create table if not exists reward_ledger(id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id),points numeric not null,reason text not null,expires_at timestamptz,created_at timestamptz not null default now());
create table if not exists non_available_requests(id uuid primary key default gen_random_uuid(),dealer_id uuid references dealers(id),search_text text not null,item_type text,qty numeric,status text not null default 'open' check(status in('open','reviewing','sourced','closed')),created_at timestamptz not null default now());
create table if not exists messages(id uuid primary key default gen_random_uuid(),dealer_id uuid references dealers(id),sender_id uuid references app_users(id),subject text,body text not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references app_users(id),kind text not null,title text not null,body text,entity_type text,entity_id text,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists app_settings(key text primary key,value jsonb not null default '{}'::jsonb,updated_by uuid references app_users(id),updated_at timestamptz not null default now());
create index if not exists idx_dealers_status on dealers(status);create index if not exists idx_catalog_type on catalog_items(item_type);create index if not exists idx_docs_type_status on sales_documents(doc_type,status);create index if not exists idx_notifications_user_unread on notifications(user_id,read_at);create index if not exists idx_audit_created on audit_log(created_at desc);
