-- TORVO V2 PRIVATE SUITABLE KNOWLEDGE / DEALER FITMENT SUGGESTIONS
-- Dealer fitment/identification suggestions NEVER earn TORVO Points. TORVO Points belong to eligible sales only.
-- Dealer submissions are private from other dealers. Admin verification is mandatory before private suitable promotion.
-- This migration is safe for a fresh V2 database and also removes obsolete knowledge-reward columns from an earlier V2 draft.

create table if not exists knowledge_challenges(id uuid primary key default gen_random_uuid(),challenge_type text not null check(challenge_type in('known_part_fitment','mystery_part_photo')),item_id uuid references catalog_items(id) on delete restrict,title text not null,instructions text,photo_urls jsonb not null default '[]'::jsonb,active boolean not null default true,starts_at timestamptz,ends_at timestamptz,created_by uuid references app_users(id) on delete restrict,created_at timestamptz not null default now());
create table if not exists knowledge_submissions(id uuid primary key default gen_random_uuid(),challenge_id uuid not null references knowledge_challenges(id) on delete restrict,dealer_id uuid not null references dealers(id) on delete restrict,suggested_part_name text,machine_brand text,machine_type text,machine_model text,notes text,evidence_photo_urls jsonb not null default '[]'::jsonb,status text not null default 'pending' check(status in('pending','verified','partly_correct','rejected','duplicate')),admin_note text,verified_by uuid references app_users(id) on delete restrict,verified_at timestamptz,created_at timestamptz not null default now());
create table if not exists knowledge_verified_fitments(id uuid primary key default gen_random_uuid(),submission_id uuid not null unique references knowledge_submissions(id) on delete restrict,item_id uuid references catalog_items(id) on delete restrict,machine_brand text not null,machine_type text,machine_model text not null,confidence_count integer not null default 1 check(confidence_count>0),suitable_mapping_id uuid references suitable_mappings(id) on delete restrict,approved_by uuid not null references app_users(id) on delete restrict,approved_at timestamptz not null default now());

-- Compatibility cutover from the retired Knowledge Rewards draft.
-- These columns were never part of the final business rule and can otherwise keep old NOT NULL constraints alive.
alter table knowledge_challenges drop column if exists points_per_verified_answer;
alter table knowledge_challenges drop column if exists reward_policy;
alter table knowledge_submissions drop column if exists approved_points;

-- Remove obsolete knowledge-only point ledger if it exists. This is NOT the separate sales reward_ledger.
drop table if exists knowledge_point_ledger;

create index if not exists idx_knowledge_submission_admin on knowledge_submissions(status,created_at desc);
create index if not exists idx_knowledge_submission_dealer on knowledge_submissions(dealer_id,created_at desc);

-- Direct table access is private. Dealer access is only through scoped security-definer RPCs below.
alter table knowledge_challenges enable row level security;
alter table knowledge_submissions enable row level security;
alter table knowledge_verified_fitments enable row level security;
revoke all on table knowledge_challenges,knowledge_submissions,knowledge_verified_fitments from anon,authenticated;

-- Owner/Admin may use the Admin workspace direct reads; all mutations still go through audited RPCs.
drop policy if exists knowledge_challenges_admin_read on knowledge_challenges;
create policy knowledge_challenges_admin_read on knowledge_challenges for select to authenticated using(exists(select 1 from app_users u where u.auth_user_id=auth.uid() and u.active=true and u.role in('owner','admin')));
drop policy if exists knowledge_submissions_admin_read on knowledge_submissions;
create policy knowledge_submissions_admin_read on knowledge_submissions for select to authenticated using(exists(select 1 from app_users u where u.auth_user_id=auth.uid() and u.active=true and u.role in('owner','admin')));
drop policy if exists knowledge_verified_fitments_admin_read on knowledge_verified_fitments;
create policy knowledge_verified_fitments_admin_read on knowledge_verified_fitments for select to authenticated using(exists(select 1 from app_users u where u.auth_user_id=auth.uid() and u.active=true and u.role in('owner','admin')));
grant select on table knowledge_challenges,knowledge_submissions,knowledge_verified_fitments to authenticated;

create or replace function dealer_knowledge_challenges() returns table(id uuid,challenge_type text,item_id uuid,title text,instructions text,photo_urls jsonb,starts_at timestamptz,ends_at timestamptz,item_code text,item_name text) language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from app_users where auth_user_id=auth.uid() and active=true and role='dealer' and dealer_id is not null) then raise exception 'Linked dealer login required';end if;return query select c.id,c.challenge_type,c.item_id,c.title,c.instructions,c.photo_urls,c.starts_at,c.ends_at,i.item_code,i.name from knowledge_challenges c left join catalog_items i on i.id=c.item_id where c.active=true and(c.starts_at is null or c.starts_at<=now())and(c.ends_at is null or c.ends_at>=now()) order by c.created_at desc;end;$$;

create or replace function dealer_knowledge_history() returns table(id uuid,challenge_title text,challenge_type text,machine_brand text,machine_type text,machine_model text,suggested_part_name text,status text,created_at timestamptz) language plpgsql security definer set search_path=public as $$declare d uuid;begin select dealer_id into d from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if d is null then raise exception 'Linked dealer login required';end if;return query select s.id,c.title,c.challenge_type,s.machine_brand,s.machine_type,s.machine_model,s.suggested_part_name,s.status,s.created_at from knowledge_submissions s join knowledge_challenges c on c.id=s.challenge_id where s.dealer_id=d order by s.created_at desc;end;$$;

create or replace function create_knowledge_challenge(p_type text,p_item uuid,p_title text,p_instructions text,p_photo_urls jsonb,p_starts_at timestamptz default null,p_ends_at timestamptz default null) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;cid uuid;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Owner/Admin required';end if;if p_type not in('known_part_fitment','mystery_part_photo') or nullif(trim(p_title),'') is null then raise exception 'Invalid knowledge request';end if;if p_type='known_part_fitment' and (p_item is null or not exists(select 1 from catalog_items where id=p_item and item_type='spare_part' and active=true)) then raise exception 'Known part request requires an active spare item';end if;if p_type='mystery_part_photo' and (p_photo_urls is null or jsonb_typeof(p_photo_urls)<>'array' or jsonb_array_length(p_photo_urls)=0) then raise exception 'Mystery request requires photo';end if;if p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at then raise exception 'End time must be after start time';end if;insert into knowledge_challenges(challenge_type,item_id,title,instructions,photo_urls,starts_at,ends_at,created_by) values(p_type,p_item,upper(trim(p_title)),nullif(trim(p_instructions),''),coalesce(p_photo_urls,'[]'::jsonb),p_starts_at,p_ends_at,a.id) returning id into cid;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'SUITABLE_KNOWLEDGE_REQUEST_CREATED','knowledge_challenge',cid::text,jsonb_build_object('type',p_type));return cid;end;$$;

create or replace function set_knowledge_challenge_active(p_challenge uuid,p_active boolean,p_reason text) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Owner/Admin required';end if;if nullif(trim(p_reason),'') is null then raise exception 'Reason required';end if;update knowledge_challenges set active=p_active where id=p_challenge;if not found then raise exception 'Knowledge request not found';end if;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,case when p_active then 'SUITABLE_KNOWLEDGE_REQUEST_ENABLED' else 'SUITABLE_KNOWLEDGE_REQUEST_DISABLED' end,'knowledge_challenge',p_challenge::text,jsonb_build_object('reason',trim(p_reason)));end;$$;

create or replace function submit_knowledge_answer(p_challenge uuid,p_part_name text,p_brand text,p_machine_type text,p_model text,p_notes text default null) returns uuid language plpgsql security definer set search_path=public as $$declare u app_users%rowtype;c knowledge_challenges%rowtype;rid uuid;begin select * into u from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found or u.dealer_id is null or not exists(select 1 from dealers d where d.id=u.dealer_id and d.status='approved') then raise exception 'Approved linked dealer login required';end if;select * into c from knowledge_challenges where id=p_challenge and active=true and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>=now());if not found then raise exception 'Knowledge request unavailable';end if;if nullif(trim(p_brand),'') is null or nullif(trim(p_model),'') is null then raise exception 'Machine brand and model required';end if;if exists(select 1 from knowledge_submissions s where s.challenge_id=p_challenge and s.dealer_id=u.dealer_id and upper(s.machine_brand)=upper(trim(p_brand)) and upper(s.machine_model)=upper(trim(p_model)) and s.status in('pending','verified','partly_correct')) then raise exception 'You already submitted this fitment';end if;insert into knowledge_submissions(challenge_id,dealer_id,suggested_part_name,machine_brand,machine_type,machine_model,notes)values(p_challenge,u.dealer_id,nullif(upper(trim(p_part_name)),''),upper(trim(p_brand)),nullif(upper(trim(p_machine_type)),''),upper(trim(p_model)),nullif(trim(p_notes),''))returning id into rid;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(u.id,'DEALER_SUITABLE_SUGGESTION_SUBMITTED','knowledge_submission',rid::text,jsonb_build_object('challenge_id',p_challenge));return rid;end;$$;

create or replace function review_knowledge_answer(p_submission uuid,p_status text,p_admin_note text,p_add_to_private_record boolean default false) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;s knowledge_submissions%rowtype;c knowledge_challenges%rowtype;item uuid;map_id uuid;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Owner/Admin required';end if;if p_status not in('verified','partly_correct','rejected','duplicate') then raise exception 'Invalid review';end if;select * into s from knowledge_submissions where id=p_submission for update;if not found or s.status<>'pending' then raise exception 'Pending submission required';end if;select * into c from knowledge_challenges where id=s.challenge_id;if p_add_to_private_record and p_status not in('verified','partly_correct') then raise exception 'Only verified fitment can be promoted';end if;if p_add_to_private_record then item:=c.item_id;if item is null then raise exception 'Link a TORVO spare item before promoting mystery identification to Suitable Master';end if;if exists(select 1 from suitable_mappings m where m.spare_part_id=item and upper(m.machine_brand)=upper(s.machine_brand) and upper(m.machine_model)=upper(s.machine_model)) then raise exception 'Suitable mapping already exists';end if;insert into suitable_mappings(spare_part_id,machine_brand,machine_model,fitment_notes,visibility,created_by)values(item,s.machine_brand,s.machine_model,'VERIFIED DEALER FITMENT: '||coalesce(s.notes,''),'private',a.id)returning id into map_id;insert into knowledge_verified_fitments(submission_id,item_id,machine_brand,machine_type,machine_model,suitable_mapping_id,approved_by)values(s.id,item,s.machine_brand,s.machine_type,s.machine_model,map_id,a.id);end if;update knowledge_submissions set status=p_status,admin_note=nullif(trim(p_admin_note),''),verified_by=a.id,verified_at=now() where id=p_submission;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'SUITABLE_SUGGESTION_REVIEWED','knowledge_submission',s.id::text,jsonb_build_object('status',p_status,'private_record_added',p_add_to_private_record));end;$$;

-- Retire every execution path from the obsolete knowledge-points RPC if it existed in an earlier V2 draft.
do $$begin if to_regprocedure('dealer_knowledge_points()') is not null then execute 'revoke all on function dealer_knowledge_points() from public,anon,authenticated';end if;end$$;

revoke all on function dealer_knowledge_challenges(),dealer_knowledge_history(),create_knowledge_challenge(text,uuid,text,text,jsonb,timestamptz,timestamptz),set_knowledge_challenge_active(uuid,boolean,text),submit_knowledge_answer(uuid,text,text,text,text,text),review_knowledge_answer(uuid,text,text,boolean) from public,anon;
grant execute on function dealer_knowledge_challenges(),dealer_knowledge_history(),create_knowledge_challenge(text,uuid,text,text,jsonb,timestamptz,timestamptz),set_knowledge_challenge_active(uuid,boolean,text),submit_knowledge_answer(uuid,text,text,text,text,text),review_knowledge_answer(uuid,text,text,boolean) to authenticated;
