-- TORVO V2 FINAL PAYMENT APPROVAL BOUNDARY
-- Install AFTER v2-maker-checker-payment-gate.sql. Browser cannot bypass maker-checker.
create or replace function public.apply_payment_internal(p_estimate uuid,p_status text,p_amount numeric,p_request_key text,p_actor uuid) returns uuid language plpgsql security definer set search_path=public as $$
declare pid uuid;f numeric;already numeric;existing payments%rowtype;
begin
 if p_status not in('cash','pending','received') or p_amount is null or p_amount<=0 or nullif(trim(p_request_key),'') is null then raise exception 'Valid payment required';end if;
 if p_actor is null or not exists(select 1 from app_users where id=p_actor and active=true) then raise exception 'Valid payment actor required';end if;
 select * into existing from payments where request_key=trim(p_request_key);if found then if existing.estimate_id=p_estimate and existing.status=p_status and existing.amount=p_amount then return existing.id;end if;raise exception 'Payment request key already used';end if;
 select final_payable into f from sales_documents where id=p_estimate and doc_type='estimate' for update;if not found then raise exception 'Estimate not found';end if;
 select coalesce(sum(amount),0) into already from payments where estimate_id=p_estimate and status in('cash','received');if p_status in('cash','received') and already+p_amount>f then raise exception 'Payment exceeds estimate payable';end if;
 insert into payments(estimate_id,status,amount,received_at,recorded_by,request_key)values(p_estimate,p_status,p_amount,case when p_status in('cash','received')then now()end,p_actor,trim(p_request_key))returning id into pid;
 insert into audit_log(actor_id,action,entity_type,entity_id,details)values(p_actor,'INTERNAL_PAYMENT_NOTED','estimate',p_estimate::text,jsonb_build_object('payment_id',pid,'status',p_status,'amount',p_amount,'request_key',trim(p_request_key),'server_boundary',true));return pid;
end;$$;
revoke all on function public.apply_payment_internal(uuid,text,numeric,text,uuid) from public,anon,authenticated;

create or replace function public.record_payment(p_estimate uuid,p_status text,p_amount numeric,p_request_key text) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role<>'owner' then raise exception 'Owner direct payment authorization required; use approval workflow';end if;return public.apply_payment_internal(p_estimate,p_status,p_amount,p_request_key,a.id);end;$$;
revoke all on function public.record_payment(uuid,text,numeric,text) from public,anon;grant execute on function public.record_payment(uuid,text,numeric,text) to authenticated;

create or replace function public.decide_payment_approval(p_approval uuid,p_decision text,p_note text default null)returns uuid language plpgsql security definer set search_path=public as $$
declare a app_users%rowtype;r approval_requests%rowtype;perm approval_permissions%rowtype;allowed boolean:=false;payment_id uuid;payload jsonb;
begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found then raise exception 'Not authorized';end if;select * into r from approval_requests where id=p_approval for update;if not found or r.module<>'payment' then raise exception 'Payment approval not found';end if;if r.status<>'pending_approval' then raise exception 'Approval request already decided';end if;if lower(trim(p_decision)) not in('approved','rejected') then raise exception 'Decision must be APPROVED or REJECTED';end if;if a.role='owner' then allowed:=true;elsif a.role in('admin','accountant')then select * into perm from approval_permissions where user_id=a.id;allowed:=found and perm.can_approve_transactions;end if;if not allowed then raise exception 'Approval permission required';end if;if r.maker_id=a.id and a.role<>'owner' and not coalesce(perm.can_approve_own_entry,false)then raise exception 'Self approval is not permitted';end if;
 if lower(trim(p_decision))='rejected' then update approval_requests set status='rejected',checker_id=a.id,checker_note=nullif(upper(trim(coalesce(p_note,''))),''),decided_at=now(),updated_at=now() where id=r.id;insert into approval_history(approval_id,action,actor_id,note)values(r.id,'rejected',a.id,nullif(upper(trim(coalesce(p_note,''))),''));insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'PAYMENT_APPROVAL_REJECTED','approval_request',r.id::text,jsonb_build_object('maker_id',r.maker_id));return null;end if;
 payload:=r.payload_snapshot;payment_id:=public.apply_payment_internal((payload->>'estimate_id')::uuid,payload->>'status',(payload->>'amount')::numeric,payload->>'request_key',a.id);update approval_requests set status='approved',checker_id=a.id,checker_note=nullif(upper(trim(coalesce(p_note,''))),''),decided_at=now(),updated_at=now(),effect_applied_at=now(),effect_result=jsonb_build_object('payment_id',payment_id)where id=r.id;insert into approval_history(approval_id,action,actor_id,note,details)values(r.id,'approved',a.id,nullif(upper(trim(coalesce(p_note,''))),''),jsonb_build_object('payment_id',payment_id));insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'PAYMENT_APPROVAL_APPROVED','approval_request',r.id::text,jsonb_build_object('maker_id',r.maker_id,'payment_id',payment_id));return payment_id;end;$$;
revoke all on function public.decide_payment_approval(uuid,text,text) from public,anon;grant execute on function public.decide_payment_approval(uuid,text,text) to authenticated;
