-- TORVO V2 CROSS-TABLE DUPLICATE PROTECTION: DESIGN HOLD
-- DO NOT INSTALL THIS FILE. NO EXECUTABLE SQL IS APPROVED HERE.
-- A naive cross-table draft check would block legitimate Draft Library to Product Master conversion.
-- Require atomic server-side conversion, consistent code locking, and verified role authorization.
-- Preserve existing catalog inventory/audit logic and avoid production changes.
