-- TORVO V2 secure report summaries. Financial metrics never return to Store Keeper/Salesman.
create or replace function get_report_summary() returns jsonb language plpgsql stable security definer set search_path=public as $$declare a app_users%rowtype;r jsonb:='{}'::jsonb;s numeric:=0;est numeric:=0;rec numeric:=0;begin
select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role='dealer' then raise exception 'Internal active user required';end if;
if a.role in('owner','admin','accountant') then
 select coalesce(sum(e.final_payable),0) into s from sales_documents e where e.doc_type='estimate' and exists(select 1 from dispatches d where d.estimate_id=e.id and d.status='delivered' and d.delivered_at is not null);
 select coalesce(sum(final_payable),0) into est from sales_documents where doc_type='estimate';
 select coalesce(sum(amount),0) into rec from payments where status in('cash','received');
 r:=r||jsonb_build_object('sales_total',s,'delivered_sales_count',(select count(*) from sales_documents e where e.doc_type='estimate' and exists(select 1 from dispatches d where d.estimate_id=e.id and d.status='delivered' and d.delivered_at is not null)),'estimate_total',est,'estimate_count',(select count(*) from sales_documents where doc_type='estimate'),'sales_order_count',(select count(*) from sales_documents where doc_type='sales_order'),'payment_received',rec,'payment_outstanding',greatest(0,est-rec));
end if;
if a.role in('owner','admin') then
 r:=r||jsonb_build_object('active_dealers',(select count(*) from dealers where status='approved'),'inventory_items',(select count(*) from inventory),'low_stock',(select count(*) from inventory where current_qty<=reorder_level),'out_stock',(select count(*) from inventory where current_qty<=0),'reorder_open',(select count(*) from stock_reorder_requests where status in('submitted','ordered')),'dispatch_pending',(select count(*) from dispatches where status<>'delivered'),'missing_open',(select count(*) from non_available_requests where status='open'),'missing_total',(select count(*) from non_available_requests),'audit_count',(select count(*) from audit_log),'query_count',(select count(*) from sales_documents where doc_type='query'),'quotation_count',(select count(*) from sales_documents where doc_type='quotation'),'accepted_quotation_count',(select count(*) from sales_documents where doc_type='quotation' and status in('accepted','converted')),'scheme_count',(select count(*) from schemes));
end if;
if a.role='store_keeper' then r:=r||jsonb_build_object('inventory_items',(select count(*) from inventory),'low_stock',(select count(*) from inventory where current_qty<=reorder_level),'out_stock',(select count(*) from inventory where current_qty<=0),'reorder_open',(select count(*) from stock_reorder_requests where status in('submitted','ordered')),'dispatch_pending',(select count(*) from dispatches where status<>'delivered'));end if;
return r;end;$$;
revoke all on function get_report_summary() from public,anon;grant execute on function get_report_summary() to authenticated;
