-- TORVO V2 secure catalog, compatibility and CURRENT locked sales workflow RPCs.
-- Actor identity always comes from auth.uid(); callers never supply actor IDs.
-- Authoritative active sales flow: Dealer Purchase Order -> TORVO Sales Order -> Dealer OK -> Estimate.

-- Drop previous signatures so PostgREST cannot expose ambiguous overloads.
drop function if exists upsert_catalog_item(uuid,text,text,text,text,text,text,text,text,boolean);
drop function if exists upsert_catalog_item(uuid,text,text,text,text,text,text,text,text,text,boolean);
create or replace function upsert_catalog_item(p_item uuid,p_type text,p_code text,p_name text,p_oem_code text default null,p_brand text default null,p_category text default null,p_model text default null,p_image_url text default null,p_gst_mode text default null,p_active boolean default true)
returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;v_id uuid;v_code text:=torvo_normalize_business_text(p_code);v_name text:=torvo_normalize_business_text(p_name);v_oem text:=nullif(torvo_normalize_business_text(p_oem_code),'');v_brand text:=nullif(torvo_normalize_business_text(p_brand),'');v_category text:=nullif(torvo_normalize_business_text(p_category),'');v_model text:=nullif(torvo_normalize_business_text(p_model),'');begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if p_type not in('machine','spare_part','accessory') or v_code='' or v_name='' then raise exception 'Type, item code and name required';end if;if p_gst_mode is not null and p_gst_mode not in('included','extra') then raise exception 'Invalid GST mode';end if;if exists(select 1 from catalog_items x where torvo_normalize_business_text(x.item_code)=v_code and (p_item is null or x.id<>p_item)) then raise exception 'ITEM CODE % ALREADY EXISTS',v_code;end if;if p_item is null then insert into catalog_items(item_type,item_code,oem_code,name,brand,category,model,image_url,gst_mode,active) values(p_type,v_code,v_oem,v_name,v_brand,v_category,v_model,nullif(trim(p_image_url),''),p_gst_mode,p_active) returning id into v_id;insert into inventory(item_id,current_qty,reorder_level) values(v_id,0,0) on conflict(item_id) do nothing;else perform 1 from catalog_items where id=p_item for update;if not found then raise exception 'Catalog item not found';end if;update catalog_items set item_type=p_type,item_code=v_code,oem_code=v_oem,name=v_name,brand=v_brand,category=v_category,model=v_model,image_url=nullif(trim(p_image_url),''),gst_mode=p_gst_mode,active=p_active where id=p_item;v_id:=p_item;end if;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,case when p_item is null then 'CATALOG_CREATED' else 'CATALOG_UPDATED' end,'catalog_item',v_id::text,jsonb_build_object('item_type',p_type,'item_code',v_code,'oem_code',v_oem));return v_id;end;$$;
revoke all on function upsert_catalog_item(uuid,text,text,text,text,text,text,text,text,text,boolean) from public,anon;grant execute on function upsert_catalog_item(uuid,text,text,text,text,text,text,text,text,text,boolean) to authenticated;

create or replace function set_item_rate(p_item uuid,p_rate_group text,p_min_qty numeric,p_rate numeric) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;v_id uuid;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if p_rate_group not in('A','B','C') or p_min_qty<=0 or p_rate<0 then raise exception 'Invalid rate';end if;perform 1 from catalog_items where id=p_item;if not found then raise exception 'Catalog item not found';end if;insert into item_rates(item_id,rate_group,min_qty,selling_rate) values(p_item,p_rate_group,p_min_qty,p_rate) on conflict(item_id,rate_group,min_qty) do update set selling_rate=excluded.selling_rate returning id into v_id;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'ITEM_RATE_SET','catalog_item',p_item::text,jsonb_build_object('rate_group',p_rate_group,'min_qty',p_min_qty,'rate',p_rate));return v_id;end;$$;
revoke all on function set_item_rate(uuid,text,numeric,numeric) from public,anon;grant execute on function set_item_rate(uuid,text,numeric,numeric) to authenticated;

create or replace function set_machine_spare_mapping(p_machine uuid,p_spare_part uuid,p_required_qty numeric default 1,p_fitment_type text default 'compatible',p_dealer_visible boolean default false,p_public_visible boolean default false,p_notes text default null) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;v_id uuid;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Not authorized';end if;if p_required_qty<=0 or p_fitment_type not in('oem','compatible','alternative') then raise exception 'Invalid mapping';end if;if not exists(select 1 from catalog_items where id=p_machine and item_type='machine') then raise exception 'Valid machine required';end if;if not exists(select 1 from catalog_items where id=p_spare_part and item_type='spare_part') then raise exception 'Valid spare part required';end if;insert into machine_spare_mapping(machine_id,spare_part_id,required_qty,fitment_type,dealer_visible,public_visible,notes) values(p_machine,p_spare_part,p_required_qty,p_fitment_type,p_dealer_visible,p_public_visible,nullif(trim(p_notes),'')) on conflict(machine_id,spare_part_id,fitment_type) do update set required_qty=excluded.required_qty,dealer_visible=excluded.dealer_visible,public_visible=excluded.public_visible,notes=excluded.notes returning id into v_id;insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'COMPATIBILITY_SET','compatibility',v_id::text,jsonb_build_object('machine_id',p_machine,'spare_part_id',p_spare_part,'fitment_type',p_fitment_type));return v_id;end;$$;
revoke all on function set_machine_spare_mapping(uuid,uuid,numeric,text,boolean,boolean,text) from public,anon;grant execute on function set_machine_spare_mapping(uuid,uuid,numeric,text,boolean,boolean,text) to authenticated;

-- Legacy Query/Quotation functions are intentionally retired from the active V2 API.
-- Existing historical rows remain readable; this does not delete business history.
revoke all on function create_sales_query(uuid,jsonb) from public,anon,authenticated;
revoke all on function create_quotation(uuid,jsonb) from public,anon,authenticated;
revoke all on function accept_quotation(uuid) from public,anon,authenticated;
revoke all on function quotation_to_sales_order(uuid) from public,anon,authenticated;

create or replace function sales_order_to_estimate(p_sales_order uuid,p_freight numeric default 0,p_other_charges numeric default 0) returns uuid language plpgsql security definer set search_path=public as $$
declare a app_users%rowtype;s sales_documents%rowtype;v_doc uuid;v_final numeric;
begin
 select * into a from app_users where auth_user_id=auth.uid() and active=true;
 if not found or a.role not in('owner','admin','accountant') then raise exception 'Owner/Admin/Accountant required';end if;
 if p_freight<0 or p_other_charges<0 then raise exception 'Charges cannot be negative';end if;
 select * into s from sales_documents where id=p_sales_order and doc_type='sales_order' for update;
 if not found then raise exception 'Sales Order not found';end if;
 if s.status<>'dealer_ok' or s.dealer_ok_revision is null or s.dealer_ok_revision<>coalesce(s.revision_no,1) or s.dealer_ok_at is null then raise exception 'Latest Sales Order revision requires Dealer OK before Estimate';end if;
 if exists(select 1 from sales_documents where (root_order_id=s.id or parent_id=s.id) and doc_type='estimate') then raise exception 'Estimate already exists';end if;
 if not exists(select 1 from sales_document_lines where document_id=s.id) then raise exception 'Sales Order has no items';end if;
 v_final:=s.subtotal+p_freight+p_other_charges;
 insert into sales_documents(dealer_id,doc_type,status,parent_id,root_order_id,subtotal,freight,other_charges,final_payable,created_by,revision_no) values(s.dealer_id,'estimate','final',s.id,s.id,s.subtotal,p_freight,p_other_charges,v_final,a.id,s.revision_no) returning id into v_doc;
 insert into sales_document_lines(document_id,item_id,qty,rate,amount) select v_doc,item_id,qty,rate,amount from sales_document_lines where document_id=s.id;
 insert into dispatches(estimate_id,status,updated_by) values(v_doc,'pick_list',a.id);
 update sales_documents set status='converted',estimate_created_at=now(),locked_at=now(),lock_reason='ESTIMATE CREATED AFTER DEALER OK' where id=s.id;
 insert into audit_log(actor_id,action,entity_type,entity_id,details) values(a.id,'ESTIMATE_CREATED','sales_document',v_doc::text,jsonb_build_object('sales_order_id',s.id,'revision_no',s.revision_no,'dealer_ok_revision',s.dealer_ok_revision,'freight',p_freight,'other_charges',p_other_charges,'final_payable',v_final,'stock_deducted',false));return v_doc;
end;$$;
revoke all on function sales_order_to_estimate(uuid,numeric,numeric) from public,anon;
grant execute on function sales_order_to_estimate(uuid,numeric,numeric) to authenticated;
