-- TORVO V2 SALES RETURN + PURCHASE RETURN
-- Returns are distinct business documents, never destructive edits/reversals of the original transaction.
-- Install after Purchase Requirement receipt integrity and Delivery stock integrity.
create table if not exists public.transaction_returns(
 id uuid primary key default gen_random_uuid(),return_type text not null check(return_type in('sales_return','purchase_return')),source_id uuid not null,status text not null default 'draft' check(status in('draft','completed','cancelled')),reason text not null,request_key text not null unique,created_by uuid not null references public.app_users(id),created_at timestamptz not null default now(),completed_by uuid references public.app_users(id),completed_at timestamptz,cancelled_by uuid references public.app_users(id),cancelled_at timestamptz,cancel_reason text,details jsonb not null default '{}'::jsonb);
create table if not exists public.transaction_return_lines(id uuid primary key default gen_random_uuid(),return_id uuid not null references public.transaction_returns(id) on delete restrict,item_id uuid not null references public.catalog_items(id),qty numeric not null check(qty>0),unique(return_id,item_id));
alter table public.transaction_returns enable row level security;alter table public.transaction_return_lines enable row level security;revoke all on public.transaction_returns,public.transaction_return_lines from anon,authenticated;

create or replace function public.complete_sales_return(p_estimate uuid,p_lines jsonb,p_reason text,p_request_key text) returns uuid language plpgsql security definer set search_path=public as $$
declare a app_users%rowtype;r uuid;old transaction_returns%rowtype;x jsonb;i uuid;q numeric;delivered numeric;returned numeric;
begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Owner/Admin required';end if;if nullif(trim(p_reason),'') is null or nullif(trim(p_request_key),'') is null then raise exception 'Reason and request key required';end if;
 select * into old from transaction_returns where request_key=trim(p_request_key);if found then if old.return_type='sales_return' and old.source_id=p_estimate and old.status='completed' then return old.id;else raise exception 'Return request key already used';end if;end if;
 if not exists(select 1 from delivery_stock_finalizations where estimate_id=p_estimate) then raise exception 'Only actually delivered Estimate can be returned';end if;if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'Return items required';end if;if exists(select 1 from(select e->>'item_id'i,count(*)c from jsonb_array_elements(p_lines)e group by e->>'item_id')s where i is null or c>1)then raise exception 'Duplicate/missing return item';end if;
 insert into transaction_returns(return_type,source_id,status,reason,request_key,created_by,completed_by,completed_at)values('sales_return',p_estimate,'completed',upper(trim(p_reason)),trim(p_request_key),a.id,a.id,now())returning id into r;
 for x in select * from jsonb_array_elements(p_lines)loop begin i:=(x->>'item_id')::uuid;q:=(x->>'qty')::numeric;exception when others then raise exception 'Invalid return line';end;select coalesce(sum(qty),0) into delivered from sales_document_lines where document_id=p_estimate and item_id=i;select coalesce(sum(rl.qty),0) into returned from transaction_return_lines rl join transaction_returns rr on rr.id=rl.return_id where rr.return_type='sales_return' and rr.source_id=p_estimate and rr.status='completed' and rl.item_id=i;if q<=0 or returned+q>delivered then raise exception 'Sales return quantity exceeds delivered quantity';end if;insert into transaction_return_lines(return_id,item_id,qty)values(r,i,q);insert into inventory(item_id,current_qty,updated_at)values(i,q,now())on conflict(item_id)do update set current_qty=inventory.current_qty+excluded.current_qty,updated_at=now();insert into inventory_movements(item_id,qty_change,reason,reference_type,reference_id,created_by)values(i,q,'SALES RETURN','sales_return',r,a.id);end loop;
 insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'SALES_RETURN_COMPLETED','sales_return',r::text,jsonb_build_object('estimate_id',p_estimate,'reason',upper(trim(p_reason)),'request_key',trim(p_request_key)));return r;end;$$;

create or replace function public.complete_purchase_return(p_purchase uuid,p_lines jsonb,p_reason text,p_request_key text) returns uuid language plpgsql security definer set search_path=public as $$
declare a app_users%rowtype;r uuid;old transaction_returns%rowtype;x jsonb;i uuid;q numeric;bought numeric;returned numeric;stock numeric;
begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin') then raise exception 'Owner/Admin required';end if;if nullif(trim(p_reason),'') is null or nullif(trim(p_request_key),'') is null then raise exception 'Reason and request key required';end if;select * into old from transaction_returns where request_key=trim(p_request_key);if found then if old.return_type='purchase_return' and old.source_id=p_purchase and old.status='completed' then return old.id;else raise exception 'Return request key already used';end if;end if;
 if not exists(select 1 from purchase_stock_receipts where purchase_id=p_purchase and reversed_at is null)then raise exception 'Only received unreversed Purchase can be returned';end if;if exists(select 1 from purchase_requirement_links where purchase_id=p_purchase and reversed_at is null)then raise exception 'Reverse active Purchase Requirement links before Purchase Return';end if;if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'Return items required';end if;if exists(select 1 from(select e->>'item_id'i,count(*)c from jsonb_array_elements(p_lines)e group by e->>'item_id')s where i is null or c>1)then raise exception 'Duplicate/missing return item';end if;
 insert into transaction_returns(return_type,source_id,status,reason,request_key,created_by,completed_by,completed_at)values('purchase_return',p_purchase,'completed',upper(trim(p_reason)),trim(p_request_key),a.id,a.id,now())returning id into r;
 for x in select * from jsonb_array_elements(p_lines)loop begin i:=(x->>'item_id')::uuid;q:=(x->>'qty')::numeric;exception when others then raise exception 'Invalid return line';end;select coalesce(sum(qty),0) into bought from purchase_lines where purchase_id=p_purchase and item_id=i;select coalesce(sum(rl.qty),0) into returned from transaction_return_lines rl join transaction_returns rr on rr.id=rl.return_id where rr.return_type='purchase_return' and rr.source_id=p_purchase and rr.status='completed' and rl.item_id=i;select current_qty into stock from inventory where item_id=i for update;if q<=0 or returned+q>bought then raise exception 'Purchase return quantity exceeds received quantity';end if;if stock is null or stock<q then raise exception 'Insufficient current stock for Purchase Return';end if;insert into transaction_return_lines(return_id,item_id,qty)values(r,i,q);update inventory set current_qty=current_qty-q,updated_at=now() where item_id=i;insert into inventory_movements(item_id,qty_change,reason,reference_type,reference_id,created_by)values(i,-q,'PURCHASE RETURN','purchase_return',r,a.id);end loop;
 insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'PURCHASE_RETURN_COMPLETED','purchase_return',r::text,jsonb_build_object('purchase_id',p_purchase,'reason',upper(trim(p_reason)),'request_key',trim(p_request_key)));return r;end;$$;
revoke all on function public.complete_sales_return(uuid,jsonb,text,text),public.complete_purchase_return(uuid,jsonb,text,text) from public,anon;grant execute on function public.complete_sales_return(uuid,jsonb,text,text),public.complete_purchase_return(uuid,jsonb,text,text) to authenticated;
create or replace function public.get_transaction_returns(p_type text default null,p_limit integer default 200)returns table(id uuid,return_type text,source_id uuid,status text,reason text,created_at timestamptz,completed_at timestamptz,created_by_name text)language plpgsql stable security definer set search_path=public as $$declare a app_users%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant','store_keeper')then raise exception 'Not authorized';end if;return query select r.id,r.return_type,r.source_id,r.status,r.reason,r.created_at,r.completed_at,u.full_name from transaction_returns r left join app_users u on u.id=r.created_by where p_type is null or r.return_type=p_type order by r.created_at desc limit greatest(1,least(coalesce(p_limit,200),500));end;$$;revoke all on function public.get_transaction_returns(text,integer) from public,anon;grant execute on function public.get_transaction_returns(text,integer) to authenticated;
