-- TORVO V2 core schema. Run on production only after staging review.
create extension if not exists pgcrypto;
create table if not exists app_users (id uuid primary key default gen_random_uuid(),auth_user_id uuid unique,full_name text not null,mobile text unique,role text not null check(role in ('owner','admin','salesman','accountant','store_keeper','dealer')),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists dealers (id uuid primary key default gen_random_uuid(),dealer_code text unique,shop_name text not null,contact_person text not null,mobile text not null,whatsapp text,email text,address text,pin_code text,state text,district text,city text,visiting_card_url text,rate_group text check(rate_group in ('A','B','C')),status text not null default 'pending',approved_by uuid references app_users(id),approved_at timestamptz,created_at timestamptz not null default now());
create table if not exists catalog_items (id uuid primary key default gen_random_uuid(),item_type text not null check(item_type in ('machine','spare_part','accessory')),item_code text unique not null,oem_code text,name text not null,brand text,category text,model text,image_url text,gst_mode text check(gst_mode in ('included','extra')),active boolean not null default true,created_at timestamptz not null default now());
alter table catalog_items add column if not exists gst_rate numeric check(gst_rate is null or(gst_rate>=0 and gst_rate<=100));alter table catalog_items add column if not exists hsn_code text;alter table catalog_items add column if not exists box_packing_qty numeric check(box_packing_qty is null or box_packing_qty>0);alter table catalog_items add column if not exists box_offer_enabled boolean not null default false;alter table catalog_items add column if not exists box_offer_mode text check(box_offer_mode in('fixed_rate','percent_discount'));alter table catalog_items add column if not exists box_offer_value numeric check(box_offer_value is null or box_offer_value>=0);
create table if not exists item_rates (id uuid primary key default gen_random_uuid(),item_id uuid not null references catalog_items(id) on delete restrict,rate_group text not null check(rate_group in ('A','B','C')),min_qty numeric not null default 1,selling_rate numeric not null check(selling_rate>=0),unique(item_id,rate_group,min_qty));
create table if not exists machine_spare_mapping (id uuid primary key default gen_random_uuid(),machine_id uuid not null references catalog_items(id),spare_part_id uuid not null references catalog_items(id),required_qty numeric not null default 1,fitment_type text not null default 'compatible',dealer_visible boolean not null default false,public_visible boolean not null default false,notes text,unique(machine_id,spare_part_id,fitment_type));
create table if not exists suitable_mappings (id uuid primary key default gen_random_uuid(),spare_part_id uuid not null references catalog_items(id),machine_id uuid references catalog_items(id),machine_brand text,machine_model text,fitment_notes text,visibility text not null default 'private',created_by uuid references app_users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists suitable_selling_codes (id uuid primary key default gen_random_uuid(),mapping_id uuid not null references suitable_mappings(id),source_item_id uuid not null references catalog_items(id),special_code text not null unique,selling_name text not null,selling_brand text not null default 'TORVO',pricing_mode text not null default 'percent_plus',markup_percent numeric,fixed_rate_a numeric,fixed_rate_b numeric,fixed_rate_c numeric,packing_mode text not null default 'torvo',packing_instruction text,active boolean not null default true,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists inventory (item_id uuid primary key references catalog_items(id),current_qty numeric not null default 0,reorder_level numeric not null default 0,updated_at timestamptz not null default now());
create table if not exists suppliers (id uuid primary key default gen_random_uuid(),supplier_name text not null,company_name text,mobile text,whatsapp text,city text,gstin text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists purchase_headers (id uuid primary key default gen_random_uuid(),supplier_id uuid not null references suppliers(id),invoice_no text not null,invoice_date date not null,total_reference_amount numeric not null default 0,created_by uuid references app_users(id),created_at timestamptz not null default now(),unique(supplier_id,invoice_no));
create table if not exists purchase_lines (id uuid primary key default gen_random_uuid(),purchase_id uuid not null references purchase_headers(id),item_id uuid not null references catalog_items(id),qty numeric not null check(qty>0),purchase_rate numeric not null check(purchase_rate>=0),line_amount numeric generated always as(qty*purchase_rate) stored);
create table if not exists sales_documents (id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id),doc_type text not null check(doc_type in ('query','quotation','sales_order','estimate')),status text not null default 'draft',parent_id uuid references sales_documents(id),subtotal numeric not null default 0,freight numeric not null default 0,other_charges numeric not null default 0,final_payable numeric not null default 0,created_by uuid references app_users(id),created_at timestamptz not null default now());
alter table sales_documents add column if not exists root_order_id uuid references sales_documents(id);alter table sales_documents add column if not exists revision_no integer not null default 1;alter table sales_documents add column if not exists dealer_modification_limit integer not null default 2;alter table sales_documents add column if not exists dealer_modifications_used integer not null default 0;alter table sales_documents add column if not exists dealer_ok_revision integer;alter table sales_documents add column if not exists dealer_ok_at timestamptz;alter table sales_documents add column if not exists estimate_created_at timestamptz;alter table sales_documents add column if not exists locked_at timestamptz;alter table sales_documents add column if not exists lock_reason text;alter table sales_documents add column if not exists final_sale_serial bigint unique;alter table sales_documents add column if not exists final_sale_serial_issued_at timestamptz;
create sequence if not exists final_sale_serial_seq start 1;
create table if not exists sales_document_lines (id uuid primary key default gen_random_uuid(),document_id uuid not null references sales_documents(id) on delete cascade,item_id uuid not null references catalog_items(id),qty numeric not null check(qty>0),rate numeric,amount numeric);
create table if not exists sales_order_revisions (id uuid primary key default gen_random_uuid(),sales_order_id uuid not null references sales_documents(id),revision_no integer not null,changed_by uuid references app_users(id),actor_role text not null,change_reason text not null,before_data jsonb not null default '{}'::jsonb,after_data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(sales_order_id,revision_no));
create table if not exists payments (id uuid primary key default gen_random_uuid(),estimate_id uuid not null references sales_documents(id),status text not null check(status in ('cash','pending','received')),amount numeric not null default 0,received_at timestamptz,recorded_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists delivery_settings (id boolean primary key default true check(id=true),spare_free_delivery_enabled boolean not null default true,spare_free_delivery_threshold numeric not null default 10000,updated_by uuid references app_users(id),updated_at timestamptz not null default now());insert into delivery_settings(id) values(true) on conflict(id) do nothing;
create table if not exists delivery_setting_history (id bigint generated always as identity primary key,old_enabled boolean,old_threshold numeric,new_enabled boolean not null,new_threshold numeric not null,reason text not null,changed_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists estimate_delivery_details (estimate_id uuid primary key references sales_documents(id),method text not null check(method in ('courier','transport','torvo_delivery','self_pickup','other')),provider_name text,lr_awb_receipt_no text,delivery_person text,delivery_charge numeric not null default 0,spare_parts_subtotal numeric not null default 0,spare_free_delivery_applied boolean not null default false,free_delivery_threshold_snapshot numeric,remarks text,updated_by uuid references app_users(id),updated_at timestamptz not null default now());
-- Future integrations: provider-neutral so Delivery and Accounting APIs can be connected without replacing business records.
create table if not exists integration_settings (integration_type text primary key check(integration_type in('delivery','accounting','whatsapp')),enabled boolean not null default false,provider_name text,config_reference text,updated_by uuid references app_users(id),updated_at timestamptz not null default now());
create table if not exists integration_events (id uuid primary key default gen_random_uuid(),integration_type text not null,entity_type text not null,entity_id text not null,direction text not null check(direction in('outbound','inbound')),event_type text not null,external_reference text,status text not null default 'pending',request_key text unique,response_summary text,created_at timestamptz not null default now(),completed_at timestamptz);
-- GST mode remains off until Owner/Admin intentionally enables billing integration.
create table if not exists tax_settings (id boolean primary key default true check(id=true),gst_billing_enabled boolean not null default false,default_pricing_mode text not null default 'included' check(default_pricing_mode in('included','extra')),updated_by uuid references app_users(id),updated_at timestamptz not null default now());insert into tax_settings(id) values(true) on conflict(id) do nothing;
-- Admin sales boosters: discount can be OFF while points booster remains ON.
create table if not exists sales_booster_campaigns (id uuid primary key default gen_random_uuid(),name text not null,active boolean not null default true,scope text not null default 'all' check(scope in('all','A','B','C','selected')),minimum_order_value numeric not null default 0,next_target_value numeric not null check(next_target_value>0),discount_enabled boolean not null default false,discount_mode text check(discount_mode in('fixed','percent')),discount_value numeric check(discount_value is null or discount_value>=0),points_enabled boolean not null default false,points_mode text check(points_mode in('total','bonus')),points_value numeric check(points_value is null or points_value>=0),starts_at timestamptz,ends_at timestamptz,created_by uuid references app_users(id),created_at timestamptz not null default now());
-- Rate-group recommendation only; system never auto-upgrades a dealer.
create table if not exists dealer_grade_rules (id uuid primary key default gen_random_uuid(),active boolean not null default true,from_group text not null check(from_group in('A','B','C')),recommended_group text not null check(recommended_group in('A','B','C')),period_type text not null check(period_type in('monthly','quarterly','financial_year')),minimum_sales numeric not null default 0,growth_percent numeric not null default 0,created_by uuid references app_users(id),created_at timestamptz not null default now(),check(from_group<>recommended_group));
-- One dealer login at one time. Tokens themselves are never stored here; only session identity/hash metadata.
create table if not exists dealer_active_sessions (dealer_id uuid primary key references dealers(id) on delete cascade,session_hash text not null,device_label text,started_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),forced_logout_at timestamptz,forced_logout_by uuid references app_users(id));
-- Dealer education/app links are Admin-managed; unpublished apps remain disabled.
create table if not exists portal_content_settings (id boolean primary key default true check(id=true),training_video_url text,android_app_url text,ios_app_url text,android_published boolean not null default false,ios_published boolean not null default false,updated_by uuid references app_users(id),updated_at timestamptz not null default now());insert into portal_content_settings(id) values(true) on conflict(id) do nothing;
create table if not exists dispatches (id uuid primary key default gen_random_uuid(),estimate_id uuid not null unique references sales_documents(id),status text not null default 'pick_list',tracking_code text,delivered_at timestamptz,stock_deducted_at timestamptz,updated_by uuid references app_users(id));
create table if not exists inventory_movements (id uuid primary key default gen_random_uuid(),item_id uuid not null references catalog_items(id),qty_change numeric not null,reason text not null,reference_type text,reference_id uuid,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists audit_log (id bigint generated always as identity primary key,actor_id uuid references app_users(id),action text not null,entity_type text not null,entity_id text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
