-- TORVO V2 core schema. Run on the production Supabase project only after final review.
create extension if not exists pgcrypto;

create table if not exists app_users (id uuid primary key default gen_random_uuid(),auth_user_id uuid unique,full_name text not null,mobile text unique,role text not null check(role in ('owner','admin','salesman','accountant','store_keeper','dealer')),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists dealers (id uuid primary key default gen_random_uuid(),dealer_code text unique,shop_name text not null,contact_person text not null,mobile text not null,whatsapp text,email text,address text,pin_code text,state text,district text,city text,visiting_card_url text,rate_group text check(rate_group in ('A','B','C')),status text not null default 'pending' check(status in ('pending','approved','hold','rejected','inactive','suspended')),approved_by uuid references app_users(id),approved_at timestamptz,created_at timestamptz not null default now());
create table if not exists catalog_items (id uuid primary key default gen_random_uuid(),item_type text not null check(item_type in ('machine','spare_part','accessory')),item_code text unique not null,oem_code text,name text not null,brand text,category text,model text,image_url text,gst_mode text check(gst_mode in ('included','extra')),active boolean not null default true,created_at timestamptz not null default now());
alter table catalog_items add column if not exists oem_code text;
create unique index if not exists idx_catalog_item_code_normalized_uq on catalog_items(upper(regexp_replace(btrim(item_code),'\s+',' ','g')));
create index if not exists idx_catalog_oem_code on catalog_items(upper(regexp_replace(btrim(oem_code),'\s+',' ','g'))) where oem_code is not null;
create index if not exists idx_catalog_brand on catalog_items(upper(regexp_replace(btrim(brand),'\s+',' ','g'))) where brand is not null;
create index if not exists idx_catalog_category on catalog_items(upper(regexp_replace(btrim(category),'\s+',' ','g'))) where category is not null;
create index if not exists idx_catalog_model on catalog_items(upper(regexp_replace(btrim(model),'\s+',' ','g'))) where model is not null;
create table if not exists item_rates (id uuid primary key default gen_random_uuid(),item_id uuid not null references catalog_items(id) on delete restrict,rate_group text not null check(rate_group in ('A','B','C')),min_qty numeric not null default 1,selling_rate numeric not null check(selling_rate>=0),unique(item_id,rate_group,min_qty));
create table if not exists machine_spare_mapping (id uuid primary key default gen_random_uuid(),machine_id uuid not null references catalog_items(id) on delete restrict,spare_part_id uuid not null references catalog_items(id) on delete restrict,required_qty numeric not null default 1,fitment_type text not null default 'compatible' check(fitment_type in ('oem','compatible','alternative')),dealer_visible boolean not null default false,public_visible boolean not null default false,notes text,unique(machine_id,spare_part_id,fitment_type));
-- Private suitable knowledge is never exposed as a dealer compatibility directory.
create table if not exists suitable_mappings (id uuid primary key default gen_random_uuid(),spare_part_id uuid not null references catalog_items(id) on delete restrict,machine_id uuid references catalog_items(id) on delete restrict,machine_brand text,machine_model text,fitment_notes text,visibility text not null default 'private' check(visibility='private'),created_by uuid references app_users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_suitable_spare_private on suitable_mappings(spare_part_id,machine_brand,machine_model);
-- A private selling alias points to the SAME physical item/stock. It may carry a premium and packing instruction.
create table if not exists suitable_selling_codes (id uuid primary key default gen_random_uuid(),mapping_id uuid not null references suitable_mappings(id) on delete restrict,source_item_id uuid not null references catalog_items(id) on delete restrict,special_code text not null unique,selling_name text not null,selling_brand text not null default 'TORVO',pricing_mode text not null default 'percent_plus' check(pricing_mode in ('percent_plus','fixed_rate')),markup_percent numeric check(markup_percent is null or markup_percent>=0),fixed_rate_a numeric check(fixed_rate_a is null or fixed_rate_a>=0),fixed_rate_b numeric check(fixed_rate_b is null or fixed_rate_b>=0),fixed_rate_c numeric check(fixed_rate_c is null or fixed_rate_c>=0),packing_mode text not null default 'torvo' check(packing_mode in ('original','torvo','repack','other')),packing_instruction text,active boolean not null default true,created_by uuid references app_users(id),created_at timestamptz not null default now(),check((pricing_mode='percent_plus' and markup_percent is not null) or(pricing_mode='fixed_rate' and fixed_rate_a is not null and fixed_rate_b is not null and fixed_rate_c is not null)));
create index if not exists idx_suitable_code_source on suitable_selling_codes(source_item_id,active);
-- Records every special-code sale resolution so packing/source/rate decisions remain auditable without duplicating physical stock.
create table if not exists suitable_sale_resolutions (id uuid primary key default gen_random_uuid(),selling_code_id uuid not null references suitable_selling_codes(id) on delete restrict,sales_document_line_id uuid references sales_document_lines(id) on delete restrict,source_item_id uuid not null references catalog_items(id) on delete restrict,normal_rate numeric not null check(normal_rate>=0),resolved_rate numeric not null check(resolved_rate>=0),packing_mode text not null,created_by uuid references app_users(id),created_at timestamptz not null default now());
-- Dealer Missing Spare Part Request.
create table if not exists missing_part_requests (id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id) on delete restrict,photo_url text not null,machine_brand text,machine_model text,part_name text,requested_qty numeric check(requested_qty is null or requested_qty>0),dealer_message text,status text not null default 'new' check(status in ('new','reviewing','identified','mapped','replied','closed')),identified_item_id uuid references catalog_items(id) on delete restrict,internal_notes text,reply_text text,handled_by uuid references app_users(id),handled_at timestamptz,created_at timestamptz not null default now());
create index if not exists idx_missing_part_status_created on missing_part_requests(status,created_at desc);
create index if not exists idx_missing_part_dealer_created on missing_part_requests(dealer_id,created_at desc);
create table if not exists inventory (item_id uuid primary key references catalog_items(id) on delete restrict,current_qty numeric not null default 0,reorder_level numeric not null default 0,updated_at timestamptz not null default now());
create table if not exists suppliers (id uuid primary key default gen_random_uuid(),supplier_name text not null,company_name text,mobile text,whatsapp text,city text,gstin text,active boolean not null default true,created_at timestamptz not null default now());
create unique index if not exists idx_supplier_name_company_uq on suppliers(upper(btrim(supplier_name)),upper(coalesce(btrim(company_name),'')));
create table if not exists purchase_headers (id uuid primary key default gen_random_uuid(),supplier_id uuid not null references suppliers(id) on delete restrict,invoice_no text not null,invoice_date date not null,total_reference_amount numeric not null default 0,created_by uuid references app_users(id),created_at timestamptz not null default now(),unique(supplier_id,invoice_no));
create table if not exists purchase_lines (id uuid primary key default gen_random_uuid(),purchase_id uuid not null references purchase_headers(id) on delete restrict,item_id uuid not null references catalog_items(id) on delete restrict,qty numeric not null check(qty>0),purchase_rate numeric not null check(purchase_rate>=0),line_amount numeric generated always as(qty*purchase_rate) stored);
create index if not exists idx_purchase_lines_item on purchase_lines(item_id,purchase_id);
create table if not exists stock_conversions (id uuid primary key default gen_random_uuid(),source_item_id uuid not null references catalog_items(id) on delete restrict,target_item_id uuid not null references catalog_items(id) on delete restrict,qty numeric not null check(qty>0),reason text not null default 'REPACK / BRAND CONVERSION',created_by uuid references app_users(id),created_at timestamptz not null default now(),check(source_item_id<>target_item_id));
create table if not exists sales_documents (id uuid primary key default gen_random_uuid(),dealer_id uuid not null references dealers(id) on delete restrict,doc_type text not null check(doc_type in ('query','quotation','sales_order','estimate')),status text not null default 'draft',parent_id uuid references sales_documents(id),subtotal numeric not null default 0,freight numeric not null default 0,other_charges numeric not null default 0,final_payable numeric not null default 0,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists sales_document_lines (id uuid primary key default gen_random_uuid(),document_id uuid not null references sales_documents(id) on delete cascade,item_id uuid not null references catalog_items(id) on delete restrict,qty numeric not null check(qty>0),rate numeric,amount numeric);
alter table sales_documents add column if not exists root_order_id uuid references sales_documents(id) on delete restrict;
alter table sales_documents add column if not exists revision_no integer not null default 1;
alter table sales_documents add column if not exists dealer_modification_limit integer not null default 2;
alter table sales_documents add column if not exists dealer_modifications_used integer not null default 0;
alter table sales_documents add column if not exists dealer_ok_revision integer;
alter table sales_documents add column if not exists dealer_ok_at timestamptz;
alter table sales_documents add column if not exists estimate_created_at timestamptz;
alter table sales_documents add column if not exists locked_at timestamptz;
alter table sales_documents add column if not exists lock_reason text;
create table if not exists sales_order_revisions (id uuid primary key default gen_random_uuid(),sales_order_id uuid not null references sales_documents(id) on delete restrict,revision_no integer not null,changed_by uuid references app_users(id),actor_role text not null,change_reason text not null,before_data jsonb not null default '{}'::jsonb,after_data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(sales_order_id,revision_no));
create table if not exists sales_modification_requests (id uuid primary key default gen_random_uuid(),sales_order_id uuid not null references sales_documents(id) on delete restrict,dealer_id uuid not null references dealers(id) on delete restrict,reason text not null,status text not null default 'requested' check(status in ('requested','allowed','rejected','used','cancelled')),extra_chances integer not null default 0,decided_by uuid references app_users(id),decided_at timestamptz,created_at timestamptz not null default now());
create table if not exists payments (id uuid primary key default gen_random_uuid(),estimate_id uuid not null references sales_documents(id) on delete restrict,status text not null check(status in ('cash','pending','received')),amount numeric not null default 0,received_at timestamptz,recorded_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists payment_revisions (id uuid primary key default gen_random_uuid(),payment_id uuid not null references payments(id) on delete restrict,old_status text,old_amount numeric,new_status text,new_amount numeric,reason text not null,changed_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists accounting_balances (id uuid primary key default gen_random_uuid(),estimate_id uuid not null references sales_documents(id) on delete restrict,dealer_id uuid not null references dealers(id) on delete restrict,balance_amount numeric not null check(balance_amount>0),status text not null default 'pending' check(status in ('pending','accounting_entered')),accounting_entry_no text,accounting_entered_at timestamptz,accounting_entered_by uuid references app_users(id),remarks text,created_at timestamptz not null default now(),check((status='pending' and accounting_entry_no is null) or(status='accounting_entered' and nullif(btrim(accounting_entry_no),'') is not null)));
create index if not exists idx_accounting_balances_pending on accounting_balances(status,created_at desc);
create table if not exists dispatches (id uuid primary key default gen_random_uuid(),estimate_id uuid not null unique references sales_documents(id) on delete restrict,status text not null default 'pick_list' check(status in('pick_list','picked','packed','ready_for_dispatch','delivered')),tracking_code text,delivered_at timestamptz,stock_deducted_at timestamptz,updated_by uuid references app_users(id));
create table if not exists inventory_movements (id uuid primary key default gen_random_uuid(),item_id uuid not null references catalog_items(id),qty_change numeric not null,reason text not null,reference_type text,reference_id uuid,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table if not exists audit_log (id bigint generated always as identity primary key,actor_id uuid references app_users(id),action text not null,entity_type text not null,entity_id text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
