-- TORVO V2 ADMIN / ACCOUNTANT SHARED-EMAIL OTP AUTH
-- Trusted-worker only. Plain OTP is never stored. One shared security email may serve multiple User IDs.
create extension if not exists pgcrypto;
create table if not exists staff_email_otp_challenges(id uuid primary key default gen_random_uuid(),app_user_id uuid not null references app_users(id) on delete cascade,email_normalized text not null,otp_hash text not null,device_id text not null,created_at timestamptz not null default now(),expires_at timestamptz not null,resend_after timestamptz not null,consumed_at timestamptz,revoked_at timestamptz,failed_attempts integer not null default 0 check(failed_attempts between 0 and 5));
create index if not exists idx_staff_email_otp_active on staff_email_otp_challenges(app_user_id,created_at desc);
alter table staff_email_otp_challenges enable row level security;revoke all on staff_email_otp_challenges from public,anon,authenticated;
create or replace function staff_email_otp_begin(p_email text,p_username text,p_device_id text,p_otp text) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$declare i staff_access_identities%rowtype;rid uuid;e text:=lower(btrim(coalesce(p_email,'')));d text:=btrim(coalesce(p_device_id,''));begin if e !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' or length(d)<8 or length(d)>180 or p_otp !~ '^[0-9]{6}$' then raise exception 'INVALID LOGIN';end if;select i.* into i from staff_access_identities i join app_users a on a.id=i.app_user_id where upper(i.username)=upper(btrim(coalesce(p_username,''))) and i.active=true and a.active=true and lower(coalesce(a.role,'')) in('admin','accountant') and lower(coalesce(i.staff_role,''))=lower(a.role);if i.app_user_id is null then raise exception 'INVALID LOGIN';end if;perform 1 from staff_authorized_devices where app_user_id=i.app_user_id and device_id=d and device_type='desktop' and revoked_at is null;if not found then raise exception 'DEVICE APPROVAL REQUIRED';end if;if exists(select 1 from staff_email_otp_challenges c where c.app_user_id=i.app_user_id and c.device_id=d and c.revoked_at is null and c.consumed_at is null and c.resend_after>now()) then raise exception 'RESEND WAIT REQUIRED';end if;update staff_email_otp_challenges set revoked_at=now() where app_user_id=i.app_user_id and consumed_at is null and revoked_at is null;insert into staff_email_otp_challenges(app_user_id,email_normalized,otp_hash,device_id,expires_at,resend_after) values(i.app_user_id,e,crypt(p_otp,gen_salt('bf')),d,now()+interval '10 minutes',now()+interval '45 seconds') returning id into rid;return rid;end$$;
create or replace function staff_email_otp_verify(p_challenge_id uuid,p_email text,p_username text,p_device_id text,p_otp text) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$declare c staff_email_otp_challenges%rowtype;i staff_access_identities%rowtype;begin select * into c from staff_email_otp_challenges where id=p_challenge_id for update;if c.id is null or c.consumed_at is not null or c.revoked_at is not null or c.expires_at<=now() or c.failed_attempts>=5 or c.device_id<>btrim(coalesce(p_device_id,'')) or c.email_normalized<>lower(btrim(coalesce(p_email,''))) then raise exception 'INVALID OR EXPIRED OTP';end if;select * into i from staff_access_identities where app_user_id=c.app_user_id and upper(username)=upper(btrim(coalesce(p_username,''))) and active=true;if i.app_user_id is null then raise exception 'INVALID OR EXPIRED OTP';end if;if crypt(coalesce(p_otp,''),c.otp_hash)<>c.otp_hash then update staff_email_otp_challenges set failed_attempts=failed_attempts+1,revoked_at=case when failed_attempts+1>=5 then now() else revoked_at end where id=c.id;raise exception 'INVALID OR EXPIRED OTP';end if;update staff_email_otp_challenges set consumed_at=now() where id=c.id;return c.app_user_id;end$$;
revoke all on function staff_email_otp_begin(text,text,text,text) from public,anon,authenticated;revoke all on function staff_email_otp_verify(uuid,text,text,text,text) from public,anon,authenticated;grant execute on function staff_email_otp_begin(text,text,text,text) to service_role;grant execute on function staff_email_otp_verify(uuid,text,text,text,text) to service_role;
