-- TORVO V2 SALES ORDER REVISION + DEALER OK + DEALER SELF-MODIFICATION + LINKED ADD-ON ORDER CONTROL
-- Depends on v2-schema.sql, v2-dealer-link.sql, v2-sales-team-mapping.sql and v2-salesman-assisted-workflows.sql.
-- Staging runtime verification required before production.

alter table sales_documents add column if not exists dealer_self_modify_limit integer not null default 2 check(dealer_self_modify_limit>=0);
alter table sales_documents add column if not exists dealer_self_modify_used integer not null default 0 check(dealer_self_modify_used>=0);
alter table sales_documents add column if not exists add_on_parent_order_id uuid references sales_documents(id) on delete restrict;
create index if not exists idx_sales_documents_add_on_parent on sales_documents(add_on_parent_order_id) where add_on_parent_order_id is not null;
create table if not exists sales_order_change_requests(id uuid primary key default gen_random_uuid(),sales_order_id uuid not null references sales_documents(id) on delete restrict,dealer_id uuid not null references dealers(id) on delete restrict,requested_by uuid not null references app_users(id) on delete restrict,request_type text not null default 'modify_order' check(request_type in('modify_order','add_more_items')),reason text not null,status text not null default 'pending' check(status in('pending','approved','rejected','closed')),admin_note text,reviewed_by uuid references app_users(id) on delete restrict,reviewed_at timestamptz,created_at timestamptz not null default now());
alter table sales_order_change_requests add column if not exists linked_add_on_order_id uuid references sales_documents(id) on delete restrict;
create unique index if not exists uq_sales_change_request_add_on on sales_order_change_requests(linked_add_on_order_id) where linked_add_on_order_id is not null;
create index if not exists idx_sales_change_requests_order on sales_order_change_requests(sales_order_id,status,created_at desc);
alter table sales_order_change_requests enable row level security;revoke all on table sales_order_change_requests from anon,authenticated;
drop policy if exists sales_change_request_admin_read on sales_order_change_requests;drop policy if exists sales_change_request_dealer_read on sales_order_change_requests;
create policy sales_change_request_admin_read on sales_order_change_requests for select to authenticated using(exists(select 1 from app_users u where u.auth_user_id=auth.uid() and u.active=true and u.role in('owner','admin','accountant')));
create policy sales_change_request_dealer_read on sales_order_change_requests for select to authenticated using(dealer_id=(select u.dealer_id from app_users u where u.auth_user_id=auth.uid() and u.active=true and u.role='dealer'));
grant select on table sales_order_change_requests to authenticated;

create or replace function torvo_replace_sales_order_lines(p_sales_order uuid,p_rate_group text,p_lines jsonb) returns numeric language plpgsql security definer set search_path=public as $$declare ln jsonb;iid uuid;q numeric;r numeric;sub numeric:=0;begin if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'Order items required';end if;create temporary table if not exists pg_temp.torvo_revision_lines(item_id uuid,qty numeric,rate numeric,amount numeric) on commit drop;truncate pg_temp.torvo_revision_lines;for ln in select * from jsonb_array_elements(p_lines) loop begin iid:=(ln->>'item_id')::uuid;q:=(ln->>'qty')::numeric;exception when others then raise exception 'Invalid order line';end;if q is null or q<=0 then raise exception 'Invalid quantity';end if;perform 1 from catalog_items where id=iid and active=true;if not found then raise exception 'Item unavailable';end if;select selling_rate into r from item_rates where item_id=iid and rate_group=p_rate_group and min_qty<=q order by min_qty desc limit 1;if r is null then raise exception 'Rate unavailable for revised quantity';end if;insert into pg_temp.torvo_revision_lines values(iid,q,r,round(q*r,2));sub:=sub+round(q*r,2);end loop;delete from sales_document_lines where document_id=p_sales_order;insert into sales_document_lines(document_id,item_id,qty,rate,amount) select p_sales_order,item_id,qty,rate,amount from pg_temp.torvo_revision_lines;return sub;end;$$;
revoke all on function torvo_replace_sales_order_lines(uuid,text,jsonb) from public,anon,authenticated;

create or replace function revise_sales_order(p_sales_order uuid,p_lines jsonb,p_reason text) returns integer language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;d sales_documents%rowtype;sub numeric;rev integer;rg text;before_json jsonb;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant') then raise exception 'Owner/Admin/Accountant required';end if;if nullif(trim(p_reason),'') is null then raise exception 'Revision reason required';end if;select * into d from sales_documents where id=p_sales_order and doc_type='sales_order' for update;if not found then raise exception 'Sales Order not found';end if;if exists(select 1 from sales_documents e where e.doc_type='estimate' and e.root_order_id=p_sales_order) then raise exception 'Estimate already exists; direct Sales Order revision is locked';end if;select rate_group into rg from dealers where id=d.dealer_id and status='approved';if rg is null then raise exception 'Approved Dealer rate group required';end if;select coalesce(jsonb_agg(jsonb_build_object('item_id',item_id,'qty',qty,'rate',rate,'amount',amount) order by id),'[]'::jsonb) into before_json from sales_document_lines where document_id=p_sales_order;sub:=torvo_replace_sales_order_lines(p_sales_order,rg,p_lines);rev:=coalesce(d.revision_no,1)+1;update sales_documents set subtotal=sub,final_payable=sub,revision_no=rev,status='revision_pending_dealer_ok',dealer_ok_revision=null,dealer_ok_at=null where id=p_sales_order;insert into sales_order_revisions(sales_order_id,revision_no,changed_by,actor_role,change_reason,before_data,after_data)values(p_sales_order,rev,a.id,a.role,upper(trim(p_reason)),jsonb_build_object('subtotal',d.subtotal,'status',d.status,'revision_no',d.revision_no,'lines',before_json),jsonb_build_object('subtotal',sub,'status','revision_pending_dealer_ok','revision_no',rev,'lines',(select coalesce(jsonb_agg(jsonb_build_object('item_id',item_id,'qty',qty,'rate',rate,'amount',amount)),'[]'::jsonb) from pg_temp.torvo_revision_lines)));insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'SALES_ORDER_REVISED','sales_order',p_sales_order::text,jsonb_build_object('revision_no',rev,'reason',upper(trim(p_reason)),'dealer_ok_invalidated',true));return rev;end;$$;

create or replace function dealer_revise_sales_order(p_sales_order uuid,p_lines jsonb,p_reason text) returns integer language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;d sales_documents%rowtype;sub numeric;rev integer;rg text;before_json jsonb;begin select * into a from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found or a.dealer_id is null then raise exception 'Linked Dealer login required';end if;if nullif(trim(p_reason),'') is null then raise exception 'Revision reason required';end if;select * into d from sales_documents where id=p_sales_order and doc_type='sales_order' for update;if not found or d.dealer_id<>a.dealer_id then raise exception 'Sales Order not available';end if;if exists(select 1 from sales_documents e where e.doc_type='estimate' and e.root_order_id=p_sales_order) then raise exception 'Estimate already exists; request modification from TORVO';end if;if d.dealer_self_modify_used>=d.dealer_self_modify_limit then raise exception 'Direct modification allowance exhausted; send a modification request';end if;select rate_group into rg from dealers where id=d.dealer_id and status='approved';if rg is null then raise exception 'Approved Dealer rate group required';end if;select coalesce(jsonb_agg(jsonb_build_object('item_id',item_id,'qty',qty,'rate',rate,'amount',amount) order by id),'[]'::jsonb) into before_json from sales_document_lines where document_id=p_sales_order;sub:=torvo_replace_sales_order_lines(p_sales_order,rg,p_lines);rev:=coalesce(d.revision_no,1)+1;update sales_documents set subtotal=sub,final_payable=sub,revision_no=rev,status='revision_pending_dealer_ok',dealer_ok_revision=null,dealer_ok_at=null,dealer_self_modify_used=dealer_self_modify_used+1 where id=p_sales_order;insert into sales_order_revisions(sales_order_id,revision_no,changed_by,actor_role,change_reason,before_data,after_data)values(p_sales_order,rev,a.id,'dealer',upper(trim(p_reason)),jsonb_build_object('subtotal',d.subtotal,'status',d.status,'revision_no',d.revision_no,'lines',before_json),jsonb_build_object('subtotal',sub,'status','revision_pending_dealer_ok','revision_no',rev,'dealer_self_modify_used',d.dealer_self_modify_used+1,'lines',(select coalesce(jsonb_agg(jsonb_build_object('item_id',item_id,'qty',qty,'rate',rate,'amount',amount)),'[]'::jsonb) from pg_temp.torvo_revision_lines)));insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'DEALER_SALES_ORDER_REVISED','sales_order',p_sales_order::text,jsonb_build_object('revision_no',rev,'used',d.dealer_self_modify_used+1,'limit',d.dealer_self_modify_limit,'reason',upper(trim(p_reason))));return rev;end;$$;

create or replace function dealer_request_sales_order_change(p_sales_order uuid,p_type text,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;d sales_documents%rowtype;rid uuid;begin select * into a from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found or a.dealer_id is null then raise exception 'Linked Dealer login required';end if;if p_type not in('modify_order','add_more_items') or nullif(trim(p_reason),'') is null then raise exception 'Valid request type and reason required';end if;select * into d from sales_documents where id=p_sales_order and doc_type='sales_order';if not found or d.dealer_id<>a.dealer_id then raise exception 'Sales Order not available';end if;if exists(select 1 from sales_order_change_requests where sales_order_id=p_sales_order and dealer_id=a.dealer_id and request_type=p_type and status='pending') then raise exception 'A pending request already exists';end if;insert into sales_order_change_requests(sales_order_id,dealer_id,requested_by,request_type,reason)values(p_sales_order,a.dealer_id,a.id,p_type,upper(trim(p_reason))) returning id into rid;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'DEALER_SALES_CHANGE_REQUESTED','sales_order_change_request',rid::text,jsonb_build_object('sales_order_id',p_sales_order,'request_type',p_type));return rid;end;$$;

create or replace function review_sales_order_change_request(p_request uuid,p_status text,p_admin_note text default null,p_extra_modify_chance boolean default false) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;r sales_order_change_requests%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant') then raise exception 'Owner/Admin/Accountant required';end if;if p_status not in('approved','rejected','closed') then raise exception 'Invalid review status';end if;select * into r from sales_order_change_requests where id=p_request for update;if not found or r.status<>'pending' then raise exception 'Pending request required';end if;if p_extra_modify_chance and (p_status<>'approved' or r.request_type<>'modify_order') then raise exception 'Extra modification chance requires approved modify request';end if;update sales_order_change_requests set status=p_status,admin_note=nullif(trim(p_admin_note),''),reviewed_by=a.id,reviewed_at=now() where id=p_request;if p_extra_modify_chance then update sales_documents set dealer_self_modify_limit=dealer_self_modify_limit+1 where id=r.sales_order_id and doc_type='sales_order';end if;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'SALES_CHANGE_REQUEST_REVIEWED','sales_order_change_request',r.id::text,jsonb_build_object('status',p_status,'extra_modify_chance',p_extra_modify_chance,'sales_order_id',r.sales_order_id));end;$$;

create or replace function dealer_create_add_on_order(p_request uuid,p_lines jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;r sales_order_change_requests%rowtype;parent sales_documents%rowtype;rg text;new_id uuid;sub numeric;begin select * into a from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found or a.dealer_id is null then raise exception 'Linked Dealer login required';end if;select * into r from sales_order_change_requests where id=p_request for update;if not found or r.dealer_id<>a.dealer_id or r.request_type<>'add_more_items' or r.status<>'approved' then raise exception 'Approved Add More Items request required';end if;if r.linked_add_on_order_id is not null then raise exception 'Add-on order already created for this request';end if;select * into parent from sales_documents where id=r.sales_order_id and doc_type='sales_order';if not found or parent.dealer_id<>a.dealer_id then raise exception 'Parent Sales Order not available';end if;select rate_group into rg from dealers where id=a.dealer_id and status='approved';if rg is null then raise exception 'Approved Dealer rate group required';end if;insert into sales_documents(doc_type,dealer_id,status,subtotal,final_payable,revision_no,dealer_self_modify_limit,dealer_self_modify_used,add_on_parent_order_id)values('sales_order',a.dealer_id,'submitted',0,0,1,2,0,parent.id) returning id into new_id;sub:=torvo_replace_sales_order_lines(new_id,rg,p_lines);update sales_documents set subtotal=sub,final_payable=sub where id=new_id;insert into sales_order_revisions(sales_order_id,revision_no,changed_by,actor_role,change_reason,before_data,after_data)values(new_id,1,a.id,'dealer','ADD MORE ITEMS FROM APPROVED REQUEST','{}'::jsonb,jsonb_build_object('subtotal',sub,'status','submitted','revision_no',1,'add_on_parent_order_id',parent.id,'lines',(select coalesce(jsonb_agg(jsonb_build_object('item_id',item_id,'qty',qty,'rate',rate,'amount',amount)),'[]'::jsonb) from pg_temp.torvo_revision_lines)));update sales_order_change_requests set linked_add_on_order_id=new_id,status='closed' where id=r.id;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'DEALER_ADD_ON_ORDER_CREATED','sales_order',new_id::text,jsonb_build_object('parent_sales_order_id',parent.id,'change_request_id',r.id,'subtotal',sub));return new_id;end;$$;

create or replace function send_sales_order_for_dealer_ok(p_sales_order uuid,p_note text default null) returns integer language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;d sales_documents%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true;if not found or a.role not in('owner','admin','accountant','salesman') then raise exception 'Authorized sales staff required';end if;select * into d from sales_documents where id=p_sales_order and doc_type='sales_order' for update;if not found then raise exception 'Sales Order not found';end if;if a.role='salesman' and not salesman_can_access_dealer(a.id,d.dealer_id) then raise exception 'Dealer is not assigned to this salesman';end if;if exists(select 1 from sales_documents e where e.doc_type='estimate' and e.root_order_id=p_sales_order) then raise exception 'Estimate already exists';end if;if not exists(select 1 from sales_document_lines where document_id=p_sales_order) then raise exception 'Sales Order has no items';end if;update sales_documents set status='awaiting_dealer_ok',dealer_ok_revision=null,dealer_ok_at=null where id=p_sales_order;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'SALES_ORDER_SENT_FOR_DEALER_OK','sales_order',p_sales_order::text,jsonb_build_object('revision_no',coalesce(d.revision_no,1),'note',nullif(trim(p_note),''),'delivery_channel','prepared_not_sent'));return coalesce(d.revision_no,1);end;$$;

create or replace function dealer_confirm_sales_order(p_sales_order uuid,p_revision integer) returns void language plpgsql security definer set search_path=public as $$declare a app_users%rowtype;d sales_documents%rowtype;begin select * into a from app_users where auth_user_id=auth.uid() and active=true and role='dealer';if not found or a.dealer_id is null then raise exception 'Linked Dealer login required';end if;select * into d from sales_documents where id=p_sales_order and doc_type='sales_order' for update;if not found or d.dealer_id<>a.dealer_id then raise exception 'Sales Order not available';end if;if d.status<>'awaiting_dealer_ok' then raise exception 'Sales Order is not awaiting Dealer OK';end if;if coalesce(d.revision_no,1)<>p_revision then raise exception 'Revision changed; review latest Sales Order';end if;if exists(select 1 from sales_documents e where e.doc_type='estimate' and e.root_order_id=p_sales_order) then raise exception 'Estimate already exists';end if;update sales_documents set status='dealer_ok',dealer_ok_revision=p_revision,dealer_ok_at=now() where id=p_sales_order;insert into audit_log(actor_id,action,entity_type,entity_id,details)values(a.id,'DEALER_CONFIRMED_SALES_ORDER','sales_order',p_sales_order::text,jsonb_build_object('revision_no',p_revision,'confirmed_at',now()));end;$$;

revoke all on function revise_sales_order(uuid,jsonb,text),dealer_revise_sales_order(uuid,jsonb,text),dealer_request_sales_order_change(uuid,text,text),review_sales_order_change_request(uuid,text,text,boolean),dealer_create_add_on_order(uuid,jsonb),send_sales_order_for_dealer_ok(uuid,text),dealer_confirm_sales_order(uuid,integer) from public,anon;
grant execute on function revise_sales_order(uuid,jsonb,text),dealer_revise_sales_order(uuid,jsonb,text),dealer_request_sales_order_change(uuid,text,text),review_sales_order_change_request(uuid,text,text,boolean),dealer_create_add_on_order(uuid,jsonb),send_sales_order_for_dealer_ok(uuid,text),dealer_confirm_sales_order(uuid,integer) to authenticated;
