from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
old='''<div class="field torvoBrandField"><label>BRAND *</label><div class="masterRow"><input id="pBrand" class="upper" list="brandList"><button class="mini" type="button" onclick="torvoOpenBrandManager()">+</button><button class="mini" type="button" onclick="torvoToggleBrandDropdown()">▼</button></div><div id="torvoBrandDropdown" class="torvoBrandDropdown"></div></div>'''
new='''<div class="field torvoBrandField"><label>BRAND *</label><div class="masterRow torvoBrandMasterRow"><div class="torvoBrandInputWrap"><input id="pBrand" class="upper" list="brandList"><button class="torvoBrandDropBtn" type="button" onclick="torvoToggleBrandDropdown()" title="Select Brand">▼</button></div><button class="mini torvoBrandAddBtn" type="button" onclick="torvoOpenBrandManager()" title="Manage Brand">+</button></div><div id="torvoBrandDropdown" class="torvoBrandDropdown"></div></div>'''
assert s.count(old)==1, 'Current Brand row mismatch'
s=s.replace(old,new,1)
old_render='''function torvoRenderBrands(){var q=N(E("torvoBrandSearch")?E("torvoBrandSearch").value:"");var a=torvoBrandNames().filter(function(v){return !q||N(v).includes(q)});E("torvoBrandRows").innerHTML=a.length?a.map(function(v){return '<div class="torvoBrandRow"><span>'+H(v)+'</span><div><button type="button" class="edit" data-brand="'+H(v)+'" onclick="torvoEditBrand(this)">EDIT</button><button type="button" class="del" data-brand="'+H(v)+'" onclick="torvoDeleteBrand(this)">DELETE</button></div></div>'}).join(""):'<div class="torvoBrandEmpty">NO BRAND FOUND</div>'}'''
new_render='''function torvoRenderBrands(){var q=N(E("torvoBrandSearch")?E("torvoBrandSearch").value:"");var a=torvoBrandNames().filter(function(v){return !q||N(v).includes(q)});E("torvoBrandRows").innerHTML=a.length?a.map(function(v){return '<div class="torvoBrandRow"><span>'+H(v)+'</span><div><button type="button" class="edit torvoBrandIconBtn" title="Edit" aria-label="Edit" data-brand="'+H(v)+'" onclick="torvoEditBrand(this)">✎</button><button type="button" class="del torvoBrandIconBtn" title="Delete" aria-label="Delete" data-brand="'+H(v)+'" onclick="torvoDeleteBrand(this)">🗑</button></div></div>'}).join(""):'<div class="torvoBrandEmpty">NO BRAND FOUND</div>'}'''
assert s.count(old_render)==1, 'Brand render mismatch'
s=s.replace(old_render,new_render,1)
marker='</style></head>'
extra='''.torvoBrandMasterRow{display:flex;gap:7px;align-items:center}.torvoBrandInputWrap{position:relative;flex:1;min-width:0}.torvoBrandInputWrap>input{width:100%;box-sizing:border-box;padding-right:38px!important}.torvoBrandDropBtn{position:absolute;right:3px;top:50%;transform:translateY(-50%);width:32px;height:32px;border:0;background:transparent;color:#334155;font-size:14px;font-weight:900;cursor:pointer;border-radius:7px}.torvoBrandDropBtn:hover{background:#eef2f7}.torvoBrandAddBtn{background:linear-gradient(135deg,#ef4444,#f97316)!important;color:#fff!important;border:0!important;box-shadow:0 3px 9px rgba(239,68,68,.28);font-size:20px!important;font-weight:900!important}.torvoBrandIconBtn{width:34px;height:32px;padding:0!important;font-size:16px!important;display:inline-flex;align-items:center;justify-content:center}.torvoBrandDropdown{left:0;top:100%;margin-top:4px}'''
assert marker in s, 'Brand style marker missing'
s=s.replace(marker,extra+marker,1)
p.write_text(s,encoding='utf-8')
