from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
marker='/* TORVO SINGLE WINDOW SOFTWARE V15 */'
if marker not in s:
 css='''<style id="torvo-single-window-software-v15">/* TORVO SINGLE WINDOW SOFTWARE V15 */
@media(min-width:761px){
html,body{height:100%!important;overflow:hidden!important}.app{height:100vh!important;min-height:0!important;grid-template-columns:205px minmax(0,1fr) 190px!important;overflow:hidden!important}.left,.right{height:100vh!important;overflow:auto!important}.main{height:100vh!important;min-height:0!important;padding:8px!important;overflow:hidden!important;display:flex!important;flex-direction:column!important}.top{height:56px!important;min-height:56px!important;flex:0 0 56px!important;border-radius:10px!important;padding:7px 10px!important}.section.active{display:flex!important;flex-direction:column!important;min-height:0!important;flex:1 1 auto!important;overflow:hidden!important}.section.active>.panel{display:flex!important;flex-direction:column!important;min-height:0!important;flex:1 1 auto!important;max-height:none!important;overflow:hidden!important;margin-top:7px!important;padding:10px!important}.section.active>.panel>.pTitle{flex:0 0 auto!important;position:relative!important;top:auto!important;padding-top:0!important}.section.active>.panel>.toolbar{flex:0 0 auto!important;position:relative!important;top:auto!important}.section.active>.panel>.grid{min-height:0!important;align-content:start!important;overflow:auto!important;padding-right:3px!important}.section.active>.panel>.scroll{min-height:0!important;flex:1 1 auto!important;max-height:none!important;overflow:auto!important}.section.active>.panel>.itemGrid,.section.active>.panel>.verifyList{min-height:0!important;overflow:auto!important}.box{padding:8px!important}.boxTitle{margin-bottom:6px!important}.grid{gap:6px!important}.field input,.field select{min-height:34px!important;padding:7px 8px!important}.field textarea{min-height:56px!important;padding:7px 8px!important}.pTitle{padding-bottom:7px!important;margin-bottom:7px!important}.toolbar{margin-bottom:6px!important}.cards{gap:7px!important}.card,.dashboardCard{min-height:72px!important;padding:9px!important}.card strong,.dashboardCard strong{font-size:19px!important}.btn{min-height:32px!important;padding:7px 10px!important}.left .nav,.right .rnav{padding:8px 9px!important;margin:2px 0!important}.left .menuTitle,.right .menuTitle{margin-top:7px!important;padding:5px 7px!important}.left .logo{font-size:23px!important;padding:4px 7px!important}.left .sub{padding-bottom:8px!important}.section.active>.panel *{scroll-margin-top:8px}
}
</style>'''
 if '</head>' not in s: raise SystemExit('Head anchor not found')
 s=s.replace('</head>',css+'\n</head>',1)
p.write_text(s,encoding='utf-8')
