from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
marker='TORVO ADMIN STRUCTURAL V26'
if marker in s: raise SystemExit(0)
css='''<style id="torvo-v26">/* TORVO ADMIN STRUCTURAL V26 */
:root{--v26nav:#0b2033;--v26red:#f21f43;--v26bg:#f5f7fb;--v26line:#e1e7ef;--v26text:#17253b}
html,body{background:var(--v26bg)!important}.app{display:grid!important;grid-template-columns:244px minmax(0,1fr)!important;min-height:100vh!important}.left{grid-column:1!important;background:var(--v26nav)!important;border:0!important;height:100vh!important;position:sticky!important;top:0!important;padding:14px 11px!important;z-index:30!important}.main{grid-column:2!important;padding:0 20px 30px!important;background:var(--v26bg)!important;min-width:0!important}.right{display:none!important}.left>.logo,.left>.sub,.left>.menuTitle,.left>.nav{display:none!important}.top{border:0!important;border-bottom:1px solid var(--v26line)!important;border-radius:0!important;box-shadow:none!important;margin:0 -20px 16px!important;padding:10px 20px!important;background:#fff!important}.section{max-width:1500px;margin:auto}.section.active{display:block!important}.section>.panel{background:#fff!important;border:1px solid var(--v26line)!important;border-radius:10px!important;box-shadow:0 2px 10px #10253a0a!important}.v26brand{display:flex;align-items:center;gap:9px;color:#fff;padding:2px 5px 14px;border-bottom:1px solid #20384d}.v26logo{width:38px;height:38px;background:var(--v26red);border-radius:9px;display:grid;place-items:center;font-size:22px;font-weight:900}.v26brand b{font-size:20px}.v26brand small{display:block;color:#91a5b7;font-size:8px}.v26menu{padding-top:10px}.v26nav,.v26sub{display:block;width:100%;border:0;background:transparent;color:#d9e4ee;text-align:left;border-radius:7px;padding:10px 11px;margin:2px 0;font-size:10px;font-weight:800}.v26nav:hover,.v26sub:hover{background:#18364e}.v26nav.active{background:var(--v26red);color:#fff}.v26sub{padding:8px 11px 8px 32px;color:#afc0ce;font-size:9px}.v26group{color:#70879b;font-size:8px;font-weight:900;padding:12px 10px 4px}.v26support{border:1px solid #29455c;border-radius:8px;padding:10px;margin:15px 4px;color:#b8c8d5;font-size:8px}.v26support b{display:block;color:#fff;margin-bottom:4px}.v26mobile{display:none}
#dashboard>*:not(#v23DashboardShell){display:none!important}#v23DashboardShell{display:block!important}.v23Dashboard{grid-template-columns:repeat(4,minmax(150px,1fr))!important;gap:12px!important}.v23Kpi,.v23WorkCard{border:1px solid var(--v26line)!important;border-radius:10px!important;background:#fff!important}.v23Work{grid-template-columns:2fr 1fr!important;gap:12px!important}.v23ActionGrid{gap:8px!important}
@media(max-width:760px){.app{display:block!important}.left{width:100%!important;height:auto!important;min-height:58px!important;position:sticky!important;top:0!important;display:flex!important;align-items:center!important;padding:8px 10px!important}.v26brand{border:0;padding:0}.v26brand small{display:none}.v26mobile{display:block;margin-left:auto;border:0;background:var(--v26red);color:#fff;border-radius:7px;padding:9px 12px;font-weight:900}.v26menu{display:none;position:absolute;left:0;right:0;top:58px;background:var(--v26nav);padding:8px 10px 18px;max-height:calc(100vh - 58px);overflow:auto}.left:focus-within .v26menu{display:block}.main{padding:0 10px 25px!important}.top{margin:0 -10px 12px!important;padding:8px 10px!important;top:58px!important}.v23Dashboard{grid-template-columns:repeat(2,minmax(0,1fr))!important}.v23Work{grid-template-columns:1fr!important}.v23ActionGrid{grid-template-columns:repeat(2,1fr)!important}}
</style>'''
s=s.replace('</head>',css+'\n</head>',1)
nav='''<div class="v26brand"><span class="v26logo">T</span><span><b>TORVO</b><small>ADMIN PANEL</small></span></div><button class="v26mobile" type="button">☰ MENU</button><div class="v26menu"><button class="v26nav active" data-sec="dashboard" onclick="v26Go(this,'dashboard')">⌂ &nbsp; DASHBOARD</button><button class="v26nav" data-sec="market" onclick="v26Go(this,'market')">♙ &nbsp; DEALERS</button><div class="v26group">PRODUCTS</div><button class="v26nav" data-sec="additem" onclick="v26Go(this,'additem')">＋ &nbsp; ADD PRODUCT</button><button class="v26sub" data-sec="itemmaster" onclick="v26Go(this,'itemmaster')">SPARE PARTS</button><button class="v26sub" data-sec="machines" onclick="v26Go(this,'machines')">MACHINES</button><button class="v26sub" data-sec="accessories" onclick="v26Go(this,'accessories')">ACCESSORIES</button><button class="v26nav" onclick="openBrandMaster&&openBrandMaster()">◆ &nbsp; BRANDS</button><button class="v26nav" onclick="openCategoryMaster&&openCategoryMaster()">▦ &nbsp; CATEGORIES</button><div class="v26group">BUSINESS</div><button class="v26nav" data-sec="reports" onclick="v26Go(this,'reports')">▤ &nbsp; REPORTS</button><button class="v26nav" data-sec="settings" onclick="v26Go(this,'settings')">⚙ &nbsp; SETTINGS</button><button class="v26nav" data-sec="employeeAccess" onclick="v26Go(this,'employeeAccess')">♟ &nbsp; EMPLOYEES</button><button class="v26nav" onclick="v26Go(this,'dashboard')">◎ &nbsp; REQUESTS</button><button class="v26nav" onclick="v26Go(this,'dashboard')">✉ &nbsp; MESSAGES</button><button class="v26nav" onclick="v26Go(this,'dashboard')">★ &nbsp; SCHEMES</button><div class="v26group">SYSTEM</div><button class="v26nav" onclick="v26Go(this,'settings')">↻ &nbsp; BACKUP & LOGS</button><button class="v26nav" onclick="v26Go(this,'settings')">? &nbsp; HELP & SUPPORT</button><button class="v26nav" onclick="if(typeof logoutAdmin==='function')logoutAdmin()">⇥ &nbsp; LOGOUT</button><div class="v26support"><b>CUSTOMER SUPPORT</b>7027751533</div></div>'''
import re
m=re.search(r'(<(?:aside|div)[^>]*class="[^"]*left[^"]*"[^>]*>)',s,re.I)
if not m: raise SystemExit('LEFT SHELL NOT FOUND')
s=s[:m.end()]+nav+s[m.end():]
js='''<script>/* TORVO V26 NAV */
function v26Go(btn,sec){if(typeof showSection==='function')showSection(sec);document.querySelectorAll('.v26nav,.v26sub').forEach(function(x){x.classList.remove('active')});if(btn)btn.classList.add('active')}
(function(){try{var sec=localStorage.getItem('TORVO_ADMIN_SECTION')||'dashboard';var b=document.querySelector('.v26menu [data-sec="'+sec+'"]');if(b){document.querySelectorAll('.v26nav,.v26sub').forEach(function(x){x.classList.remove('active')});b.classList.add('active')}}catch(e){}})();
</script>'''
s=s.replace('</body>',js+'\n</body>',1)
p.write_text(s,encoding='utf-8')
