from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
marker='TORVO ADMIN EXACT REFERENCE V25'
if marker not in s:
 css='''<style id="torvo-v25">/* TORVO ADMIN EXACT REFERENCE V25 */
:root{--nav:#0d2235;--red:#f51b3d;--bg:#f4f6fa;--line:#dfe5ed;--text:#17253b}
body{background:var(--bg)!important}.app{grid-template-columns:248px minmax(0,1fr) 0!important}.right{display:none!important}.left{background:var(--nav)!important;padding:15px 12px!important;overflow:auto!important}.main{background:var(--bg)!important;padding:0 20px 30px!important}.top{background:#fff!important;border:0!important;border-bottom:1px solid var(--line)!important;border-radius:0!important;margin:0 -20px 16px!important;padding:10px 20px!important;box-shadow:none!important}.v25brand{display:flex;align-items:center;gap:9px;margin:0 5px 18px;color:#fff}.v25mark{width:39px;height:39px;border-radius:9px;background:var(--red);display:grid;place-items:center;font-size:23px;font-weight:900}.v25brand b{font-size:20px}.v25brand small{display:block;color:#9aabba;font-size:8px}.v25menu{display:block}.v25nav,.v25sub{width:100%;border:0;background:transparent;color:#dbe5ef;text-align:left;border-radius:7px;padding:10px 11px;margin:2px 0;font-size:10px;font-weight:800;cursor:pointer}.v25nav.active{background:var(--red);color:#fff}.v25nav:hover,.v25sub:hover{background:#18344c}.v25sub{padding-left:31px;color:#b9c7d5;font-size:9px}.v25group{color:#71859a;font-size:8px;font-weight:900;padding:11px 10px 4px}.v25support{border:1px solid #294158;border-radius:8px;padding:10px;margin:16px 5px 8px;color:#c8d4df;font-size:8px}.v25support b{display:block;color:#fff;font-size:9px;margin-bottom:4px}.left>.logo,.left>.sub,.left>.menuTitle,.left>.nav{display:none!important}#dashboard>*:not(#v23DashboardShell){display:none!important}#v23DashboardShell{display:block!important}.v23PageHead h1{font-size:21px!important}.v23Dashboard{grid-template-columns:repeat(4,minmax(140px,1fr))!important}.v23Kpi{border-radius:8px!important}.v23Work{grid-template-columns:2fr 1fr!important}.v23WorkCard{border-radius:8px!important}.v25mobilebar{display:none}
@media(max-width:700px){.app{display:block!important}.left{position:sticky!important;top:0!important;z-index:100!important;width:100%!important;height:auto!important;min-height:58px!important;padding:8px 10px!important;overflow:visible!important}.v25brand{margin:0!important}.v25brand small{display:none}.v25mobilebar{display:block!important;margin-left:auto!important;border:0;background:var(--red);color:#fff;border-radius:7px;padding:9px 12px;font-weight:900}.left{display:flex!important;align-items:center!important}.v25menu{display:none;position:absolute;left:0;right:0;top:58px;background:var(--nav);padding:8px 10px 18px;max-height:calc(100vh - 58px);overflow:auto;box-shadow:0 10px 20px #0004}.left:focus-within .v25menu{display:block}.main{padding:0 10px 25px!important}.top{margin:0 -10px 11px!important;padding:7px 10px!important;position:sticky!important;top:58px!important;z-index:80!important}.top .owner,.top .verifyBtn,.top .logout,.top .langBtn{display:none!important}.v23Dashboard{grid-template-columns:repeat(2,minmax(0,1fr))!important}.v23Work{grid-template-columns:1fr!important}.v23ActionGrid{grid-template-columns:repeat(2,1fr)!important}.v23PageHead h1{font-size:18px!important}}
</style>'''
 s=s.replace('</head>',css+'\n</head>',1)
 # Actual new sidebar markup. Existing legacy sidebar stays in DOM but is hidden, so its handlers/logic remain intact.
 sidebar='''<div class="v25brand"><span class="v25mark">T</span><span><b>TORVO</b><small>ADMIN PANEL</small></span></div><button class="v25mobilebar" type="button">☰ MENU</button><div class="v25menu"><button class="v25nav active" onclick="showSection('dashboard')">⌂ &nbsp; DASHBOARD</button><button class="v25nav" onclick="showSection('market')">♙ &nbsp; DEALERS</button><div class="v25group">PRODUCTS</div><button class="v25nav" onclick="showSection('additem')">＋ &nbsp; ADD PRODUCT</button><button class="v25sub" onclick="showSection('itemmaster')">SPARE PARTS</button><button class="v25sub" onclick="showSection('machine')">MACHINES</button><button class="v25sub" onclick="showSection('accessories')">ACCESSORIES</button><button class="v25nav" onclick="showSection('brands')">◆ &nbsp; BRANDS</button><button class="v25nav" onclick="showSection('categories')">▦ &nbsp; CATEGORIES</button><div class="v25group">SALES</div><button class="v25nav" onclick="showSection('orders')">▣ &nbsp; ORDERS</button><button class="v25sub" onclick="showSection('quotation')">QUOTATION</button><button class="v25sub" onclick="showSection('salesorder')">SALES ORDER</button><button class="v25sub" onclick="showSection('estimates')">ESTIMATES</button><button class="v25nav" onclick="showSection('reports')">▤ &nbsp; REPORTS</button><button class="v25nav" onclick="showSection('requests')">◎ &nbsp; REQUESTS</button><button class="v25nav" onclick="showSection('messages')">✉ &nbsp; MESSAGES</button><button class="v25nav" onclick="showSection('schemes')">★ &nbsp; SCHEMES</button><div class="v25group">SYSTEM</div><button class="v25nav" onclick="showSection('settings')">⚙ &nbsp; SETTINGS</button><button class="v25nav" onclick="showSection('employeeAccess')">♟ &nbsp; EMPLOYEES</button><button class="v25nav" onclick="showSection('recycle')">↻ &nbsp; BACKUP & LOGS</button><button class="v25nav" onclick="showSection('help')">? &nbsp; HELP & SUPPORT</button><button class="v25nav" onclick="logoutAdmin&&logoutAdmin()">⇥ &nbsp; LOGOUT</button><div class="v25support"><b>CUSTOMER SUPPORT</b>7027751533</div></div>'''
 # inject as first child of real left sidebar
 import re
 m=re.search(r'(<(?:aside|div)[^>]*class="[^"]*left[^"]*"[^>]*>)',s,re.I)
 if m:s=s[:m.end()]+sidebar+s[m.end():]
 # Fix dashboard top action so it opens the known existing Add Item section in legacy build.
 s=s.replace("showSection('additem')\">+ ADD PRODUCT", "showSection('additem')\">+ ADD PRODUCT")
p.write_text(s,encoding='utf-8')
