from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
marker='function torvoEditCategory(btn)'
if marker not in s:
    old='''function torvoRenderCategories(){var q=N(E("torvoCategorySearch")?E("torvoCategorySearch").value:"");var a=torvoCategoryNames().filter(function(v){return !q||N(v).includes(q)});E("torvoCategoryRows").innerHTML=a.length?a.map(function(v){return '<div class="torvoBrandRow"><span>'+H(v)+'</span></div>'}).join(""):'<div class="torvoBrandEmpty">NO CATEGORY FOUND</div>'}'''
    new='''function torvoRenderCategories(){var q=N(E("torvoCategorySearch")?E("torvoCategorySearch").value:"");var a=torvoCategoryNames().filter(function(v){return !q||N(v).includes(q)});E("torvoCategoryRows").innerHTML=a.length?a.map(function(v){return '<div class="torvoBrandRow"><span>'+H(v)+'</span><button type="button" class="torvoBrandEdit" data-v="'+H(v)+'" onclick="torvoEditCategory(this)" title="Edit">✎</button><button type="button" class="torvoBrandDelete" data-v="'+H(v)+'" onclick="torvoDeleteCategory(this)" title="Delete">🗑</button></div>'}).join(""):'<div class="torvoBrandEmpty">NO CATEGORY FOUND</div>'}
function torvoEditCategory(btn){var old=U(btn.getAttribute("data-v")||"");if(!old)return;var use=masterUsage("category",old);if(use>0)return torvoCategoryMessage("USED IN "+use+" RECORD(S) — CORRECT LINKED ITEM FIRST",true);var n=E("torvoCategoryNew");n.value=old;n.focus();n.setAttribute("data-edit",old);torvoCategoryMessage("EDIT NAME ABOVE, THEN PRESS + ADD",false)}
function torvoDeleteCategory(btn){var v=U(btn.getAttribute("data-v")||"");if(!v)return;var use=masterUsage("category",v);if(use>0)return torvoCategoryMessage("DELETE BLOCKED — USED IN "+use+" RECORD(S)",true);var code=E("torvoCategoryNew");if((code.value||"").trim()!=="1122"){code.value="";code.placeholder="ENTER DELETE CODE 1122";code.focus();code.setAttribute("data-delete",v);return torvoCategoryMessage("ENTER DELETE CODE 1122 ABOVE, THEN TAP DELETE AGAIN",true)}DB.categories=(DB.categories||[]).filter(function(x){return N(x)!==N(v)});code.removeAttribute("data-delete");code.value="";code.placeholder="ADD CATEGORY NAME";if(E("pCategory")&&N(E("pCategory").value)===N(v))E("pCategory").value="";logActivity("MASTER DELETED: "+v);saveDB();torvoCategoryMessage("CATEGORY DELETED — "+v,false);torvoRenderCategories()}'''
    if old not in s: raise SystemExit('Current Category renderer not found; no change made')
    s=s.replace(old,new,1)
    oldadd='''function torvoAddCategory(){var v=U((E("torvoCategoryNew").value||"").trim());if(!v)return torvoCategoryMessage("ENTER CATEGORY NAME",true);if(torvoCategoryNames().some(function(x){return N(x)===N(v)}))return torvoCategoryMessage("CATEGORY ALREADY EXISTS",true);DB.categories=DB.categories||[];DB.categories.push(v);if(E("pCategory"))E("pCategory").value=v;logActivity("MASTER ADDED: "+v);saveDB();E("torvoCategoryNew").value="";torvoCategoryMessage("✓ SUCCESSFUL — "+v+" ADDED",false);torvoRenderCategories()}'''
    newadd='''function torvoAddCategory(){var n=E("torvoCategoryNew"),v=U((n.value||"").trim()),old=U(n.getAttribute("data-edit")||"");if(!v)return torvoCategoryMessage("ENTER CATEGORY NAME",true);if(old){if(torvoCategoryNames().some(function(x){return N(x)===N(v)&&N(x)!==N(old)}))return torvoCategoryMessage("CATEGORY ALREADY EXISTS",true);DB.categories=(DB.categories||[]).map(function(x){return N(x)===N(old)?v:x});n.removeAttribute("data-edit");if(E("pCategory")&&N(E("pCategory").value)===N(old))E("pCategory").value=v;logActivity("MASTER EDITED: "+old+" → "+v);saveDB();n.value="";torvoCategoryMessage("✓ SUCCESSFUL — "+v+" UPDATED",false);return torvoRenderCategories()}if(torvoCategoryNames().some(function(x){return N(x)===N(v)}))return torvoCategoryMessage("CATEGORY ALREADY EXISTS",true);DB.categories=DB.categories||[];DB.categories.push(v);if(E("pCategory"))E("pCategory").value=v;logActivity("MASTER ADDED: "+v);saveDB();n.value="";torvoCategoryMessage("✓ SUCCESSFUL — "+v+" ADDED",false);torvoRenderCategories()}'''
    if oldadd not in s: raise SystemExit('Current Category add function not found; no change made')
    s=s.replace(oldadd,newadd,1)
    css='''<style id="torvo-category-popup-position-v7">#torvoCategoryManager.torvoBrandOverlay{align-items:flex-start!important;padding-top:18vh!important}.torvoBrandRow{display:grid!important;grid-template-columns:minmax(0,1fr) 34px 34px!important;align-items:center!important}.torvoBrandEdit,.torvoBrandDelete{width:30px!important;height:30px!important;border:0!important;border-radius:6px!important;background:#eef5ff!important;color:#1268d5!important;font-weight:900!important}.torvoBrandDelete{background:#fff0f1!important;color:#d71920!important}@media(max-width:700px){#torvoCategoryManager.torvoBrandOverlay{padding-top:12vh!important;align-items:flex-start!important}}</style>'''
    if '</head>' not in s: raise SystemExit('Head anchor not found; no change made')
    s=s.replace('</head>',css+'\n</head>',1)
p.write_text(s,encoding='utf-8')
