export const ROLES=Object.freeze({OWNER:'owner',ADMIN:'admin',SALESMAN:'salesman',ACCOUNTANT:'accountant',STORE_KEEPER:'store_keeper',DEALER:'dealer'});
export const EXPERIENCE=Object.freeze({PUBLIC_WEBSITE:'public_website',OPERATIONAL_APP:'operational_app',SECURE_DESKTOP:'secure_desktop'});
export const ROLE_EXPERIENCE=Object.freeze({owner:EXPERIENCE.SECURE_DESKTOP,admin:EXPERIENCE.SECURE_DESKTOP,accountant:EXPERIENCE.SECURE_DESKTOP,dealer:EXPERIENCE.OPERATIONAL_APP,salesman:EXPERIENCE.OPERATIONAL_APP,store_keeper:EXPERIENCE.OPERATIONAL_APP});
export const OPERATIONAL_APP_ROLES=Object.freeze(['dealer','salesman','store_keeper']);
export const SECURE_DESKTOP_ROLES=Object.freeze(['owner','admin','accountant']);
export const MODULES=[
{id:'dashboard',label:'Dashboard',roles:['owner','admin','salesman','accountant','store_keeper']},{id:'dealers',label:'Dealer Management',roles:['owner','admin','salesman']},{id:'dealer-requests',label:'Dealer Requests',roles:['owner','admin']},{id:'sales-team',label:'Sales Team',roles:['owner','admin']},{id:'sales',label:'Sales Workspace',roles:['owner','admin','salesman']},{id:'payments',label:'Payments & Accounts',roles:['owner','admin','accountant']},{id:'approvals',label:'Approval Center',roles:['owner','admin','accountant']},{id:'returns',label:'Sales & Purchase Returns',roles:['owner','admin','accountant','store_keeper']},{id:'machines',label:'Machines',roles:['owner','admin','salesman']},{id:'spare-parts',label:'Spare Parts',roles:['owner','admin','salesman']},{id:'accessories',label:'Accessories',roles:['owner','admin','salesman']},{id:'compatibility',label:'Suitable Spare Parts',roles:['owner','admin']},{id:'knowledge-rewards',label:'Dealer Fitment Suggestions',roles:['owner','admin']},{id:'inventory',label:'Inventory Control',roles:['owner','admin','store_keeper']},{id:'purchase-entry',label:'Purchase Entry',roles:['owner','admin']},{id:'purchase-requirements',label:'Purchase Requirements',roles:['owner','admin','salesman','accountant','store_keeper']},{id:'dispatch',label:'Store & Dispatch',roles:['owner','admin','store_keeper']},{id:'schemes',label:'Schemes & Rewards',roles:['owner','admin','salesman']},{id:'messages',label:'Requests & Messages',roles:['owner','admin','salesman']},{id:'reports',label:'Reports Center',roles:['owner','admin','accountant','store_keeper']},{id:'users',label:'Users & Roles',roles:['owner','admin']},{id:'backup',label:'Backup & Recovery',roles:['owner','admin']},{id:'audit',label:'Settings & Audit',roles:['owner','admin']}];
export const SALES_FLOW=Object.freeze(['sales_order','dealer_ok','estimate','payment','delivery']);export const PAYMENT_STATUS=Object.freeze(['cash','pending','received']);export const DISPATCH_FLOW=Object.freeze(['pick_list','picked','packed','ready_for_dispatch','delivered']);
export const PUBLIC_CUSTOMER_FLOW=Object.freeze(['product_selected','customer_captured','dealer_found','dealer_selected','referral_created','verified_by_dealer','benefit_given']);
export const REFERRAL_BENEFIT_TYPES=Object.freeze(['percent','fixed_amount','free_service','free_accessory','other']);
export const BUSINESS_RULES=Object.freeze({stockDeductionTrigger:'payment_received_and_delivery',stockDeductionOnce:true,estimateDeductsStock:false,pickedDeductsStock:false,packedDeductsStock:false,storeKeeperCanSeeFinancials:false,dealerPricesBeforePurchaseOrder:true,dealerRequiresApproval:true,compatibilityPrivateByDefault:true,knowledgeAnswersPrivateBetweenDealers:true,knowledgeSuggestionsEarnPoints:false,torvoPointsSource:'eligible_sales_only',salesmanDealerScopeServerEnforced:true,backupDueAfterHours:24,backupRequiresVerification:true,makerCheckerApproval:true,selfApprovalDefault:false,salesReturnSeparateDocument:true,purchaseReturnSeparateDocument:true,publicCustomerDirectCheckout:false,publicCustomerPriceDisplayed:false,publicDealerPricingPrivate:true,publicReferralDealerTransaction:true,publicReferralRequiresApprovedDealer:true,publicReferralTracksFinalDealerPrice:false,customerMarketingRequiresSeparateOptIn:true,adminDesktopOnly:true,adminVerificationRequired:true});
