import React,{useMemo,useState}from'react';
import{LayoutDashboard,Users,ClipboardCheck,ShoppingCart,Wallet,Cog,Package,Boxes,Link2,Truck,Gift,MessageSquare,BarChart3,ShieldCheck,Bell,Menu,X,ChevronRight,Search,Plus}from'lucide-react';
import{MODULES,ROLES}from'./config/modules';
import'./styles.css';

const icons={dashboard:LayoutDashboard,dealers:Users,'dealer-requests':ClipboardCheck,sales:ShoppingCart,payments:Wallet,machines:Cog,'spare-parts':Package,accessories:Boxes,compatibility:Link2,inventory:Boxes,dispatch:Truck,schemes:Gift,messages:MessageSquare,reports:BarChart3,users:ShieldCheck,audit:ShieldCheck};
const groups=[['Business',['dashboard','dealers','dealer-requests','sales','payments']],['Catalog & Stock',['machines','spare-parts','accessories','compatibility','inventory']],['Operations',['dispatch','schemes','messages','reports']],['System',['users','audit']]];
const meta={dashboard:['Command Center','Business health and priority work'],dealers:['Dealers','Approved dealer network'], 'dealer-requests':['Dealer Requests','Review and control onboarding'],sales:['Sales Workspace','Query → Quotation → Sales Order → Estimate'],payments:['Payments','Cash, pending and received payments'],machines:['Machines','Sellable machines and model references'],'spare-parts':['Spare Parts','Parts master and compatibility'],accessories:['Accessories','Accessory catalog'],compatibility:['Suitable Spare Parts','Machine ↔ spare-part fitment engine'],inventory:['Inventory','Stock, reorder and movement control'],dispatch:['Store & Dispatch','Pick → Pack → Ready → Delivery'],schemes:['Schemes & Rewards','Dealer targets, gifts, points and referrals'],messages:['Requests & Messages','Non-available requests and communication'],reports:['Reports Center','Business, sales, stock and operations reports'],users:['Users & Roles','Role-based employee access'],audit:['Settings & Audit','Security, activity and system controls']};
const kpis=[['Sales Today','₹0'],['Open Orders','0'],['Dealer Requests','0'],['Payment Pending','₹0'],['Low Stock','0'],['Dispatch Pending','0']];
function Empty({title,body,action}){return <div className="empty"><div className="emptyIcon">◎</div><h3>{title}</h3><p>{body}</p>{action&&<button className="primary"><Plus size={16}/>{action}</button>}</div>}
function Dashboard(){return <><section className="welcome"><div><span className="eyebrow">TORVO BUSINESS CONTROL</span><h2>Good morning, Admin</h2><p>Important business activity appears here automatically. No demo figures are shown.</p></div><div className="health"><i/>System ready</div></section><div className="kpis">{kpis.map(([a,b])=><article key={a}><span>{a}</span><strong>{b}</strong><small>Live data</small></article>)}</div><div className="split"><section className="panel"><header><div><h3>Sales & Fulfilment</h3><p>Current pipeline</p></div></header><div className="pipeline">{['Query','Quotation','Sales Order','Estimate','Payment','Delivery'].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span><strong>0</strong></div>)}</div></section><section className="panel"><header><div><h3>Action Center</h3><p>Only work needing attention</p></div></header><Empty title="All clear" body="Pending approvals, stock alerts and dispatch exceptions will appear here."/></section></div><section className="panel"><header><div><h3>Business Performance</h3><p>Real data will populate after transactions begin</p></div></header><div className="chartEmpty">No transaction data yet</div></section></>}
function Workspace({id}){let [title,sub]=meta[id]||['Workspace',''];let catalog=['machines','spare-parts','accessories'].includes(id);return <section className="panel workspace"><header><div><h3>{title}</h3><p>{sub}</p></div>{catalog&&<button className="primary"><Plus size={16}/>Add {id==='machines'?'Machine':id==='spare-parts'?'Spare Part':'Accessory'}</button>}</header>{['dealers','dealer-requests','sales','payments','inventory','dispatch','messages','reports'].includes(id)&&<div className="localTools"><label><Search size={16}/><input placeholder={`Search ${title.toLowerCase()}…`}/></label></div>}<Empty title={`No ${title.toLowerCase()} yet`} body="This workspace is connected to the V2 data model and will show real records only."/></section>}
export default function App(){const role=ROLES.OWNER;const [active,setActive]=useState('dashboard');const[open,setOpen]=useState(false);const allowed=useMemo(()=>new Set(MODULES.filter(m=>m.roles.includes(role)).map(m=>m.id)),[role]);const go=id=>{setActive(id);setOpen(false)};return <div className="app"><aside className={open?'open':''}><div className="brand"><div className="mark">T</div><div><strong>TORVO</strong><span>Business Suite</span></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><nav>{groups.map(([g,ids])=><div className="navGroup" key={g}><p>{g}</p>{ids.filter(id=>allowed.has(id)).map(id=>{const I=icons[id]||Package;return <button className={active===id?'active':''} onClick={()=>go(id)} key={id}><I size={18}/><span>{meta[id]?.[0]||id}</span><ChevronRight className="chev" size={15}/></button>})}</div>)}</nav><div className="identity"><div>LG</div><p><strong>Owner</strong><span>Full access</span></p></div></aside><main><header className="top"><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{meta[active]?.[0]}</h1><p>{meta[active]?.[1]}</p></div><div className="topRight"><button className="iconBtn" aria-label="Notifications"><Bell size={19}/></button><div className="avatar">LG</div></div></header><div className="content">{active==='dashboard'?<Dashboard/>:<Workspace id={active}/>}</div></main>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>}
