import React,{lazy,Suspense,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
const App=lazy(()=>import('./App.jsx'));
const BusinessLogin=lazy(()=>import('./components/BusinessLogin.jsx'));
import LoginVisualPreview from './components/LoginVisualPreview.jsx';
import BackupCloseModal from './components/BackupCloseModal.jsx';
import AppUpdateNotice from './components/AppUpdateNotice.jsx';
import './styles.css';
import './workspace-polish.css';
import './admin-desktop-polish.css';
import './admin-search-v2.css';
import './accountant-search-v2.css';
import './accountant-admin-parity-fix.css';
import './purchase-requirements-ui.css';
import './app-install-ui.css';
import './backup-ui.css';
import './backup-close-ui.css';
import './dealer-addon-ui.css';
import './dealer-rewards-ui.css';
import './product-discovery.css';
import './login-ui.css';
import './login-preview.css';
import './public-product-showcase.css';
import './smart-search-ui.css';
import './public-catalog-browser.css';
import './smart-product-filters.css';
import './dealer-search-lock.css';
import './final-ui-balance.css';
import './secure-desktop-lock.css';
import './live-responsive-hotfix.css';
import {installGlobalUiFeedback} from './services/uiFeedback.js';
import {installAppFoundation} from './services/appInstall.js';
import {forceSignOut,currentAppUser} from './services/auth.js';
const root=document.getElementById('torvo-v2-root');
if(!root) throw new Error('TORVO V2 root element is missing');
const isNativeAndroid=()=>window?.Capacitor?.isNativePlatform?.()===true||window?.Capacitor?.getPlatform?.()==='android';
function V2Root(){const[backupClose,setBackupClose]=useState(false),[nativeReady,setNativeReady]=useState(!isNativeAndroid()),[nativeSignedIn,setNativeSignedIn]=useState(false);useEffect(()=>{const stopFeedback=installGlobalUiFeedback();const stopInstall=installAppFoundation();const open=()=>setBackupClose(true);window.addEventListener('torvo:backup-close',open);if(isNativeAndroid())currentAppUser().then(u=>setNativeSignedIn(Boolean(u?.active))).catch(()=>setNativeSignedIn(false)).finally(()=>setNativeReady(true));return()=>{stopFeedback?.();stopInstall?.();window.removeEventListener('torvo:backup-close',open)}},[]);const finish=async()=>{await forceSignOut();setBackupClose(false)};const params=new URLSearchParams(location.search),path=location.pathname.replace(/\/+$/,'')||'/',webLogin=params.get('login')==='1'||path==='/business-login.html'||path==='/business-login',nativeLogin=isNativeAndroid()&&nativeReady&&!nativeSignedIn;return <><Suspense fallback={null}>{!nativeReady?null:webLogin?<LoginVisualPreview/>:nativeLogin?<BusinessLogin/>:<App/>}</Suspense><AppUpdateNotice/><BackupCloseModal open={backupClose} onCancel={()=>setBackupClose(false)} onSignOut={finish}/></>}
createRoot(root).render(<React.StrictMode><V2Root/></React.StrictMode>);
