import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.jsx';
import OperationalStaffLogin from './components/OperationalStaffLogin.jsx';
import DealerAppEntry from './components/DealerAppEntry.jsx';
import LoginVisualPreview from './components/LoginVisualPreview.jsx';
import BackupCloseModal from './components/BackupCloseModal.jsx';
import AppUpdateNotice from './components/AppUpdateNotice.jsx';
import './styles.css';
import './admin-desktop-polish.css';
import './admin-search-v2.css';
import './accountant-search-v2.css';
import './accountant-admin-parity-fix.css';
import './purchase-requirements-ui.css';
import './app-install-ui.css';
import './backup-ui.css';
import './backup-close-ui.css';
import './dealer-addon-ui.css';
import './product-discovery.css';
import './login-ui.css';
import './login-preview.css';
import './public-product-showcase.css';
import './smart-search-ui.css';
import './public-catalog-browser.css';
import './smart-product-filters.css';
import './torvo-component-contract.css';
import './torvo-operational-ui.css';
import './torvo-ai-integration-ui.css';
import './torvo-ui-system.css';
import {installGlobalUiFeedback} from './services/uiFeedback.js';
import {installAppFoundation} from './services/appInstall.js';
import {forceSignOut,currentAppUser} from './services/auth.js';
const root=document.getElementById('torvo-v2-root');
if(!root) throw new Error('TORVO V2 root element is missing');
const isNativeAndroid=()=>window?.Capacitor?.isNativePlatform?.()===true||window?.Capacitor?.getPlatform?.()==='android';
function NativeOperationalEntry({onStaff}){const[mode,setMode]=useState('');if(mode==='dealer')return <DealerAppEntry/>;if(mode==='staff')return <OperationalStaffLogin onAuthenticated={onStaff}/>;return <main className="dealerEntry"><section className="dealerEntryBrand"><div className="roleLogo">T</div><h1>TORVO</h1><p>BUSINESS APP</p><strong>AUTHORIZED ROLE ACCESS</strong></section><section className="dealerEntryCard"><span className="eyebrow">SELECT YOUR ACCESS</span><h2>WELCOME TO TORVO</h2><p>Your actual permissions come from the server-authorized account after login.</p><button className="primary" onClick={()=>setMode('dealer')}>DEALER LOGIN</button><button className="secondary" onClick={()=>setMode('staff')}>SALESMAN / STORE KEEPER LOGIN</button><small>This selection does not assign a role. Server authorization remains mandatory.</small></section></main>}
function V2Root(){const[backupClose,setBackupClose]=useState(false),[nativeReady,setNativeReady]=useState(!isNativeAndroid()),[nativeUser,setNativeUser]=useState(null);useEffect(()=>{const stopFeedback=installGlobalUiFeedback();const stopInstall=installAppFoundation();const open=()=>setBackupClose(true);window.addEventListener('torvo:backup-close',open);if(isNativeAndroid())currentAppUser().then(u=>setNativeUser(u?.active?u:null)).catch(()=>setNativeUser(null)).finally(()=>setNativeReady(true));return()=>{stopFeedback?.();stopInstall?.();window.removeEventListener('torvo:backup-close',open)}},[]);const finish=async()=>{await forceSignOut();setBackupClose(false)};const params=new URLSearchParams(location.search),path=location.pathname.replace(/\/+$/,'')||'/',webLogin=params.get('login')==='1'||path==='/business-login.html'||path==='/business-login',nativeLogin=isNativeAndroid()&&nativeReady&&!nativeUser;const nativeRole=String(nativeUser?.role||'').toLowerCase();return <>{!nativeReady?null:webLogin?<LoginVisualPreview/>:nativeLogin?<NativeOperationalEntry onStaff={setNativeUser}/>:isNativeAndroid()&&!['dealer','salesman','store_keeper'].includes(nativeRole)?<NativeOperationalEntry onStaff={setNativeUser}/>:<App/>}<AppUpdateNotice/><BackupCloseModal open={backupClose} onCancel={()=>setBackupClose(false)} onSignOut={finish}/></>}
createRoot(root).render(<React.StrictMode><V2Root/></React.StrictMode>);
