import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.jsx';
import DealerAppEntry from './components/DealerAppEntry.jsx';
import LoginVisualPreview from './components/LoginVisualPreview.jsx';
import BackupCloseModal from './components/BackupCloseModal.jsx';
import AppUpdateNotice from './components/AppUpdateNotice.jsx';
import './styles.css';
import './role-app-preview.css';
import './admin-desktop-polish.css';
import './accountant-admin-parity-fix.css';
import './purchase-requirements-ui.css';
import './app-install-ui.css';
import './backup-ui.css';
import './backup-close-ui.css';
import './dealer-addon-ui.css';
import './product-discovery.css';
import './login-preview.css';
import './public-product-showcase.css';
import './smart-search-ui.css';
import './public-catalog-browser.css';
import './smart-product-filters.css';
import './torvo-component-contract.css';
import './torvo-operational-ui.css';
import './torvo-ai-integration-ui.css';
import './torvo-ui-system.css';
import {installGlobalUiFeedback} from './services/uiFeedback.js';
import {installAppFoundation} from './services/appInstall.js';
import {forceSignOut,currentAppUser} from './services/auth.js';
const root=document.getElementById('torvo-v2-root');
if(!root) throw new Error('TORVO V2 root element is missing');
const isNativeAndroid=()=>window?.Capacitor?.isNativePlatform?.()===true||window?.Capacitor?.getPlatform?.()==='android';
function NativeOperationalEntry({onStaff}){return <DealerAppEntry onStaffAuthenticated={onStaff}/>}
function V2Root(){const[backupClose,setBackupClose]=useState(false),[nativeReady,setNativeReady]=useState(!isNativeAndroid()),[nativeUser,setNativeUser]=useState(null);useEffect(()=>{const stopFeedback=installGlobalUiFeedback();const stopInstall=installAppFoundation();const open=()=>setBackupClose(true);window.addEventListener('torvo:backup-close',open);if(isNativeAndroid())currentAppUser().then(u=>setNativeUser(u?.active?u:null)).catch(()=>setNativeUser(null)).finally(()=>setNativeReady(true));return()=>{stopFeedback?.();stopInstall?.();window.removeEventListener('torvo:backup-close',open)}},[]);const finish=async()=>{await forceSignOut();setBackupClose(false)};const params=new URLSearchParams(location.search),path=location.pathname.replace(/\/+$/,'')||'/',webLogin=params.get('login')==='1'||path==='/business-login.html'||path==='/business-login',nativeLogin=isNativeAndroid()&&nativeReady&&!nativeUser;const nativeRole=String(nativeUser?.role||'').toLowerCase();return <>{!nativeReady?null:webLogin?<LoginVisualPreview/>:nativeLogin?<NativeOperationalEntry onStaff={setNativeUser}/>:isNativeAndroid()&&!['dealer','salesman','store_keeper'].includes(nativeRole)?<NativeOperationalEntry onStaff={setNativeUser}/>:<App/>}<AppUpdateNotice/><BackupCloseModal open={backupClose} onCancel={()=>setBackupClose(false)} onSignOut={finish}/></>}
createRoot(root).render(<React.StrictMode><V2Root/></React.StrictMode>);
