import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import PublicWebsitePreview from './components/PublicWebsitePreview';
import RoleAppPreview from './components/RoleAppPreview';
import DealerAppEntry from './components/DealerAppEntry';
import AdminVisualPreview from './components/AdminVisualPreview';
import AccountantVisualPreview from './components/AccountantVisualPreview';
import LoginVisualPreview from './components/LoginVisualPreview';
import App from './App.jsx';
import DealerRegistrationPreview from './components/DealerRegistrationPreview';
import './styles.css';import './login-preview.css';import './purchase-requirements-ui.css';import './public-website.css';import './public-product-showcase.css';import './public-catalog-browser.css';import './smart-search-ui.css';import './smart-product-filters.css';import './role-app-preview.css';import './admin-desktop-polish.css';import './admin-search-v2.css';import './accountant-search-v2.css';import './torvo-component-contract.css';import './torvo-operational-ui.css';import './torvo-ai-integration-ui.css';import './torvo-ui-system.css';
import {installGlobalUiFeedback} from './services/uiFeedback.js';
import {currentVerifiedStaff} from './services/auth.js';
const root=document.getElementById('torvo-v2-root');if(!root)throw new Error('TORVO V2 preview root not found');
const params=new URLSearchParams(window.location.search);const routeVisual=location.pathname==='/admin-workspace'?'admin':location.pathname==='/accountant-workspace'?'accountant':'';const visual=(routeVisual||params.get('visual')||'website').toLowerCase();
const protectedDesktop=visual==='admin'||visual==='desktop'||visual==='accountant';
function Preview(){const[user,setUser]=useState(undefined);useEffect(()=>{let live=true;if(!protectedDesktop){setUser(null);return()=>{live=false}}currentVerifiedStaff().then(u=>{if(live)setUser(u)}).catch(()=>{if(live)setUser(null)});return()=>{live=false}},[]);if(protectedDesktop){if(user===undefined)return null;const role=String(user?.role||'').toLowerCase();if(!user?.active)return <LoginVisualPreview/>;if((visual==='admin'||visual==='desktop')&&['owner','admin'].includes(role))return <App/>;if(visual==='accountant'&&role==='accountant')return <App/>;return <LoginVisualPreview/>;}if(visual==='login')return <LoginVisualPreview/>;if(visual==='register')return <DealerRegistrationPreview/>;if(visual==='salesman')return <RoleAppPreview role="salesman"/>;if(visual==='store')return <RoleAppPreview role="store"/>;if(visual==='app'||visual==='dealer')return <DealerAppEntry/>;return <PublicWebsitePreview/>}
const links=[['website','WEBSITE'],['dealer','DEALER APP'],['salesman','SALESMAN APP'],['store','STORE KEEPER APP'],['accountant','ACCOUNTANT'],['admin','OWNER / ADMIN']];const build=(import.meta.env.VITE_BUILD_SHA||'LOCAL').slice(0,8).toUpperCase();
function Switcher(){return <div className="previewSwitcher"><div className="previewSwitcherButtons">{links.map(([id,label])=><button key={id} onClick={()=>{const u=new URL(location.href);id==='website'?u.searchParams.delete('visual'):u.searchParams.set('visual',id);if(id==='admin'||id==='accountant')u.searchParams.set('auth','required');location.href=u.toString()}} className={(visual===id)||(visual==='website'&&id==='website')?'active':''}>{label}</button>)}</div><span>PREVIEW BUILD · {build}</span></div>}
const showPreviewTools=params.get('previewTools')==='1'||params.get('review')==='1';function PreviewRoot(){useEffect(()=>installGlobalUiFeedback(),[]);return <><Preview/>{showPreviewTools&&<Switcher/>}</>}
function renderPreview(){createRoot(root).render(<React.StrictMode><PreviewRoot/></React.StrictMode>)}
try{renderPreview()}catch(error){console.error('TORVO V2 PUBLIC RENDER FAILED',error);root.innerHTML='<main style="min-height:100vh;background:#fff;padding:24px;font-family:Arial,sans-serif;color:#111"><div style="max-width:620px;margin:15vh auto;border:1px solid #e5e7eb;border-radius:16px;padding:24px"><b style="color:#d71920">TORVO</b><h1 style="font-size:22px;margin:12px 0 8px">DISPLAY RECOVERY MODE</h1><p style="line-height:1.5">The public screen could not start correctly. Refresh once. If this remains visible, the TORVO build can now report the render failure instead of showing a blank white page.</p><button onclick="location.reload()" style="border:0;border-radius:10px;background:#d71920;color:#fff;padding:11px 16px;font-weight:700">REFRESH TORVO</button></div></main>'}
