import React,{useEffect,useState}from'react';
import{ArrowLeft,ArrowRight,LockKeyhole,Smartphone,UserRound}from'lucide-react';
import{currentAppUser}from'../services/auth';
import{deviceId,loginStaffWithAdminPassword,normalizeDealerMobile,normalizeStaffUsername,verifyDealerPin,requestDealerPinRecovery}from'../services/staffAuth';
import'../login-attendance.css';
const digits=v=>String(v||'').replace(/\D/g,'').slice(-10);
export default function BusinessLogin(){
 const[kind,setKind]=useState('dealer'),[identity,setIdentity]=useState(''),[mode,setMode]=useState('identity'),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{currentAppUser().then(u=>{if(u?.active)location.replace('/v2.html')}).catch(()=>{})},[]);
 const start=e=>{e.preventDefault();setErr('');setNotice('');try{if(kind==='dealer'){normalizeDealerMobile(identity);setMode('dealer_pin')}else{const u=normalizeStaffUsername(identity);if(!/^[A-Z]{2,8}@[0-9]{2,6}$/.test(u))throw new Error('ENTER A VALID STAFF USER ID.');setIdentity(u);setMode('staff_password')}}catch(x){setErr(x.message)}};
 const finish=async e=>{e.preventDefault();setErr('');setNotice('');setBusy(true);try{let result;if(mode==='dealer_pin'){if(digits(code).length!==4)throw new Error('ENTER YOUR 4-DIGIT DEALER PIN.');result=await verifyDealerPin(identity,digits(code),deviceId())}else{if(code.length<10)throw new Error('ENTER THE ADMIN-ISSUED ONE-TIME PASSWORD.');result=await loginStaffWithAdminPassword(identity,code,'mobile_app')}if(!result?.ok)throw new Error(result?.message||'VERIFICATION FAILED.');location.replace('/v2.html')}catch(x){setErr(x.message||'VERIFICATION FAILED.')}finally{setBusy(false)}};
 const recover=async()=>{setErr('');setNotice('');setBusy(true);try{const r=await requestDealerPinRecovery(identity);setNotice(r?.message||'PIN RECOVERY VERIFICATION SENT TO YOUR REGISTERED WHATSAPP NUMBER.')}catch(x){setErr(x.message||'PIN RECOVERY SERVICE IS NOT AVAILABLE.')}finally{setBusy(false)}};
 const reset=()=>{setMode('identity');setCode('');setErr('');setNotice('')};
 const dealer=kind==='dealer';
 return <main className="loginPage"><section className="loginCard"><header className="loginBrand"><div className="mark">T</div><div><strong>TORVO</strong><span>TOOLS PRIVATE LIMITED</span></div></header><div className="loginIntro"><span className="eyebrow">SECURE BUSINESS ACCESS</span><h1>{mode==='identity'?'LOGIN':dealer?'DEALER LOGIN':'STAFF LOGIN'}</h1><p>{mode==='identity'?'DEALER USES REGISTERED MOBILE. STAFF USES ADMIN-ISSUED USER ID.':dealer?'ENTER YOUR 4-DIGIT PIN. A NEW MOBILE LOGIN SIGNS OUT THE PREVIOUS DEALER MOBILE.':'ENTER THE ONE-TIME PASSWORD ISSUED BY ADMIN. SALESMAN AND STORE KEEPER USE THE MOBILE APP; ACCOUNTANT USES SECURE DESKTOP.'}</p></div>{mode==='identity'?<form onSubmit={start}><div className="loginTypeSwitch"><button type="button" className={dealer?'active':''} onClick={()=>{setKind('dealer');setIdentity('');setErr('')}}><Smartphone size={16}/>DEALER MOBILE</button><button type="button" className={!dealer?'active':''} onClick={()=>{setKind('staff');setIdentity('');setErr('')}}><UserRound size={16}/>STAFF USER ID</button></div><label>{dealer?'MOBILE NUMBER':'USER ID'}<div className="loginInput">{dealer?<><Smartphone size={18}/><span className="country">+91</span></>:<UserRound size={18}/>}<input autoFocus inputMode={dealer?'numeric':'text'} autoCapitalize="characters" autoComplete={dealer?'tel':'username'} value={identity} onChange={e=>setIdentity(dealer?digits(e.target.value):normalizeStaffUsername(e.target.value).slice(0,15))} placeholder={dealer?'10-DIGIT MOBILE NUMBER':'EXAMPLE: SM@01'}/></div></label>{err&&<div className="inlineError" role="alert">{err}</div>}<button className="primary loginContinue" disabled={dealer?identity.length!==10:identity.length<5}>CONTINUE <ArrowRight size={17}/></button><button type="button" className="loginHelp" onClick={()=>location.href='/'}>NEW DEALER? REGISTER AS DEALER</button></form>:<form onSubmit={finish}><label>{dealer?'4-DIGIT PIN':'ADMIN-ISSUED ONE-TIME PASSWORD'}<div className="loginInput"><LockKeyhole size={18}/><input autoFocus inputMode={dealer?'numeric':'text'} autoComplete="current-password" type="password" maxLength={dealer?4:80} value={code} onChange={e=>{setErr('');setCode(dealer?digits(e.target.value).slice(0,4):e.target.value)}} placeholder={dealer?'ENTER PIN':'ENTER ONE-TIME PASSWORD'}/></div></label>{err&&<div className="inlineError" role="alert">{err}</div>}{notice&&<div className="loginNotice" role="status">{notice}</div>}<button className="primary loginContinue" disabled={busy||(dealer?code.length!==4:code.length<10)}>{busy?'VERIFYING…':'VERIFY & LOGIN'} <ArrowRight size={17}/></button><button type="button" className="loginHelp" onClick={reset}><ArrowLeft size={13}/> CHANGE {dealer?'MOBILE NUMBER':'USER ID'}</button>{dealer&&<button type="button" className="loginHelp" disabled={busy} onClick={recover}>FORGOT PIN? VERIFY ON WHATSAPP</button>}</form>}<p className="loginFoot">DEALER: MOBILE + PIN · STAFF: USER ID + ADMIN ONE-TIME PASSWORD.</p></section></main>}
