import React,{useEffect,useState}from'react';
import{Headphones,MapPin,QrCode,Wrench,X,Phone,CheckCircle2,Search}from'lucide-react';
import{requireBackend}from'../services/supabase';
import{recordPromotionEvent}from'../services/productPromotion';
import{createCustomerProductDemand,requestTorvoProductHelp}from'../services/customerProductDemand';
import ProductDiscovery from'./ProductDiscovery';
import ProductDiscoveryRail from'./ProductDiscoveryRail';
const db=()=>requireBackend();const U=v=>String(v||'').toUpperCase();
export default function CustomerApp(){
 const[settings,setSettings]=useState({support_mobile:'7027751533',referral_enabled:true,repair_service_enabled:true,customer_catalog_enabled:true});const[selected,setSelected]=useState(null);const[pin,setPin]=useState('');const[dealers,setDealers]=useState([]);const[dealer,setDealer]=useState(null);const[form,setForm]=useState({name:'',mobile:'',marketing:false});const[demand,setDemand]=useState({name:'',mobile:'',search:'',brand:'',model:'',note:'',marketing:false});const[demandResult,setDemandResult]=useState(null);const[repair,setRepair]=useState({name:'',mobile:'',pin:'',brand:'',model:'',problem:'',marketing:false});const[repairResult,setRepairResult]=useState(null);const[ref,setRef]=useState(null);const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const[open,setOpen]=useState('');
 useEffect(()=>{db().rpc('public_business_settings').then(({data})=>{const x=Array.isArray(data)?data[0]:data;if(x)setSettings(x)})},[]);
 const support=settings.support_mobile||'7027751533';
 const find=async()=>{if(!/^\d{6}$/.test(pin)){setErr('VALID 6 DIGIT PIN CODE REQUIRED');return}setBusy(true);setErr('');const{data,error}=await db().rpc('public_find_torvo_dealers_expanded',{p_pin_code:pin,p_repair_only:false,p_limit:12});setBusy(false);if(error)setErr(U(error.message));else{setDealers(data||[]);setOpen('dealers')}};
 const openDemand=()=>{setErr('');setDemand(d=>({...d,search:selected?.name||selected?.item_code||d.search,brand:selected?.brand||d.brand,model:selected?.model||d.model}));setOpen('demand')};
 const submitDemand=async e=>{e.preventDefault();setBusy(true);setErr('');try{const r=await createCustomerProductDemand({name:demand.name,mobile:demand.mobile,pin,searchText:demand.search,productId:selected?.id||null,brand:demand.brand,modelNumber:demand.model,requirementNote:demand.note,marketing:demand.marketing});setDemandResult(r);setOpen('demandDone')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const askTorvo=async()=>{setBusy(true);setErr('');try{const r=await requestTorvoProductHelp(demandResult?.demand_id,demand.mobile);setDemandResult(v=>({...v,...r}));setOpen('torvoHelp')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const createReferral=async e=>{e.preventDefault();if(!settings.referral_enabled||!selected)return;setBusy(true);const{data,error}=await db().rpc('public_create_customer_referral',{p_full_name:form.name,p_mobile:form.mobile,p_pin_code:pin,p_product_id:selected.id,p_dealer_id:dealer?.dealer_id||null,p_marketing_opt_in:form.marketing});setBusy(false);if(error)setErr(U(error.message));else{const r=Array.isArray(data)?data[0]:data;setRef(r);if(selected.promotion_id)recordPromotionEvent(selected.promotion_id,'enquiry','website',r?.referral_code||null).catch(()=>{});setOpen('referral')}};
 const submitRepair=async e=>{e.preventDefault();setBusy(true);const{data,error}=await db().rpc('public_create_repair_request',{p_full_name:repair.name,p_mobile:repair.mobile,p_pin_code:repair.pin,p_brand:repair.brand||null,p_model_number:repair.model||null,p_problem_description:repair.problem,p_marketing_opt_in:repair.marketing});setBusy(false);if(error)setErr(U(error.message));else{setRepairResult(Array.isArray(data)?data[0]:data);setOpen('repairDone')}};
 return <section className="panel workspace"><header><div><span className="eyebrow">TORVO CUSTOMER APP</span><h3>SEARCH · FILTER · FIND DEALER</h3><p>FAST SPARE PART DISCOVERY WITHOUT PUBLIC SELLING PRICE. RETAIL PRICE, PAYMENT AND DELIVERY STAY BETWEEN CUSTOMER AND DEALER.</p></div></header>{err&&<div className="inlineError">{err}</div>}<ProductDiscoveryRail target="website" onProductSelect={x=>setSelected(s=>({...s,...x}))}/>{settings.customer_catalog_enabled?<ProductDiscovery selectedId={selected?.id} onSelect={x=>setSelected(s=>({...s,...x}))}/>:<div className="modalNotice">CUSTOMER CATALOG IS CURRENTLY PAUSED BY TORVO.</div>}
 <section className="panel"><header><div><span className="eyebrow">{selected?'SELECTED PRODUCT':'MISSING PRODUCT'}</span><h3>{selected?(selected.name||selected.item_code):"CAN'T FIND IT? REQUEST THIS ITEM"}</h3><p>{selected?'FIND AN APPROVED DEALER OR SUBMIT A CONFIRMED REQUIREMENT.':'RAW SEARCH TYPING DOES NOT CREATE A CUSTOMER LEAD.'}</p></div>{!selected&&<Search/>}</header><div className="workFilters"><label><MapPin size={16}/><input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 DIGIT PIN CODE"/></label>{selected&&<button className="primary" disabled={busy} onClick={find}>FIND NEARBY DEALER</button>}<button onClick={openDemand}>REQUEST THIS ITEM</button></div></section>
 {open==='dealers'&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>DEALERS SERVING PIN {pin}</h3><button className="iconBtn" onClick={()=>setOpen('')}><X/></button></header><div className="requestList">{dealers.length?dealers.map(d=><article key={d.dealer_id}><div><strong>{d.shop_name}</strong><span>{d.address}</span><small>{d.match_type==='EXACT_PIN'?'SAME PIN':'VERIFIED SERVICE AREA'}</small></div><button onClick={()=>{setDealer(d);setOpen('details')}}>SELECT DEALER</button></article>):<div className="empty"><MapPin/><h3>NO VERIFIED DEALER COVERAGE</h3><p>SUBMIT YOUR REQUIREMENT AND TORVO CAN HELP CHECK PAN-INDIA SOURCING.</p><button className="primary" onClick={openDemand}>REQUEST THIS ITEM</button></div>}</div></section></div>}
 {open==='demand'&&<div className="modalLayer"><form className="dealerActionModal" onSubmit={submitDemand}><header><div><span className="eyebrow">CUSTOMER PRODUCT REQUIREMENT</span><h3>REQUEST THIS ITEM</h3></div><button type="button" className="iconBtn" onClick={()=>setOpen('')}><X/></button></header><div className="modalForm"><label>NAME<input value={demand.name} onChange={e=>setDemand({...demand,name:e.target.value})} required/></label><label>MOBILE / WHATSAPP<input inputMode="numeric" value={demand.mobile} onChange={e=>setDemand({...demand,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} required/></label><label>PIN CODE<input inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} required/></label><label>ITEM / SEARCH<input value={demand.search} onChange={e=>setDemand({...demand,search:e.target.value})} required/></label><label>BRAND<input value={demand.brand} onChange={e=>setDemand({...demand,brand:e.target.value})}/></label><label>MODEL NUMBER<input value={demand.model} onChange={e=>setDemand({...demand,model:e.target.value})}/></label><label>REQUIREMENT NOTE<textarea maxLength="500" value={demand.note} onChange={e=>setDemand({...demand,note:e.target.value})}/></label><label className="checkRow"><input type="checkbox" checked={demand.marketing} onChange={e=>setDemand({...demand,marketing:e.target.checked})}/> RECEIVE TORVO UPDATES ON WHATSAPP</label><div className="modalNotice">CUSTOMER CONTACT IS NOT PUBLICLY BROADCAST TO DEALERS.</div></div><footer><button type="button" onClick={()=>setOpen('')}>CANCEL</button><button className="primary" disabled={busy}>SUBMIT REQUIREMENT</button></footer></form></div>}
 {open==='demandDone'&&demandResult&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>TORVO PRODUCT REQUEST CREATED</h3><CheckCircle2/></header><div className="inlineSuccess">REQUEST ID: {String(demandResult.demand_id).slice(0,8).toUpperCase()}</div><div className="modalNotice">IF THE ITEM IS STILL NOT AVAILABLE, ASK TORVO TO CHECK PAN-INDIA SOURCING.</div><footer><button onClick={()=>setOpen('')}>CLOSE</button><button className="primary" disabled={busy} onClick={askTorvo}>ASK TORVO PAN-INDIA HELP</button></footer></section></div>}
 {open==='torvoHelp'&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>WE WILL CHECK THE ITEM</h3><Headphones/></header><div className="inlineSuccess">REQUEST STATUS: {U(demandResult?.status||'SOURCING')}</div><div className="modalNotice">TORVO WILL CHECK ITS NETWORK. AVAILABILITY IS NOT GUARANTEED.</div><footer><a href={`tel:${support}`}><Phone size={15}/> CALL {support}</a><button onClick={()=>setOpen('')}>CLOSE</button></footer></section></div>}
 {open==='details'&&dealer&&<div className="modalLayer"><form className="dealerActionModal" onSubmit={createReferral}><header><h3>{dealer.shop_name}</h3><button type="button" className="iconBtn" onClick={()=>setOpen('')}><X/></button></header><div className="modalForm"><label>NAME<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>MOBILE / WHATSAPP<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} required/></label><label className="checkRow"><input type="checkbox" checked={form.marketing} onChange={e=>setForm({...form,marketing:e.target.checked})}/> RECEIVE TORVO UPDATES ON WHATSAPP</label></div><footer><button type="button" onClick={()=>setOpen('')}>CANCEL</button><button className="primary" disabled={busy}>GET TORVO REFERRAL CODE</button></footer></form></div>}
 {open==='referral'&&ref&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>{ref.referral_code}</h3><QrCode/></header><div className="modalNotice">SHOW THIS TORVO REFERRAL CODE TO THE DEALER.</div><button onClick={()=>setOpen('')}>CLOSE</button></section></div>}
 {settings.repair_service_enabled&&<section className="panel"><header><div><span className="eyebrow">SERVICE NETWORK</span><h3>MACHINE REPAIR & SERVICE</h3></div><Wrench/></header><button className="primary" onClick={()=>setOpen('repair')}>SEND REPAIR REQUIREMENT</button></section>}
 {open==='repair'&&<div className="modalLayer"><form className="dealerActionModal" onSubmit={submitRepair}><header><h3>TELL US THE MACHINE PROBLEM</h3><button type="button" className="iconBtn" onClick={()=>setOpen('')}><X/></button></header><div className="modalForm"><label>NAME<input value={repair.name} onChange={e=>setRepair({...repair,name:e.target.value})} required/></label><label>MOBILE / WHATSAPP<input value={repair.mobile} onChange={e=>setRepair({...repair,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} required/></label><label>PIN CODE<input value={repair.pin} onChange={e=>setRepair({...repair,pin:e.target.value.replace(/\D/g,'').slice(0,6)})} required/></label><label>BRAND<input value={repair.brand} onChange={e=>setRepair({...repair,brand:e.target.value})}/></label><label>MODEL NUMBER<input value={repair.model} onChange={e=>setRepair({...repair,model:e.target.value})}/></label><label>PROBLEM DESCRIPTION<textarea value={repair.problem} onChange={e=>setRepair({...repair,problem:e.target.value})} required/></label><label className="checkRow"><input type="checkbox" checked={repair.marketing} onChange={e=>setRepair({...repair,marketing:e.target.checked})}/> RECEIVE TORVO UPDATES ON WHATSAPP</label></div><footer><button type="button" onClick={()=>setOpen('')}>CANCEL</button><button className="primary" disabled={busy}>SUBMIT REPAIR REQUEST</button></footer></form></div>}
 {open==='repairDone'&&repairResult&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>REPAIR REQUEST RECEIVED</h3><CheckCircle2/></header><div className="inlineSuccess">REQUEST ID: {String(repairResult.requirement_id).slice(0,8).toUpperCase()}</div><button onClick={()=>setOpen('')}>CLOSE</button></section></div>}
 <div className="modalNotice"><Headphones size={16}/> TORVO SUPPORT: {support} · CUSTOMER RETAIL TRANSACTION REMAINS BETWEEN CUSTOMER AND DEALER.</div></section>;
}
