import React,{useEffect,useState}from'react';
import{Headphones,MapPin,QrCode,Wrench,X,Phone,CheckCircle2,Search,RefreshCw,MessageCircle,Navigation,ShieldCheck,ShoppingBag,BadgeCheck}from'lucide-react';
import{requireBackend}from'../services/supabase';
import{recordPromotionEvent}from'../services/productPromotion';
import{createCustomerProductDemand,requestTorvoProductHelp,loadCustomerProductDemandResult}from'../services/customerProductDemand';
import{createReferral as createPublicReferral,createRepair as createPublicRepair}from'../services/publicWebsite';
import{findCustomerDealers,openCustomerDealerProfile,selectCustomerDealer,recordCustomerDealerCall,recordCustomerDealerWhatsApp,recordCustomerDealerDirections,recordCustomerDealerReferral}from'../services/customerDealerJourney';
import ProductDiscovery from'./ProductDiscovery';
import ProductDiscoveryRail from'./ProductDiscoveryRail';
import PublicCatalogDropdowns from'./PublicCatalogDropdowns';
const db=()=>requireBackend();const U=v=>String(v||'').toUpperCase();
export default function CustomerApp(){
 const[settings,setSettings]=useState({support_mobile:'7027751533',referral_enabled:true,repair_service_enabled:true,customer_catalog_enabled:true});const[selected,setSelected]=useState(null);const[pin,setPin]=useState('');const[dealers,setDealers]=useState([]);const[dealer,setDealer]=useState(null);const[dealerProfile,setDealerProfile]=useState(null);const[form,setForm]=useState({name:'',mobile:'',marketing:false});const[demand,setDemand]=useState({name:'',mobile:'',search:'',brand:'',machineModel:'',note:'',marketing:false});const[demandResult,setDemandResult]=useState(null);const[repair,setRepair]=useState({name:'',mobile:'',pin:'',brand:'',machineModel:'',problem:'',marketing:false});const[repairResult,setRepairResult]=useState(null);const[ref,setRef]=useState(null);const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const[open,setOpen]=useState('');
 useEffect(()=>{db().rpc('public_business_settings').then(({data})=>{const x=Array.isArray(data)?data[0]:data;if(x)setSettings(x)}).catch(()=>{})},[]);const support=settings.support_mobile||'7027751533';const close=()=>{if(busy)return;setErr('');setOpen('')};
 const find=async()=>{if(busy)return;setBusy(true);setErr('');try{const data=await findCustomerDealers(pin);setDealers(data);setDealer(null);setDealerProfile(null);setRef(null);setOpen('dealers')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const selectDealer=async d=>{if(busy)return;setBusy(true);setErr('');setRef(null);try{const profile=await openCustomerDealerProfile(d,selected);await selectCustomerDealer(profile,selected);setDealer(d);setDealerProfile(profile);setOpen('details')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const openDemand=()=>{if(busy)return;setErr('');setDemandResult(null);setDemand(d=>({...d,search:selected?.name||selected?.item_code||d.search,brand:selected?.brand||d.brand,machineModel:selected?.model||selected?.machine_model||d.machineModel}));setOpen('demand')};
 const submitDemand=async e=>{e.preventDefault();if(busy)return;setBusy(true);setErr('');try{const r=await createCustomerProductDemand({name:demand.name,mobile:demand.mobile,pin,searchText:demand.search,productId:selected?.id||null,brand:demand.brand,modelNumber:demand.machineModel,requirementNote:demand.note,marketing:demand.marketing});setDemandResult(r);setOpen('demandDone')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const askTorvo=async()=>{if(busy)return;setBusy(true);setErr('');try{const r=await requestTorvoProductHelp(demandResult?.demand_id,demand.mobile);setDemandResult(v=>({...v,...r}));setOpen('torvoHelp')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const checkDemand=async()=>{if(busy)return;setBusy(true);setErr('');try{const r=await loadCustomerProductDemandResult(demandResult?.demand_id,demand.mobile);if(!r)throw new Error('CUSTOMER REQUIREMENT NOT FOUND');setDemandResult(v=>({...v,...r}));setOpen('demandStatus')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const createReferral=async e=>{e.preventDefault();if(busy||!settings.referral_enabled||!selected||!dealerProfile)return;setBusy(true);setErr('');try{const r=await createPublicReferral({name:form.name,mobile:form.mobile,pin,productId:selected.id,dealerId:dealerProfile.dealer_id,marketing:form.marketing});setRef(r);recordCustomerDealerReferral(dealerProfile,selected,r?.enquiry_id||null);if(selected.promotion_id)recordPromotionEvent(selected.promotion_id,'enquiry','website',r?.referral_code||null).catch(()=>{});setOpen('referral')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const submitRepair=async e=>{e.preventDefault();if(busy)return;setBusy(true);setErr('');try{const r=await createPublicRepair({name:repair.name,mobile:repair.mobile,pin:repair.pin,brand:repair.brand||null,model:repair.machineModel||null,problem:repair.problem,marketing:repair.marketing});setRepairResult(r);setOpen('repairDone')}catch(x){setErr(U(x.message))}finally{setBusy(false)}};
 const dp=dealerProfile||dealer,wa=String(dp?.whatsapp||dp?.mobile||'').replace(/\D/g,''),map=String(dp?.map_url||'').trim(),productLabel=selected?.name||selected?.item_code||'PRODUCT',journeyEnquiryId=ref?.enquiry_id||null;
 const dealerCall=()=>recordCustomerDealerCall(dp,selected,journeyEnquiryId);const dealerWhatsApp=()=>recordCustomerDealerWhatsApp(dp,selected,journeyEnquiryId);const dealerDirections=()=>recordCustomerDealerDirections(dp,selected,journeyEnquiryId);
 const capabilities=dp&&<div className="dealerCapabilities">{dp.product_sales_available&&<span><ShoppingBag size={14}/>PRODUCT SALES</span>}{dp.repair_service_available&&<span><Wrench size={14}/>REPAIR SERVICE</span>}{dp.authorized_service_center&&<span className="verified"><BadgeCheck size={14}/>AUTHORIZED SERVICE CENTER</span>}</div>;
 const dealerActions=<div className="workFilters dealerContactActions">{dp?.mobile&&<a href={`tel:${dp.mobile}`} onClick={dealerCall}><Phone size={15}/>CALL DEALER</a>}{wa&&<a href={`https://wa.me/91${wa}?text=${encodeURIComponent(`TORVO PRODUCT ENQUIRY: ${productLabel}${ref?.referral_code?` | REFERRAL CODE: ${ref.referral_code}`:''}`)}`} target="_blank" rel="noreferrer" onClick={dealerWhatsApp}><MessageCircle size={15}/>WHATSAPP DEALER</a>}{map&&<a href={map} target="_blank" rel="noreferrer" onClick={dealerDirections}><Navigation size={15}/>MAP / DIRECTION</a>}</div>;
 return <section className="panel workspace customerWorkspace"><header><div><span className="eyebrow">TORVO CUSTOMER APP</span><h3>SEARCH · FILTER · FIND DEALER</h3><p>FAST SPARE PART DISCOVERY WITHOUT PUBLIC SELLING PRICE. RETAIL PRICE, PAYMENT AND DELIVERY STAY BETWEEN CUSTOMER AND DEALER.</p></div></header>{err&&<div className="inlineError" role="alert">{err}</div>}<ProductDiscoveryRail target="website" onProductSelect={x=>setSelected(s=>({...s,...x}))}/>{settings.customer_catalog_enabled?<ProductDiscovery selectedId={selected?.id} onSelect={x=>setSelected(s=>({...s,...x}))}/>:<div className="modalNotice">CUSTOMER CATALOG IS CURRENTLY PAUSED BY TORVO.</div>}
 <section className="panel customerFinder"><header><div><span className="eyebrow">{selected?'SELECTED PRODUCT':'MISSING PRODUCT'}</span><h3>{selected?productLabel:"CAN'T FIND IT? REQUEST THIS ITEM"}</h3><p>{selected?'FIND AN APPROVED DEALER OR SUBMIT A CONFIRMED REQUIREMENT.':'RAW SEARCH TYPING DOES NOT CREATE A CUSTOMER LEAD.'}</p></div>{!selected&&<Search/>}</header><div className="workFilters"><label className="pinField"><MapPin size={16}/><input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 DIGIT PIN CODE"/></label>{selected&&<button type="button" className="primary" disabled={busy} onClick={find}>FIND NEARBY DEALER</button>}<button type="button" disabled={busy} onClick={openDemand}>REQUEST THIS ITEM</button></div></section>
 {open==='dealers'&&<div className="modalLayer"><section className="dealerActionModal customerDealerModal"><header><div><span className="eyebrow">VERIFIED TORVO NETWORK</span><h3>DEALERS SERVING PIN {pin}</h3></div><button type="button" className="iconBtn" disabled={busy} onClick={close}><X/></button></header><div className="requestList dealerResults">{dealers.length?dealers.map(d=><article key={d.dealer_id}><div><div className="dealerTitle"><ShieldCheck size={17}/><strong>{d.shop_name}</strong></div><span>{d.address}</span><small>{d.match_type==='EXACT_PIN'?'VERIFIED EXACT PIN COVERAGE':'VERIFIED SERVICE AREA'}</small>{d.authorized_service_center&&<small className="authorizedText">AUTHORIZED SERVICE CENTER</small>}</div><button type="button" className="primary" disabled={busy} onClick={()=>selectDealer(d)}>{busy?'LOADING…':'VIEW DEALER'}</button></article>):<div className="empty"><MapPin/><h3>NO VERIFIED DEALER COVERAGE</h3><p>SUBMIT YOUR REQUIREMENT AND TORVO CAN HELP CHECK PAN-INDIA SOURCING.</p><button type="button" className="primary" disabled={busy} onClick={openDemand}>REQUEST THIS ITEM</button></div>}</div></section></div>}
 {open==='details'&&dp&&<div className="modalLayer"><form className="dealerActionModal customerDealerModal" onSubmit={createReferral}><header><div><span className="eyebrow"><ShieldCheck size={13}/> VERIFIED TORVO DEALER</span><h3>{dp.shop_name}</h3></div><button type="button" className="iconBtn" disabled={busy} onClick={close}><X/></button></header><div className="modalForm">{capabilities}{dp.authorized_service_center&&dp.authorized_service_note&&<div className="modalNotice authorizedNote"><BadgeCheck size={16}/> {U(dp.authorized_service_note)}</div>}<div className="modalNotice dealerAddress"><MapPin size={16}/> {[dp.address,dp.city,dp.district,dp.state,dp.pin_code].filter(Boolean).join(' · ')}</div>{dealerActions}<div className="modalNotice selectedProductNote"><ShoppingBag size={16}/><strong>SELECTED PRODUCT:</strong> {U(productLabel)}</div><label>NAME<input maxLength="120" value={form.name} onChange={e=>setForm({...form,name:e.target.value.toUpperCase()})} disabled={busy} required/></label><label>MOBILE / WHATSAPP<input inputMode="numeric" maxLength="10" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} disabled={busy} required/></label><label className="checkRow"><input type="checkbox" checked={form.marketing} onChange={e=>setForm({...form,marketing:e.target.checked})} disabled={busy}/> RECEIVE TORVO UPDATES ON WHATSAPP</label><div className="modalNotice privacyNote">YOUR CONTACT DETAILS ARE USED FOR THIS REFERRAL. PROMOTIONAL WHATSAPP UPDATES REQUIRE THE SEPARATE CHECKBOX ABOVE.</div></div><footer><button type="button" disabled={busy} onClick={close}>CANCEL</button><button className="primary" type="submit" disabled={busy}>{busy?'CREATING…':'GET TORVO REFERRAL CODE'}</button></footer></form></div>}
 {open==='demand'&&<div className="modalLayer"><form className="dealerActionModal" onSubmit={submitDemand}><header><h3>REQUEST THIS ITEM</h3><button type="button" className="iconBtn" disabled={busy} onClick={close}><X/></button></header><div className="modalForm"><label>NAME<input maxLength="120" value={demand.name} onChange={e=>setDemand({...demand,name:e.target.value.toUpperCase()})} disabled={busy} required/></label><label>MOBILE / WHATSAPP<input inputMode="numeric" maxLength="10" value={demand.mobile} onChange={e=>setDemand({...demand,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} disabled={busy} required/></label><label>PIN CODE<input inputMode="numeric" maxLength="6" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} disabled={busy} required/></label><label>ITEM / SEARCH<input maxLength="200" value={demand.search} onChange={e=>setDemand({...demand,search:e.target.value.toUpperCase()})} disabled={busy} required/></label><PublicCatalogDropdowns value={demand} onChange={setDemand} disabled={busy}/><label>REQUIREMENT NOTE<textarea maxLength="500" value={demand.note} onChange={e=>setDemand({...demand,note:e.target.value.toUpperCase()})} disabled={busy}/></label><label className="checkRow"><input type="checkbox" checked={demand.marketing} onChange={e=>setDemand({...demand,marketing:e.target.checked})} disabled={busy}/> RECEIVE TORVO UPDATES ON WHATSAPP</label><div className="modalNotice">CUSTOMER CONTACT IS NOT PUBLICLY BROADCAST TO DEALERS.</div></div><footer><button type="button" disabled={busy} onClick={close}>CANCEL</button><button className="primary" type="submit" disabled={busy}>{busy?'SUBMITTING…':'SUBMIT REQUIREMENT'}</button></footer></form></div>}
 {open==='demandDone'&&demandResult&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>TORVO PRODUCT REQUEST CREATED</h3><CheckCircle2/></header><div className="inlineSuccess" role="status">REQUEST ID: {String(demandResult.demand_id).slice(0,8).toUpperCase()}</div><footer><button type="button" disabled={busy} onClick={close}>CLOSE</button><button type="button" disabled={busy} onClick={checkDemand}><RefreshCw size={15}/>CHECK STATUS</button><button type="button" className="primary" disabled={busy} onClick={askTorvo}>ASK TORVO PAN-INDIA HELP</button></footer></section></div>}
 {open==='torvoHelp'&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>WE WILL CHECK THE ITEM</h3><Headphones/></header><div className="inlineSuccess" role="status">REQUEST STATUS: {U(demandResult?.status||'SOURCING')}</div><div className="modalNotice">TORVO WILL CHECK ITS NETWORK. AVAILABILITY IS NOT GUARANTEED.</div><footer><button type="button" disabled={busy} onClick={checkDemand}>CHECK STATUS</button><a href={`tel:${support}`}><Phone size={15}/> CALL {support}</a><button type="button" disabled={busy} onClick={close}>CLOSE</button></footer></section></div>}
 {open==='demandStatus'&&demandResult&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>CUSTOMER REQUIREMENT STATUS</h3><CheckCircle2/></header><div className="inlineSuccess" role="status">{U(demandResult.message||`STATUS: ${demandResult.status||'SOURCING'}`)}</div>{String(demandResult.status||'').toLowerCase()==='available'&&demandResult.found_contact_note&&<div className="modalNotice">{U(demandResult.found_contact_note)}</div>}<footer><button type="button" disabled={busy} onClick={checkDemand}>REFRESH STATUS</button><button type="button" disabled={busy} onClick={close}>CLOSE</button></footer></section></div>}
 {open==='referral'&&ref&&<div className="modalLayer"><section className="dealerActionModal referralSuccess"><header><div><span className="eyebrow">TORVO DEALER REFERRAL</span><h3>{ref.referral_code}</h3></div><QrCode/></header>{dp?.shop_name&&<div className="inlineSuccess" role="status"><CheckCircle2 size={16}/> SELECTED DEALER: {dp.shop_name}</div>}<div className="modalNotice"><strong>PRODUCT:</strong> {U(productLabel)}<br/>SHOW THIS TORVO REFERRAL CODE TO THE SELECTED DEALER.</div>{capabilities}{dp&&dealerActions}<footer><button type="button" disabled={busy} onClick={close}>CLOSE</button></footer></section></div>}
 {settings.repair_service_enabled&&<section className="panel"><header><div><span className="eyebrow">SERVICE NETWORK</span><h3>MACHINE REPAIR & SERVICE</h3></div><Wrench/></header><button type="button" className="primary" disabled={busy} onClick={()=>{setErr('');setRepairResult(null);setOpen('repair')}}>SEND REPAIR REQUIREMENT</button></section>}
 {open==='repair'&&<div className="modalLayer"><form className="dealerActionModal" onSubmit={submitRepair}><header><h3>TELL US THE MACHINE PROBLEM</h3><button type="button" className="iconBtn" disabled={busy} onClick={close}><X/></button></header><div className="modalForm"><label>NAME<input maxLength="120" value={repair.name} onChange={e=>setRepair({...repair,name:e.target.value.toUpperCase()})} disabled={busy} required/></label><label>MOBILE / WHATSAPP<input inputMode="numeric" maxLength="10" value={repair.mobile} onChange={e=>setRepair({...repair,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} disabled={busy} required/></label><label>PIN CODE<input inputMode="numeric" maxLength="6" value={repair.pin} onChange={e=>setRepair({...repair,pin:e.target.value.replace(/\D/g,'').slice(0,6))} disabled={busy} required/></label><PublicCatalogDropdowns value={repair} onChange={setRepair} disabled={busy}/><label>PROBLEM DESCRIPTION<textarea maxLength="1000" value={repair.problem} onChange={e=>setRepair({...repair,problem:e.target.value.toUpperCase()})} disabled={busy} required/></label><label className="checkRow"><input type="checkbox" checked={repair.marketing} onChange={e=>setRepair({...repair,marketing:e.target.checked})} disabled={busy}/> RECEIVE TORVO UPDATES ON WHATSAPP</label></div><footer><button type="button" disabled={busy} onClick={close}>CANCEL</button><button className="primary" type="submit" disabled={busy}>{busy?'SUBMITTING…':'SUBMIT REPAIR REQUEST'}</button></footer></form></div>}
 {open==='repairDone'&&repairResult&&<div className="modalLayer"><section className="dealerActionModal"><header><h3>REPAIR REQUEST RECEIVED</h3><CheckCircle2/></header><div className="inlineSuccess" role="status">REQUEST ID: {String(repairResult.requirement_id).slice(0,8).toUpperCase()}</div><button type="button" disabled={busy} onClick={close}>CLOSE</button></section></div>}
 <div className="modalNotice"><Headphones size={16}/> TORVO SUPPORT: {support} · CUSTOMER RETAIL TRANSACTION REMAINS BETWEEN CUSTOMER AND DEALER.</div></section>;
}
