import React,{useEffect,useState}from'react';
import{Check,LoaderCircle,Search}from'lucide-react';
import{dealerCatalogService}from'../services/dealerCatalogService';
import{normalizeSearchInput}from'../services/textNormalization';

export default function DealerCatalogItemFinder({selectedIds=[],onChoose}){
 const[q,setQ]=useState(''),[type,setType]=useState(''),[brand,setBrand]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const narrowed=!!q.trim()||!!type||!!brand.trim();
 useEffect(()=>{if(!narrowed){setRows([]);setBusy(false);return}let alive=true;const t=setTimeout(async()=>{setBusy(true);setError('');try{const x=await dealerCatalogService.search(q,type,brand,60);if(alive)setRows(x)}catch(e){if(alive)setError(e.message)}finally{if(alive)setBusy(false)}},q?220:0);return()=>{alive=false;clearTimeout(t)}},[q,type,brand,narrowed]);
 return <div className="dealerCatalogFinder"><div className="purchaseFinderTools"><label><Search size={17}/><input value={q} onChange={e=>setQ(normalizeSearchInput(e.target.value))} placeholder="ITEM CODE, OEM, PRODUCT NAME…" autoCapitalize="characters"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">ALL TYPES</option><option value="machine">MACHINE</option><option value="spare_part">SPARE PART</option><option value="accessory">ACCESSORY</option></select><input value={brand} onChange={e=>setBrand(normalizeSearchInput(e.target.value))} placeholder="BRAND FILTER" autoCapitalize="characters"/></div><div className="purchaseFinderCount">{busy?<><LoaderCircle size={13}/> SEARCHING…</>:narrowed?<>SHOWING {rows.length}{rows.length===60?' BEST MATCHES — TYPE MORE TO NARROW':''}</>:<>SEARCH OR CHOOSE TYPE / BRAND TO FIND PRODUCTS</>}</div><div className="purchaseFinderList dealerFinderList">{error?<div className="purchaseError">{error}</div>:rows.map(x=><button type="button" key={x.id} disabled={selectedIds.includes(x.id)} onClick={()=>onChoose(x)}><span><b>{x.item_code}</b><strong>{x.name}</strong><small>{[x.brand,x.category,x.oem_code&&`OEM ${x.oem_code}`].filter(Boolean).join(' · ')}</small></span>{selectedIds.includes(x.id)?<Check size={18}/>:<span>ADD</span>}</button>)}{!busy&&narrowed&&!rows.length&&<div className="purchaseEmpty">NO MATCHING ACTIVE ITEM.</div>}{!narrowed&&<div className="purchaseEmpty">FULL CATALOG LOADING IS AVOIDED FOR FASTER DEALER PORTAL PERFORMANCE.</div>}</div></div>;
}
