import React,{useEffect,useState}from'react';
import{Check,LoaderCircle,Search}from'lucide-react';
import{dealerCatalogService}from'../services/dealerCatalogService';

export default function DealerCatalogItemFinder({selectedIds=[],onChoose}){
 const[q,setQ]=useState(''),[type,setType]=useState(''),[brand,setBrand]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const narrowed=!!q.trim()||!!type||!!brand.trim();
 useEffect(()=>{if(!narrowed){setRows([]);setBusy(false);return}let alive=true;const t=setTimeout(async()=>{setBusy(true);setError('');try{const x=await dealerCatalogService.search(q,type,brand,60);if(alive)setRows(x)}catch(e){if(alive)setError(e.message)}finally{if(alive)setBusy(false)}},q?220:0);return()=>{alive=false;clearTimeout(t)}},[q,type,brand,narrowed]);
 return <div className="dealerCatalogFinder"><div className="purchaseFinderTools"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Item code, OEM, product name…"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">All Types</option><option value="machine">Machine</option><option value="spare_part">Spare Part</option><option value="accessory">Accessory</option></select><input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="Brand filter"/></div><div className="purchaseFinderCount">{busy?<><LoaderCircle size={13}/> Searching…</>:narrowed?<>Showing {rows.length}{rows.length===60?' best matches — type more to narrow':''}</>:<>Search or choose Type / Brand to find products</>}</div><div className="purchaseFinderList dealerFinderList">{error?<div className="purchaseError">{error}</div>:rows.map(x=><button type="button" key={x.id} disabled={selectedIds.includes(x.id)} onClick={()=>onChoose(x)}><span><b>{x.item_code}</b><strong>{x.name}</strong><small>{[x.brand,x.category,x.oem_code&&`OEM ${x.oem_code}`].filter(Boolean).join(' · ')}</small></span>{selectedIds.includes(x.id)?<Check size={18}/>:<span>ADD</span>}</button>)}{!busy&&narrowed&&!rows.length&&<div className="purchaseEmpty">No matching active item.</div>}{!narrowed&&<div className="purchaseEmpty">Full catalog loading is avoided for faster Dealer Portal performance.</div>}</div></div>;
}
