import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{AlertCircle,CheckCircle2,FilePlus2,RefreshCw}from'lucide-react';
import{secureDealerLegacy as data}from'../services/dealerLegacyBridge';
import DealerDirectAdditionalPOModal from'./DealerDirectAdditionalPOModal';
const id=v=>String(v||'').trim();const U=v=>String(v||'').trim().toUpperCase();const kind=v=>String(v||'').trim().toLowerCase();
const orderId=o=>id(o?.id||o?.order_id);const label=o=>U(o?.order_number||o?.document_number||orderId(o));const linkIds=o=>new Set([id(o?.id),id(o?.order_id),id(o?.root_order_id),id(o?.parent_id),id(o?.sales_order_id),id(o?.original_sales_order_id)].filter(Boolean));
const isBaseSalesOrder=o=>kind(o?.doc_type)==='sales_order'&&!id(o?.parent_id)&&!['additional_pending_approval','additional_approved','additional_rejected'].includes(kind(o?.status));
const estimateMatches=(estimate,order)=>{const oid=orderId(order);if(!oid)return false;const links=linkIds(estimate);return links.has(oid)||[...linkIds(order)].some(x=>x!==oid&&links.has(x))};
export default function DealerAdditionalPOWorkspace(){
 const[docs,setDocs]=useState([]),[selectedId,setSelectedId]=useState(''),[active,setActive]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[ok,setOk]=useState('');const loading=useRef(false),mounted=useRef(true),reloadQueued=useRef(false);
 const load=useCallback(async()=>{if(loading.current){reloadQueued.current=true;return}loading.current=true;if(mounted.current){setBusy(true);setErr('')}try{const rows=await data.dealerOrderHistory();if(mounted.current)setDocs(Array.isArray(rows)?rows:[])}catch(e){if(mounted.current)setErr(U(e?.message)||'ORDER HISTORY COULD NOT BE LOADED')}finally{loading.current=false;if(mounted.current)setBusy(false);if(reloadQueued.current){reloadQueued.current=false;queueMicrotask(load)}}},[]);
 useEffect(()=>{mounted.current=true;load();return()=>{mounted.current=false}},[load]);
 useEffect(()=>{const changed=()=>load();window.addEventListener('torvo:dealer-order-created',changed);return()=>window.removeEventListener('torvo:dealer-order-created',changed)},[load]);
 const eligible=useMemo(()=>{const estimates=docs.filter(x=>kind(x?.doc_type)==='estimate');const seen=new Set();return docs.filter(isBaseSalesOrder).filter(o=>estimates.some(e=>estimateMatches(e,o))).filter(o=>{const oid=orderId(o);if(!oid||seen.has(oid))return false;seen.add(oid);return true}).sort((a,b)=>label(a).localeCompare(label(b)))},[docs]);
 const selected=useMemo(()=>eligible.find(o=>orderId(o)===selectedId)||null,[eligible,selectedId]);
 useEffect(()=>{if(selectedId&&!eligible.some(o=>orderId(o)===selectedId))setSelectedId('')},[eligible,selectedId]);
 const created=async result=>{setActive(null);setSelectedId('');setOk(`ADDITIONAL PURCHASE ORDER CREATED${result?.order_id?` · ${result.order_id}`:''}.`);await load()};
 const open=()=>{if(!selected){setErr('SELECT AN ELIGIBLE SALES ORDER FIRST.');return}setErr('');setOk('');setActive(selected)};
 if(!busy&&!err&&!ok&&!eligible.length)return null;
 return <><section className="panel approvedAddOnPanel"><header><div><span className="eyebrow">ESTIMATE CREATED</span><h3>ADD MORE ITEMS</h3><p>SELECT AN ORIGINAL SALES ORDER FROM THE DROPDOWN. ONLY ORDERS WITH AN ESTIMATE ARE AVAILABLE.</p></div><button type="button" className="iconBtn" disabled={busy} onClick={load} aria-label="REFRESH ELIGIBLE ORDERS"><RefreshCw size={17}/></button></header>{err&&<div className="inlineError" role="alert"><AlertCircle size={16}/>{err}</div>}{ok&&<div className="inlineSuccess"><CheckCircle2 size={16}/>{ok}</div>}{busy&&!docs.length?<div className="miniEmpty">CHECKING ELIGIBLE SALES ORDERS…</div>:eligible.length?<div className="field"><span>ORIGINAL SALES ORDER</span><select value={selectedId} disabled={busy} onChange={e=>{setSelectedId(e.target.value);setErr('');setOk('')}}><option value="">SELECT SALES ORDER</option>{eligible.map(o=><option key={orderId(o)} value={orderId(o)}>{label(o)} · ESTIMATE CREATED</option>)}</select>{selected&&<div className="modalNotice"><strong>SELECTED: SALES ORDER {label(selected)}</strong><br/>STATUS: {U(selected.status)||'ORDER ACTIVE'} · ORIGINAL ORDER / ESTIMATE WILL REMAIN UNCHANGED.</div>}<button type="button" className="primary" disabled={busy||!selected} onClick={open}><FilePlus2 size={14}/>ADD MORE ITEMS</button></div>:ok?<div className="miniEmpty">NO OTHER ESTIMATE-CREATED SALES ORDER IS CURRENTLY AVAILABLE.</div>:null}</section>{active&&<DealerDirectAdditionalPOModal order={active} onClose={()=>setActive(null)} onCreated={created}/>}</>;
}
