import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{AlertCircle,CheckCircle2,FilePlus2,RefreshCw}from'lucide-react';
import{secureDealerLegacy as data}from'../services/dealerLegacyBridge';
import DealerDirectAdditionalPOModal from'./DealerDirectAdditionalPOModal';
const id=v=>String(v||'').trim();const U=v=>String(v||'').trim().toUpperCase();const kind=v=>String(v||'').trim().toLowerCase();const POLL_MS=60000;
const orderId=o=>id(o?.id||o?.order_id);const label=o=>U(o?.order_number||o?.document_number||orderId(o));
const isBaseSalesOrder=o=>kind(o?.doc_type)==='sales_order'&&!id(o?.parent_id)&&!['additional_pending_approval','additional_approved','additional_rejected'].includes(kind(o?.status));
const estimateMatches=(estimate,order)=>id(estimate?.linked_sales_order_id)===orderId(order);
export default function DealerAdditionalPOWorkspace(){
 const[docs,setDocs]=useState([]),[selectedId,setSelectedId]=useState(''),[active,setActive]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[ok,setOk]=useState('');const loading=useRef(false),mounted=useRef(true),reloadQueued=useRef(false);
 const load=useCallback(async({silent=false}={})=>{if(loading.current){reloadQueued.current=true;return}loading.current=true;if(mounted.current&&!silent){setBusy(true);setErr('')}try{const rows=await data.dealerOrderHistory();if(mounted.current){setDocs(Array.isArray(rows)?rows:[]);if(!silent)setErr('')}}catch(e){if(mounted.current&&!silent){setDocs([]);setErr(U(e?.message)||'ORDER HISTORY COULD NOT BE LOADED')}}finally{loading.current=false;if(mounted.current&&!silent)setBusy(false);if(reloadQueued.current){reloadQueued.current=false;queueMicrotask(()=>load({silent:true}))}}},[]);
 useEffect(()=>{mounted.current=true;load();const refresh=()=>load({silent:true});const visible=()=>{if(document.visibilityState==='visible')refresh()};const timer=window.setInterval(()=>{if(document.visibilityState==='visible')refresh()},POLL_MS);window.addEventListener('torvo:dealer-order-created',refresh);window.addEventListener('torvo:dealer-payment-updated',refresh);window.addEventListener('torvo:dealer-delivery-updated',refresh);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',visible);return()=>{mounted.current=false;window.clearInterval(timer);window.removeEventListener('torvo:dealer-order-created',refresh);window.removeEventListener('torvo:dealer-payment-updated',refresh);window.removeEventListener('torvo:dealer-delivery-updated',refresh);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',visible)}},[load]);
 const eligible=useMemo(()=>{const estimates=docs.filter(x=>kind(x?.doc_type)==='estimate'&&id(x?.linked_sales_order_id));const seen=new Set();return docs.filter(isBaseSalesOrder).filter(o=>estimates.some(e=>estimateMatches(e,o))).filter(o=>{const oid=orderId(o);if(!oid||seen.has(oid))return false;seen.add(oid);return true}).sort((a,b)=>label(a).localeCompare(label(b)))},[docs]);
 const selected=useMemo(()=>eligible.find(o=>orderId(o)===selectedId)||null,[eligible,selectedId]);
 useEffect(()=>{if(selectedId&&!eligible.some(o=>orderId(o)===selectedId)){setSelectedId('');setActive(null)}},[eligible,selectedId]);
 const created=async result=>{setActive(null);setSelectedId('');setOk(`ADDITIONAL PURCHASE ORDER CREATED${result?.order_id?` · ${result.order_id}`:''}.`);window.dispatchEvent(new CustomEvent('torvo:dealer-order-created',{detail:{order_id:result?.order_id||null,parent_order_id:result?.parent_order_id||null,source:'ADDITIONAL_PURCHASE_ORDER'}}));await load({silent:true})};
 const open=()=>{if(!selected){setErr('SELECT AN ELIGIBLE SALES ORDER FIRST.');return}setErr('');setOk('');setActive(selected)};
 if(!busy&&!err&&!ok&&!eligible.length)return null;
 return <><section className="panel approvedAddOnPanel"><header><div><span className="eyebrow">ESTIMATE CREATED</span><h3>ADD MORE ITEMS</h3><p>SELECT AN ORIGINAL SALES ORDER FROM THE DROPDOWN. ONLY ORDERS WITH A LINKED ESTIMATE ARE AVAILABLE.</p></div><button type="button" className="iconBtn" disabled={busy} onClick={()=>load()} aria-label="REFRESH ELIGIBLE ORDERS"><RefreshCw size={17}/></button></header>{err&&<div className="inlineError" role="alert"><AlertCircle size={16}/>{err}</div>}{ok&&<div className="inlineSuccess"><CheckCircle2 size={16}/>{ok}</div>}{busy&&!docs.length?<div className="miniEmpty">CHECKING ELIGIBLE SALES ORDERS…</div>:eligible.length?<div className="field"><span>ORIGINAL SALES ORDER</span><select value={selectedId} disabled={busy} onChange={e=>{setSelectedId(e.target.value);setErr('');setOk('')}}><option value="">SELECT SALES ORDER</option>{eligible.map(o=><option key={orderId(o)} value={orderId(o)}>{label(o)} · ESTIMATE CREATED</option>)}</select>{selected&&<div className="modalNotice"><strong>SELECTED: SALES ORDER {label(selected)}</strong><br/>STATUS: {U(selected.status)||'ORDER ACTIVE'} · ORIGINAL ORDER / ESTIMATE WILL REMAIN UNCHANGED.</div>}<button type="button" className="primary" disabled={busy||!selected} onClick={open}><FilePlus2 size={14}/>ADD MORE ITEMS</button></div>:ok?<div className="miniEmpty">NO OTHER ESTIMATE-CREATED SALES ORDER IS CURRENTLY AVAILABLE.</div>:null}</section>{active&&<DealerDirectAdditionalPOModal order={active} onClose={()=>setActive(null)} onCreated={created}/>}</>;
}
