import React,{useCallback,useEffect,useRef,useState}from'react';
import{AlertCircle,CheckCircle2,PlusCircle,RefreshCw}from'lucide-react';
import{secureDealerLegacy as data}from'../services/dealerLegacyBridge';
import DealerAddOnOrderModal from'./DealerAddOnOrderModal';
const U=v=>String(v||'').trim().toUpperCase();const rid=r=>String(r?.id||r?.request_id||'').trim();
const when=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-GB')};
export default function DealerApprovedAddOnOrders({onOrderCreated}){
 const[requests,setRequests]=useState([]),[active,setActive]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[ok,setOk]=useState('');const loading=useRef(false),mounted=useRef(true);
 const load=useCallback(async()=>{if(loading.current)return;loading.current=true;if(mounted.current){setBusy(true);setErr('')}try{const rows=await data.dealerApprovedAddOnRequests();if(mounted.current)setRequests(Array.isArray(rows)?rows:[])}catch(e){if(mounted.current)setErr(U(e?.message)||'APPROVED REQUESTS COULD NOT BE LOADED')}finally{loading.current=false;if(mounted.current)setBusy(false)}},[]);
 useEffect(()=>{mounted.current=true;load();return()=>{mounted.current=false}},[load]);
 const created=async result=>{const orderId=String(result?.order_id||'').trim();setActive(null);setOk(orderId?`ADDITIONAL PURCHASE ORDER CREATED · ${orderId}`:'ADDITIONAL PURCHASE ORDER CREATED.');await load();onOrderCreated?.(result)};
 const open=r=>{if(!rid(r)){setErr('APPROVED REQUEST ID IS MISSING.');return}setErr('');setOk('');setActive(r)};
 if(!busy&&!err&&!ok&&!requests.length)return null;
 return <><section className="panel approvedAddOnPanel"><header><div><span className="eyebrow">APPROVED BY TORVO</span><h3>ADDITIONAL PURCHASE ORDERS</h3><p>APPROVED ADD MORE ITEMS REQUESTS WAITING FOR YOUR ITEM SELECTION.</p></div><button type="button" className="iconBtn" disabled={busy} onClick={load} title="REFRESH APPROVALS" aria-label="REFRESH APPROVED ADDITIONAL ORDERS"><RefreshCw size={17}/></button></header>{err&&<div className="inlineError" role="alert"><AlertCircle size={16}/>{err}</div>}{ok&&<div className="inlineSuccess"><CheckCircle2 size={16}/>{ok}</div>}{busy&&!requests.length?<div className="miniEmpty">CHECKING APPROVED REQUESTS…</div>:requests.length?<div className="requestList">{requests.filter(r=>rid(r)).map(r=><article key={rid(r)}><div><strong><CheckCircle2 size={14}/> ADD MORE ITEMS APPROVED</strong><span>{U(r.reason)||'ADDITIONAL ITEMS APPROVED'}</span><small>{when(r.reviewed_at||r.created_at)}{r.admin_note?` · TORVO: ${U(r.admin_note)}`:''}</small></div><b className="status approved">APPROVED</b><button type="button" className="primary" disabled={busy} onClick={()=>open(r)}><PlusCircle size={14}/>CREATE ADDITIONAL ORDER</button></article>)}</div>:ok?<div className="miniEmpty">NO OTHER APPROVED ADD MORE ITEMS REQUEST IS PENDING.</div>:null}</section>{active&&<DealerAddOnOrderModal request={active} onClose={()=>setActive(null)} onCreated={created}/>}</>;
}
