import React,{useEffect,useMemo,useState}from'react';
import{Check,LoaderCircle,Search}from'lucide-react';
import{dealerCatalogService}from'../services/dealerCatalogService';
import{normalizeSearchInput}from'../services/textNormalization';
const U=v=>String(v||'').trim().toUpperCase();const pid=x=>String(x?.id||x?.item_id||x?.product_id||'').trim();
export default function DealerCatalogItemFinder({selectedIds=[],onChoose}){
 const[q,setQ]=useState(''),[type,setType]=useState(''),[brand,setBrand]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const selected=useMemo(()=>new Set(selectedIds.map(x=>String(x||'').trim()).filter(Boolean)),[selectedIds]);
 const narrowed=!!q.trim()||!!type||!!brand.trim();
 useEffect(()=>{if(!narrowed){setRows([]);setBusy(false);setError('');return}let alive=true;const t=setTimeout(async()=>{setBusy(true);setError('');try{const x=await dealerCatalogService.search(q,type,brand,60);if(alive)setRows(x)}catch(e){if(alive){setRows([]);setError(U(e?.message)||'CATALOG SEARCH COULD NOT BE COMPLETED')}}finally{if(alive)setBusy(false)}},q?220:0);return()=>{alive=false;clearTimeout(t)}},[q,type,brand,narrowed]);
 return <div className="dealerCatalogFinder"><div className="purchaseFinderTools"><label><Search size={17}/><input value={q} maxLength="120" onChange={e=>setQ(normalizeSearchInput(e.target.value))} placeholder="ITEM CODE, OEM, PRODUCT NAME…" autoCapitalize="characters"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">PRODUCT TYPE</option><option value="machine">MACHINE</option><option value="spare_part">SPARE PART</option><option value="accessory">ACCESSORY</option></select><input value={brand} maxLength="80" onChange={e=>setBrand(normalizeSearchInput(e.target.value))} placeholder="BRAND FILTER" autoCapitalize="characters"/></div><div className="purchaseFinderCount">{busy?<><LoaderCircle size={13}/> SEARCHING…</>:narrowed?<>SHOWING {rows.length}{rows.length===60?' BEST MATCHES — TYPE MORE TO NARROW':''}</>:<>SEARCH OR CHOOSE PRODUCT TYPE / BRAND TO FIND PRODUCTS</>}</div><div className="purchaseFinderList dealerFinderList">{error?<div className="purchaseError">{error}</div>:rows.map(x=>{const k=pid(x),chosen=selected.has(k);return <button type="button" key={k} disabled={chosen} onClick={()=>onChoose?.({...x,id:k})}><span><b>{U(x.item_code)}</b><strong>{U(x.name)}</strong><small>{[x.brand&&U(x.brand),x.category&&U(x.category),x.oem_code&&`OEM ${U(x.oem_code)}`].filter(Boolean).join(' · ')}</small></span>{chosen?<Check size={18}/>:<span>ADD</span>}</button>})}{!busy&&narrowed&&!error&&!rows.length&&<div className="purchaseEmpty">NO MATCHING ACTIVE ITEM.</div>}{!narrowed&&<div className="purchaseEmpty">FULL CATALOG LOADING IS AVOIDED FOR FASTER DEALER PORTAL PERFORMANCE.</div>}</div></div>;
}
