import React,{useEffect,useMemo,useState}from'react';import'../dealer-service-book-ui.css';import{Camera,ClipboardList,History,Image as ImageIcon,Plus,Truck,UserRound,Wrench}from'lucide-react';
const complaints=['NOT STARTING','LOW POWER','NOISY / VIBRATION','HEATING','SPARKING','SWITCH PROBLEM','BEARING / GEAR NOISE','CHUCK / HOLDER PROBLEM','CABLE / POWER PROBLEM','OTHER'];
export default function DealerServiceBookPreview(){const[photo,setPhoto]=useState('');const[tab,setTab]=useState('IN SHOP');const[complaint,setComplaint]=useState('');const preview=useMemo(()=>photo?URL.createObjectURL(photo):'',[photo]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);return <div className="serviceBook">
<div className="serviceBookStats"><article><Wrench/><b>IN SHOP</b><strong>—</strong></article><article><Wrench/><b>REPAIRING</b><strong>—</strong></article><article><ClipboardList/><b>READY</b><strong>—</strong></article><article><Truck/><b>DELIVERED</b><strong>—</strong></article></div>
<div className="serviceBookTabs">{['IN SHOP','NEW JOB CARD','HISTORY'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='NEW JOB CARD'?<Plus/>:x==='HISTORY'?<History/>:<Wrench/>}{x}</button>)}</div>
{tab==='NEW JOB CARD'?<div className="serviceJobForm"><section><h3><UserRound/> CUSTOMER / MACHINE OWNER</h3><div className="serviceGrid"><input placeholder="CUSTOMER NAME"/><input inputMode="tel" placeholder="MOBILE NUMBER"/><input inputMode="tel" placeholder="WHATSAPP NUMBER"/><input placeholder="ADDRESS / CITY"/></div></section>
<section><h3><Camera/> MACHINE PHOTO & IDENTITY</h3><label className="servicePhoto">{preview?<img src={preview} alt="MACHINE PREVIEW"/>:<><ImageIcon/><b>TAKE / ADD ORIGINAL MACHINE PHOTO</b><span>GENUINE PHOTO FIRST — NO FAKE PRODUCT IMAGE</span></>}<input type="file" accept="image/*" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||'')}/></label><div className="serviceGrid"><input placeholder="BRAND"/><input placeholder="MACHINE TYPE"/><input placeholder="MODEL"/><input placeholder="SERIAL / IDENTIFICATION (OPTIONAL)"/></div></section>
<section><h3><Wrench/> COMPLAINT</h3><select value={complaint} onChange={e=>setComplaint(e.target.value)}><option value="">SELECT COMPLAINT</option>{complaints.map(x=><option key={x}>{x}</option>)}</select><textarea rows="3" placeholder="ADDITIONAL COMPLAINT / NOTES (OPTIONAL)"/></section>
<div className="servicePending">JOB CARD SAVE WILL CONNECT ONLY TO THE DEVICE-BOUND SERVER CONTRACT. THIS PREVIEW DOES NOT CREATE A FAKE REPAIR RECORD.</div><button className="serviceSave" disabled>CREATE MACHINE IN / JOB CARD</button></div>:<div className="serviceEmpty"><ClipboardList/><h3>{tab==='HISTORY'?'SERVICE HISTORY':'MACHINES CURRENTLY IN SHOP'}</h3><p>REAL DEALER JOBS WILL APPEAR HERE AFTER THE DEVICE-BOUND SERVICE BOOK BACKEND IS INSTALLED AND ACCEPTED.</p></div>}
</div>}