import React,{useEffect,useState}from'react';
import{CheckCircle2,Clock3,RefreshCw,ShieldCheck,UserRound,XCircle}from'lucide-react';
import{currentAppUser,forceSignOut}from'../services/auth';
import{beginStaffEmailOtp,verifyStaffEmailOtp,normalizeStaffUsername,isStaffUserIdFormat}from'../services/staffAuth';
import{roleRuntimeAllowed}from'../services/runtimePlatform';

export default function OperationalStaffLogin({onAuthenticated}){
 const[username,setUsername]=useState(''),[challenge,setChallenge]=useState(''),[otp,setOtp]=useState(''),[sent,setSent]=useState(false),[resend,setResend]=useState(0),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{if(!sent||resend<=0)return;const t=setTimeout(()=>setResend(x=>x-1),1000);return()=>clearTimeout(t)},[sent,resend]);
 const normalized=normalizeStaffUsername(username),valid=isStaffUserIdFormat(normalized);
 const send=async()=>{if(!valid||busy)return;setBusy(true);setErr('');setNotice('');try{const r=await beginStaffEmailOtp(normalized);setChallenge(r.challenge_id);setOtp('');setSent(true);setResend(Number(r.resend_after_seconds)||45);setNotice('OTP SENT TO THE REGISTERED TORVO SECURITY EMAIL.')}catch(e){setErr(e?.message||'OTP COULD NOT BE SENT.')}finally{setBusy(false)}};
 const verify=async()=>{if(busy||otp.length!==6||!challenge)return;setBusy(true);setErr('');try{const r=await verifyStaffEmailOtp(normalized,challenge,otp);if(!['salesman','store_keeper'].includes(String(r?.role||'').toLowerCase())){await forceSignOut();throw new Error('THIS USER ID IS NOT AUTHORIZED FOR THE OPERATIONAL APP.')}const u=await currentAppUser();if(!u?.active||!['salesman','store_keeper'].includes(String(u.role||'').toLowerCase())||!roleRuntimeAllowed(u.role)){await forceSignOut();throw new Error('ACTIVE SALESMAN / STORE KEEPER APP ACCOUNT REQUIRED.')}onAuthenticated?.(u)}catch(e){setErr(e?.message||'OTP VERIFICATION FAILED.')}finally{setBusy(false)}};
 return <main className="dealerEntry"><section className="dealerEntryBrand"><div className="roleLogo">T</div><h1>TORVO</h1><p>STAFF OPERATIONS APP</p><strong>SALESMAN · STORE KEEPER</strong></section><section className="dealerEntryCard"><span className="eyebrow">AUTHORIZED STAFF LOGIN</span><h2>WELCOME TO TORVO</h2><p>Enter the User ID issued by TORVO. The secure OTP is sent only to the registered TORVO security email.</p><label>USER ID<input value={username} onChange={e=>{setUsername(normalizeStaffUsername(e.target.value).slice(0,6));setErr('')}} placeholder="XX@000" autoCapitalize="characters" autoComplete="username"/></label>{username&&<div className={valid?"inlineSuccess":"inlineError"}>{valid?<><CheckCircle2/>VALID USER ID FORMAT</>:<><XCircle/>ENTER USER ID LIKE XX@000</>}</div>}<button className="primary" disabled={busy||!valid} onClick={send}><ShieldCheck/>{busy&&!sent?'SENDING…':'SEND OTP'}</button>{sent&&<><label>6-DIGIT OTP<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="ENTER OTP"/></label><div className="dealerEntryResend"><span><Clock3/>{resend>0?`RESEND IN 00:${String(resend).padStart(2,'0')}`:'OTP VALID FOR 10 MINUTES'}</span><button disabled={busy||resend>0} onClick={send}><RefreshCw/>RESEND</button></div><button className="primary" disabled={busy||otp.length!==6} onClick={verify}><UserRound/>{busy?'VERIFYING…':'LOGIN'}</button></>}{notice&&!err&&<div className="inlineSuccess">{notice}</div>}{err&&<div className="inlineError" role="alert">{err}</div>}<small>Actual workspace is selected from the server-authorized role. This screen cannot choose or change a role.</small></section></main>
}