import React,{useEffect,useState}from'react';
import{loadLocationStates,loadLocationDistricts,loadLocationCities}from'../services/publicWebsite';

export default function PublicLocationDropdowns({value,onChange,disabled=false,includeContact=false}){
 const[states,setStates]=useState([]),[districts,setDistricts]=useState([]),[cities,setCities]=useState([]),[stateId,setStateId]=useState(''),[districtId,setDistrictId]=useState(''),[loading,setLoading]=useState(''),[error,setError]=useState('');
 const emit=next=>onChange?.({...value,...next});
 useEffect(()=>{let live=true;setLoading('STATE');setError('');loadLocationStates().then(x=>{if(live)setStates(x||[])}).catch(()=>{if(live){setStates([]);setError('LOCATION MASTER NOT AVAILABLE')}}).finally(()=>{if(live)setLoading('')});return()=>{live=false}},[]);
 useEffect(()=>{if(!value?.state){setStateId('');setDistrictId('');setDistricts([]);setCities([]);return}if(!states.length||stateId)return;const row=states.find(x=>String(x.name||'').toUpperCase()===String(value.state||'').toUpperCase());if(!row)return;let live=true;setStateId(row.id);setLoading('DISTRICT');loadLocationDistricts(row.id).then(x=>{if(live)setDistricts(x||[])}).catch(()=>{if(live){setDistricts([]);setError('DISTRICT MASTER NOT AVAILABLE')}}).finally(()=>{if(live)setLoading('')});return()=>{live=false}},[value?.state,states,stateId]);
 useEffect(()=>{if(!value?.district){setDistrictId('');setCities([]);return}if(!districts.length||districtId)return;const row=districts.find(x=>String(x.name||'').toUpperCase()===String(value.district||'').toUpperCase());if(!row)return;let live=true;setDistrictId(row.id);setLoading('CITY');loadLocationCities(row.id).then(x=>{if(live)setCities(x||[])}).catch(()=>{if(live){setCities([]);setError('CITY MASTER NOT AVAILABLE')}}).finally(()=>{if(live)setLoading('')});return()=>{live=false}},[value?.district,districts,districtId]);
 const changeState=async e=>{const id=e.target.value,row=states.find(x=>x.id===id);setStateId(id);setDistrictId('');setDistricts([]);setCities([]);setError('');emit({state:row?.name||'',district:'',city:''});if(!id)return;setLoading('DISTRICT');try{setDistricts(await loadLocationDistricts(id))}catch{setError('DISTRICT MASTER NOT AVAILABLE')}finally{setLoading('')}};
 const changeDistrict=async e=>{const id=e.target.value,row=districts.find(x=>x.id===id);setDistrictId(id);setCities([]);setError('');emit({district:row?.name||'',city:''});if(!id)return;setLoading('CITY');try{setCities(await loadLocationCities(id))}catch{setError('CITY MASTER NOT AVAILABLE')}finally{setLoading('')}};
 const changeCity=e=>{const row=cities.find(x=>x.id===e.target.value);emit({city:row?.name||''})};
 const contact=includeContact?<div className="formTwo"><label>NAME<input name="name" value={value?.name||''} onChange={e=>emit({name:e.target.value.toUpperCase()})} disabled={disabled} autoComplete="name"/></label><label>MOBILE / WHATSAPP (+91)<input name="mobile" inputMode="tel" maxLength="10" value={value?.mobile||''} onChange={e=>emit({mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} disabled={disabled} autoComplete="tel"/></label></div>:null;
 return <>{contact}<div className="formTwo"><label>STATE<select value={stateId} onChange={changeState} disabled={disabled||loading==='STATE'} required><option value="">{loading==='STATE'?'LOADING STATES…':'SELECT STATE'}</option>{states.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>DISTRICT<select value={districtId} onChange={changeDistrict} disabled={disabled||!stateId||loading==='DISTRICT'} required><option value="">{loading==='DISTRICT'?'LOADING DISTRICTS…':'SELECT DISTRICT'}</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="formTwo"><label>CITY<select value={cities.find(x=>x.name===value?.city)?.id||''} onChange={changeCity} disabled={disabled||!districtId||loading==='CITY'} required><option value="">{loading==='CITY'?'LOADING CITIES…':'SELECT CITY'}</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>PIN CODE<input name="pin" inputMode="numeric" maxLength="6" pattern="[0-9]{6}" value={value?.pin||''} onChange={e=>emit({pin:e.target.value.replace(/\D/g,'').slice(0,6)})} disabled={disabled} autoComplete="postal-code" required/></label></div>{error&&<small className="errorText">{error}</small>}</>;
}
