import React,{useEffect,useRef,useState}from'react';
import{loadLocationStates,loadLocationDistricts,loadLocationCities}from'../services/publicWebsite';

const same=(a,b)=>String(a||'').trim().toUpperCase()===String(b||'').trim().toUpperCase();
export default function PublicLocationDropdowns({value,onChange,disabled=false,includeContact=false,allowOtherCity=true}){
 const[states,setStates]=useState([]),[districts,setDistricts]=useState([]),[cities,setCities]=useState([]),[stateId,setStateId]=useState(''),[districtId,setDistrictId]=useState(''),[loading,setLoading]=useState(''),[error,setError]=useState('');
 const requestVersion=useRef({district:0,city:0});
 const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;requestVersion.current.district++;requestVersion.current.city++}},[]);
 const emit=next=>onChange?.({...value,...next});
 useEffect(()=>{let live=true;setLoading('STATE');setError('');loadLocationStates().then(x=>{if(!live)return;const rows=x||[];setStates(rows);if(!rows.length)setError('LOCATION MASTER NOT AVAILABLE')}).catch(()=>{if(live){setStates([]);setError('LOCATION MASTER NOT AVAILABLE')}}).finally(()=>{if(live)setLoading('')});return()=>{live=false}},[]);
 useEffect(()=>{let live=true;const name=String(value?.state||'').trim();if(!name){++requestVersion.current.district;++requestVersion.current.city;setStateId('');setDistrictId('');setDistricts([]);setCities([]);return()=>{live=false}}if(!states.length)return()=>{live=false};const row=states.find(x=>same(x.name,name));if(!row){++requestVersion.current.district;++requestVersion.current.city;setStateId('');setDistrictId('');setDistricts([]);setCities([]);return()=>{live=false}}const current=states.find(x=>x.id===stateId);if(current&&same(current.name,name))return()=>{live=false};const version=++requestVersion.current.district;++requestVersion.current.city;setStateId(row.id);setDistrictId('');setDistricts([]);setCities([]);setLoading('DISTRICT');setError('');loadLocationDistricts(row.id).then(x=>{if(live&&mounted.current&&version===requestVersion.current.district)setDistricts(x||[])}).catch(()=>{if(live&&mounted.current&&version===requestVersion.current.district){setDistricts([]);setError('DISTRICT MASTER NOT AVAILABLE')}}).finally(()=>{if(live&&mounted.current&&version===requestVersion.current.district)setLoading('')});return()=>{live=false}},[value?.state,states,stateId]);
 useEffect(()=>{let live=true;const name=String(value?.district||'').trim();if(!name){++requestVersion.current.city;setDistrictId('');setCities([]);return()=>{live=false}}if(!districts.length)return()=>{live=false};const row=districts.find(x=>same(x.name,name));if(!row){++requestVersion.current.city;setDistrictId('');setCities([]);return()=>{live=false}}const current=districts.find(x=>x.id===districtId);if(current&&same(current.name,name))return()=>{live=false};const version=++requestVersion.current.city;setDistrictId(row.id);setCities([]);setLoading('CITY');setError('');loadLocationCities(row.id).then(x=>{if(live&&mounted.current&&version===requestVersion.current.city)setCities(x||[])}).catch(()=>{if(live&&mounted.current&&version===requestVersion.current.city){setCities([]);setError('CITY MASTER NOT AVAILABLE')}}).finally(()=>{if(live&&mounted.current&&version===requestVersion.current.city)setLoading('')});return()=>{live=false}},[value?.district,districts,districtId]);
 const changeState=async e=>{const id=e.target.value,row=states.find(x=>x.id===id);const version=++requestVersion.current.district;++requestVersion.current.city;setStateId(id);setDistrictId('');setDistricts([]);setCities([]);setError('');emit({state:row?.name||'',district:'',city:'',cityOther:false});if(!id){setLoading('');return}setLoading('DISTRICT');try{const rows=await loadLocationDistricts(id);if(!mounted.current||version!==requestVersion.current.district)return;setDistricts(rows||[]);if(!rows?.length)setError('DISTRICT MASTER NOT AVAILABLE')}catch{if(mounted.current&&version===requestVersion.current.district)setError('DISTRICT MASTER NOT AVAILABLE')}finally{if(version===requestVersion.current.district)setLoading('')}};
 const changeDistrict=async e=>{const id=e.target.value,row=districts.find(x=>x.id===id);const version=++requestVersion.current.city;setDistrictId(id);setCities([]);setError('');emit({district:row?.name||'',city:'',cityOther:false});if(!id){setLoading('');return}setLoading('CITY');try{const rows=await loadLocationCities(id);if(!mounted.current||version!==requestVersion.current.city)return;setCities(rows||[]);if(!rows?.length)setError('CITY MASTER NOT AVAILABLE — USE OTHER FOR YOUR CITY / TOWN')}catch{if(mounted.current&&version===requestVersion.current.city)setError('CITY MASTER NOT AVAILABLE — USE OTHER FOR YOUR CITY / TOWN')}finally{if(version===requestVersion.current.city)setLoading('')}};
 const changeCity=e=>{const id=e.target.value;if(id==='__OTHER__')return emit({city:'',cityOther:true});const row=cities.find(x=>x.id===id);emit({city:row?.name||'',cityOther:false})};
 const knownCity=cities.find(x=>same(x.name,value?.city));
 const otherCity=allowOtherCity&&(Boolean(value?.cityOther)||Boolean(value?.city&&!knownCity&&districtId));
 const cityId=otherCity?'__OTHER__':knownCity?.id||'';
 const contact=includeContact?<div className="formTwo"><label>NAME<input name="name" value={value?.name||''} onChange={e=>emit({name:e.target.value.toUpperCase()})} disabled={disabled} autoComplete="name"/></label><label>MOBILE / WHATSAPP (+91)<input name="mobile" inputMode="tel" maxLength="10" value={value?.mobile||''} onChange={e=>emit({mobile:e.target.value.replace(/\D/g,'').slice(0,10)})} disabled={disabled} autoComplete="tel"/></label></div>:null;
 return <div className="torvoSemanticLocation" data-torvo-semantic="location">{contact}<div className="formTwo"><label>STATE<select value={stateId} onChange={changeState} disabled={disabled||loading==='STATE'} required><option value="">{loading==='STATE'?'LOADING STATES…':'SELECT STATE'}</option>{states.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>DISTRICT<select value={districtId} onChange={changeDistrict} disabled={disabled||!stateId||loading==='DISTRICT'} required><option value="">{loading==='DISTRICT'?'LOADING DISTRICTS…':'SELECT DISTRICT'}</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="formTwo"><label>CITY<select value={cityId} onChange={changeCity} disabled={disabled||!districtId||loading==='CITY'} required><option value="">{loading==='CITY'?'LOADING CITIES…':'SELECT CITY'}</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}{allowOtherCity&&<option value="__OTHER__">OTHER / ADD CITY</option>}</select>{otherCity&&<input className="otherCityInput" name="cityOtherName" placeholder="ENTER YOUR CITY / TOWN NAME" value={value?.city||''} onChange={e=>emit({city:e.target.value.toUpperCase(),cityOther:true})} disabled={disabled} required autoComplete="address-level2"/>}</label><label>PIN CODE<input name="pin" inputMode="numeric" maxLength="6" pattern="[0-9]{6}" value={value?.pin||''} onChange={e=>emit({pin:e.target.value.replace(/\D/g,'').slice(0,6)})} disabled={disabled} autoComplete="postal-code" required/></label></div>{error&&<small className="errorText">{error}</small>}</div>;
}
