import React,{useEffect,useMemo,useState}from'react';import{RefreshCw}from'lucide-react';import{REPORT_CATALOG}from'../config/reports';import{data}from'../services/repository';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
export default function ReportsWorkspace({role}){const[raw,setRaw]=useState(null),[err,setErr]=useState('');const load=async()=>{setErr('');try{setRaw(await data.reportSummary())}catch(e){setErr(e.message)}};useEffect(()=>{load()},[role]);const cards=useMemo(()=>{if(!raw)return[];const conversion=Number(raw.quotation_count)>0?Math.round(Number(raw.accepted_quotation_count||0)*100/Number(raw.quotation_count)):0;return[
{id:'sales',v:raw.sales_total!=null?money(raw.sales_total):null,s:raw.estimate_count!=null?`${raw.estimate_count} estimates · ${raw.sales_order_count||0} orders`:null},
{id:'profit',v:null,s:'Purchase-cost history required before profit can be calculated safely'},
{id:'conversion',v:raw.quotation_count!=null?`${conversion}%`:null,s:raw.quotation_count!=null?`${raw.query_count||0} queries · ${raw.accepted_quotation_count||0}/${raw.quotation_count} quotations accepted`:null},
{id:'order-estimate',v:raw.sales_order_count!=null?`${raw.sales_order_count} / ${raw.estimate_count||0}`:null,s:'Orders / Estimates'},
{id:'outstanding',v:raw.payment_outstanding!=null?money(raw.payment_outstanding):null,s:raw.payment_received!=null?`Received ${money(raw.payment_received)}`:null},
{id:'dealer',v:raw.active_dealers,s:raw.inactive_dealers!=null?`${raw.inactive_dealers} inactive/suspended`:null},
{id:'product',v:raw.delivered_qty!=null?Number(raw.delivered_qty).toLocaleString('en-IN'):null,s:raw.catalog_items!=null?`${raw.catalog_items} active catalog items · delivered qty`:null},
{id:'inventory',v:raw.inventory_units!=null?Number(raw.inventory_units).toLocaleString('en-IN'):null,s:raw.inventory_items!=null?`${raw.inventory_items} items · ${raw.inventory_movements||0} movements · ${raw.low_stock||0} low · ${raw.out_stock||0} out`:null},
{id:'reorder',v:raw.reorder_open,s:raw.reorder_ordered!=null?`${raw.reorder_ordered} ordered · ${raw.low_stock||0} low · ${raw.out_stock||0} out`:null},
{id:'dispatch',v:raw.dispatch_pending,s:raw.dispatch_ready!=null?`${raw.dispatch_ready} ready · ${raw.dispatch_delivered||0} delivered`:null},
{id:'scheme',v:raw.scheme_achieved,s:raw.scheme_participants!=null?`${raw.scheme_participants} participants · ${raw.reward_points_available||0} available points`:null},
{id:'opportunity',v:raw.missing_open,s:raw.missing_total!=null?`${raw.missing_sourced||0} sourced · ${raw.missing_total} total requests`:null},
{id:'audit',v:raw.audit_count,s:raw.audit_users!=null?`${raw.audit_users} acting users`:null}
]},[raw]);const allowed=REPORT_CATALOG.filter(r=>r.roles.includes(role));return <section className="panel workspace"><header><div><h3>Reports Center</h3><p>Role-secured live summaries. Store Keeper receives operational metrics only; financial information is not requested.</p></div><button className="iconBtn" onClick={load}><RefreshCw size={18}/></button></header>{err?<div className="empty"><h3>Unable to load reports</h3><p>{err}</p><button onClick={load}>Retry</button></div>:!raw?<div className="chartEmpty">Loading reports…</div>:<div className="reportGrid">{allowed.map(r=>{const c=cards.find(x=>x.id===r.id),has=c&&c.v!=null;return <article key={r.id}><span>{r.name}</span><strong>{has?c.v:'Not calculated yet'}</strong><small>{c?.s||(has?r.metrics.join(' · '):'Detailed report is pending')}</small></article>})}</div>}</section>}
