import React,{useMemo,useState}from'react';
import{Bell,Box,ChevronRight,ClipboardList,Home,MapPinned,MessageSquare,PackageCheck,QrCode,Search,ShoppingCart,Store,Truck,UserPlus,UserRound,Wrench,X}from'lucide-react';

const configs={
 dealer:{title:'DEALER BUSINESS APP',hello:'DEALER WORKSPACE',actions:[['PRODUCT SEARCH',Search],['PURCHASE ORDER',ShoppingCart],['CUSTOMER REFERRALS',QrCode],['REPAIR REQUESTS',Wrench],['ESTIMATES',ClipboardList],['DELIVERY STATUS',Truck],['SCHEMES & REWARDS',Store],['REQUESTS & MESSAGES',MessageSquare]],note:'PRIVATE DEALER RATES AND BUSINESS DATA ARE AVAILABLE ONLY AFTER TORVO APPROVAL.'},
 salesman:{title:'SALESMAN APP',hello:'FIELD SALES WORKSPACE',actions:[['MY DEALERS',Store],['FIND / ADD RETAILER LEAD',UserPlus],['REPAIR LEAD ROUTING',Wrench],['PRODUCT SEARCH',Search],['ASSISTED ORDER',ShoppingCart],['MY AREA',MapPinned],['ORDER STATUS',ClipboardList],['REQUESTS & MESSAGES',MessageSquare]],note:'ONLY MAPPED DEALERS, AREAS AND OWNER/ADMIN-AUTHORIZED SALES ACTIONS ARE AVAILABLE.'},
 store:{title:'STORE KEEPER APP',hello:'STORE OPERATIONS',actions:[['STOCK LOOKUP',Search],['PICK',Box],['PACK',PackageCheck],['DISPATCH',Truck],['WORK QUEUE',ClipboardList],['REQUESTS & MESSAGES',MessageSquare]],note:'STORE KEEPER HAS OPERATIONAL ACCESS ONLY. ACCOUNTING, PROFIT AND PRIVATE FINANCIAL CONTROLS STAY HIDDEN.'}
};

function WorkSheet({role,open,onClose}){
 const dealerReferral=role==='dealer'&&open==='CUSTOMER REFERRALS';
 const repair=role==='dealer'&&open==='REPAIR REQUESTS';
 const retailer=role==='salesman'&&open==='FIND / ADD RETAILER LEAD';
 const routing=role==='salesman'&&open==='REPAIR LEAD ROUTING';
 return <div className="roleSheetBack" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="roleSheet"><header><div><span>TORVO AUTHORIZED WORKFLOW</span><h2>{open}</h2></div><button onClick={onClose} aria-label="CLOSE"><X/></button></header>
 {dealerReferral&&<><div className="roleFeature"><QrCode/><div><b>SCAN / ENTER TORVO REFERRAL CODE</b><p>VALIDATE CUSTOMER, SELECTED PRODUCT, DEALER, EXPIRY AND APPLICABLE BENEFIT THROUGH THE SERVER BEFORE CONFIRMING.</p></div></div><div className="roleMiniGrid"><button>SCAN CUSTOMER CODE</button><button>ENTER REFERRAL CODE</button><button>VIEW REFERRED CUSTOMERS</button><button>BENEFITS GIVEN</button></div></>}
 {repair&&<><div className="roleFeature"><Wrench/><div><b>REPAIR & SERVICE LEADS</b><p>SEE ONLY TORVO-OFFERED REQUIREMENT DETAILS BEFORE ASSIGNMENT. CUSTOMER CONTACT STAYS PROTECTED UNTIL THE LEAD IS ASSIGNED.</p></div></div><div className="roleMiniGrid"><button>YES, I CAN REPAIR</button><button>NEED MORE DETAILS</button><button>CANNOT REPAIR</button><button>MY ACCEPTED REPAIRS</button></div></>}
 {retailer&&<><div className="roleFeature"><UserPlus/><div><b>FIELD RETAILER / REPAIR DEALER DISCOVERY</b><p>REGISTER A USEFUL MARKET LEAD. THIS DOES NOT CREATE OR APPROVE A DEALER ACCOUNT.</p></div></div><div className="roleLeadForm"><input placeholder="SHOP / FIRM NAME"/><input placeholder="CONTACT PERSON"/><input inputMode="tel" placeholder="MOBILE / WHATSAPP"/><input inputMode="numeric" placeholder="PIN CODE"/><select defaultValue=""><option value="" disabled>CAPABILITY</option><option>PRODUCT SALES</option><option>REPAIR & SERVICE</option><option>PRODUCT SALES + REPAIR & SERVICE</option></select><button>SUBMIT RETAILER LEAD</button></div><p className="roleHint">TORVO ADMIN VERIFICATION AND APPROVAL IS REQUIRED BEFORE THIS LEAD CAN BECOME AN ACTIVE DEALER.</p></>}
 {routing&&<><div className="roleFeature"><MapPinned/><div><b>ROUTE REPAIR REQUIREMENT</b><p>EXACT CUSTOMER PIN IS FIRST PRIORITY. EXPAND ONLY TO VERIFIED NEARBY/SERVICE AREAS. NEVER SHOW A FAKE KM DISTANCE.</p></div></div><div className="roleMiniGrid"><button>NEW REPAIR REQUESTS</button><button>OFFER TO DEALER</button><button>DEALER RESPONSES</button><button>REPAIR DEALER REQUIRED</button></div></>}
 {!dealerReferral&&!repair&&!retailer&&!routing&&<p>THIS WORKSPACE WILL USE ONLY AUTHORIZED SERVER-SIDE BUSINESS FLOWS. NO PREVIEW BUTTON MAY CREATE A FAKE BUSINESS SUCCESS.</p>}
 <button className="roleClose" onClick={onClose}>CLOSE</button></section></div>;
}

export default function RoleAppPreview({role='dealer'}){
 const c=useMemo(()=>configs[role]||configs.dealer,[role]);const[open,setOpen]=useState('');
 return <div className="roleApp"><header><div className="roleLogo">T</div><div><strong>TORVO</strong><small>{c.title}</small></div><button aria-label="NOTIFICATIONS"><Bell/></button></header><main><section className="roleWelcome"><span>{c.hello}</span><h1>FAST DAILY BUSINESS.<br/>ONLY WHAT YOUR ROLE NEEDS.</h1><p>{c.note}</p></section><section className="roleSearch"><Search/><input placeholder="SEARCH MACHINE / SPARE PART / ACCESSORY"/><button>SEARCH</button></section><section className="roleGrid">{c.actions.map(([name,I])=><button key={name} onClick={()=>setOpen(name)}><I/><span>{name}</span><ChevronRight/></button>)}</section><section className="roleSecurity"><UserRound/><div><b>ROLE-BASED PRIVATE WORKSPACE</b><p>REAL ACCESS COMES FROM THE AUTHORIZED USER PROFILE AND SERVER PERMISSIONS, NOT A ROLE SELECTED IN THE PREVIEW.</p></div></section></main><nav><button><Home/><span>HOME</span></button><button><Search/><span>SEARCH</span></button><button><ClipboardList/><span>WORK</span></button><button><UserRound/><span>PROFILE</span></button></nav>{open&&<WorkSheet role={role} open={open} onClose={()=>setOpen('')}/>}</div>;
}
