import React,{useEffect,useState}from'react';
import{RefreshCw,ShieldCheck}from'lucide-react';
import{requireBackend}from'../services/supabase';
const U=v=>String(v||'').toUpperCase();
export default function SalesmanReferralWorkspace(){
 const[code,setCode]=useState(''),[challenge,setChallenge]=useState(''),[otp,setOtp]=useState(''),[rows,setRows]=useState([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 const load=async()=>{setErr('');const{data,error}=await requireBackend().rpc('salesman_my_referral_statement',{p_from:from||null,p_to:to||null});if(error)setErr(U(error.message));else setRows(data||[])};
 useEffect(()=>{load()},[]);
 const start=async e=>{e.preventDefault();setBusy(true);setErr('');setMsg('');const{data,error}=await requireBackend().rpc('salesman_start_referral_otp',{p_referral_code:U(code).trim()});setBusy(false);if(error){const m=U(error.message);setErr(m.includes('WHATSAPP OTP WORKER NOT CONFIGURED')?'WHATSAPP OTP SERVICE IS NOT CONFIGURED YET. OTP WAS NOT SENT. CONTACT ADMIN.':m);return}const c=Array.isArray(data)?data[0]:data;if(!c?.challenge_id){setErr('OTP CHALLENGE WAS NOT CREATED. OTP WAS NOT SENT.');return}setChallenge(c.challenge_id);setMsg('OTP SENT TO THE VERIFIED WHATSAPP NUMBER. ENTER IT BELOW.')};
 const verify=async e=>{e.preventDefault();if(!challenge)return;setBusy(true);setErr('');setMsg('');const{error}=await requireBackend().rpc('salesman_verify_referral_otp',{p_challenge_id:challenge,p_otp:otp});setBusy(false);if(error)setErr(U(error.message));else{setMsg('REFERRAL VERIFIED SUCCESSFULLY.');setChallenge('');setOtp('');setCode('');await load()}};
 return <section className="salesmanHub"><section className="welcome salesmanHero"><div><span className="eyebrow">SECURE REFERRAL</span><h2>REFERRAL OTP & STATEMENT</h2><p>OTP IS SENT ONLY THROUGH THE TRUSTED WHATSAPP SERVICE. THE APP NEVER GENERATES OR DISPLAYS OTP.</p></div><ShieldCheck/></section>{err&&<div className="inlineError">{err}</div>}{msg&&<div className="inlineSuccess">{msg}</div>}<section className="panel"><header><div><h3>VERIFY DEALER REFERRAL</h3><p>ONLY REFERRALS FOR YOUR ACTIVE MAPPED DEALERS CAN BE VERIFIED.</p></div></header><form className="modalForm" onSubmit={start}><label>REFERRAL CODE<input value={code} onChange={e=>setCode(U(e.target.value))} required/></label><button className="primary" disabled={busy||!code.trim()}>{busy?'PLEASE WAIT…':'SEND WHATSAPP OTP'}</button></form>{challenge&&<form className="modalForm" onSubmit={verify}><label>6-DIGIT OTP<input inputMode="numeric" maxLength="6" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} required/></label><button className="primary" disabled={busy||otp.length!==6}>{busy?'VERIFYING…':'VERIFY REFERRAL'}</button></form>}</section><section className="panel"><header><div><h3>MY REFERRAL STATEMENT</h3><p>SERVER-SCOPED VERIFIED REFERRALS ONLY.</p></div><button className="iconBtn" onClick={load}><RefreshCw size={18}/></button></header><div className="modalForm"><label>FROM<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>TO<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load}>APPLY DATE FILTER</button></div><div className="requestList">{rows.length===0?<div className="chartEmpty">NO VERIFIED REFERRAL IN THIS PERIOD.</div>:rows.map(r=><article key={r.referral_id}><div><strong>{U(r.referral_code)} · {U(r.dealer_name)}</strong><span>{U(r.product_name)}</span><small>{r.created_at?new Date(r.created_at).toLocaleDateString('en-IN'):''}</small></div><b>{U(r.status)}</b></article>)}</div></section></section>;
}
